api:
    entities:
        Oro\Bundle\OrderBundle\Entity\Order:
            documentation_resource: '@OroOrderBundle/Resources/doc/api/order.md'
            fields:
                paymentTerm:
                    property_path: payment_term_7c4f1e8e
                source:
                    data_type: nestedAssociation
                    fields:
                        __class__:
                            property_path: sourceEntityClass
                        id:
                            property_path: sourceEntityId
                subtotalValue:
                    form_options:
                        mapped: false
                totalValue:
                    form_options:
                        mapped: false
                totalDiscountsAmount:
                    form_options:
                        mapped: false
            filters:
                fields:
                    external: ~
            sorters:
                fields:
                    external: ~
            actions:
                update:
                    fields:
                        currency:
                            form_options:
                                mapped: false
                        external:
                            form_options:
                                mapped: false
                update_list: true

        Extend\Entity\EV_Order_Internal_Status:
            actions: false

        Oro\Bundle\OrderBundle\Entity\OrderLineItem:
            documentation_resource: '@OroOrderBundle/Resources/doc/api/order_line_item.md'
            fields:
                value:
                    form_options:
                        mapped: false
                currency:
                    form_options:
                        mapped: false
                productUnitCode:
                    form_options:
                        mapped: false
            subresources:
                order:
                    actions:
                        update_relationship: false

        Oro\Bundle\OrderBundle\Entity\OrderAddress:
            documentation_resource: '@OroOrderBundle/Resources/doc/api/order_address.md'
            fields:
                createdAt:
                    property_path: created
                updatedAt:
                    property_path: updated
                customRegion:
                    exclude: false # set manually because this field is marked as excluded in entity.yml
                    property_path: regionText
            subresources:
                country:
                    actions:
                        update_relationship: false
                region:
                    actions:
                        update_relationship: false

        Oro\Bundle\OrderBundle\Entity\OrderDiscount:
            documentation_resource: '@OroOrderBundle/Resources/doc/api/order_discount.md'
            fields:
                percent:
                    data_type: percent_100
            actions:
                update:
                    fields:
                        order:
                            form_options:
                                mapped: false
            subresources:
                order:
                    actions:
                        update_relationship: false

        Oro\Bundle\OrderBundle\Entity\OrderShippingTracking:
            documentation_resource: '@OroOrderBundle/Resources/doc/api/order_shipping_tracking.md'
