oro_api:
    error_title_overrides:
        'not blank discount value constraint': 'not blank constraint'

oro_entity:
    entity_name_representation:
        Oro\Bundle\OrderBundle\Entity\Order:
            full: [ identifier ]
