oro_permissions:
    VIEW_PAYMENT_HISTORY:
        label: oro.order.permission.view_payment_history.label
        apply_to_all: false
        apply_to_entities:
            - 'Oro\Bundle\OrderBundle\Entity\Order'
        group_names:
            - 'default'

    CHARGE_AUTHORIZED_PAYMENTS:
        label: oro.order.permission.charge_authorized_payments.label
        apply_to_all: false
        apply_to_entities:
            - 'Oro\Bundle\OrderBundle\Entity\Order'
        group_names:
            - 'default'

    CANCEL_PAYMENTS:
        label: oro.order.permission.cancel_payments.label
        apply_to_all: false
        apply_to_entities:
            - 'Oro\Bundle\OrderBundle\Entity\Order'
        group_names:
            - 'default'

    REFUND_PAYMENTS:
        label: oro.order.permission.refund_payments.label
        apply_to_all: false
        apply_to_entities:
            - 'Oro\Bundle\OrderBundle\Entity\Order'
        group_names:
            - 'default'

    CANCEL_ORDERS:
        label: oro.order.permission.cancel_orders.label
        apply_to_all: false
        apply_to_entities:
            - 'Oro\Bundle\OrderBundle\Entity\Order'
        group_names:
            - 'default'

    CLOSE_ORDERS:
        label: oro.order.permission.close_orders.label
        apply_to_all: false
        apply_to_entities:
            - 'Oro\Bundle\OrderBundle\Entity\Order'
        group_names:
            - 'default'
