placeholders:
    placeholders:
        scripts_before:
            items:
                line_item_templates: ~

    items:
        line_item_templates:
            template: '@@OroOrder/Js/line_item_templates.js.twig'
            applicable: "@oro_layout.helper->isTemplateRequest()"
        order_create_for_customer_user_link:
            template: '@@OroOrder/CustomerUser/createOrderLink.html.twig'
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\CustomerBundle\Entity\CustomerUser)'
            acl: [ oro_order_create ]
        order_create_for_customer_user_button:
            template: '@@OroOrder/CustomerUser/createOrderButton.html.twig'
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\CustomerBundle\Entity\CustomerUser)'
            acl: [ oro_order_create ]
        order_create_for_customer_link:
            template: '@@OroOrder/Customer/createOrderLink.html.twig'
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\CustomerBundle\Entity\Customer)'
            acl: [ oro_order_create ]
        order_create_for_customer_button:
            template: '@@OroOrder/Customer/createOrderButton.html.twig'
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\CustomerBundle\Entity\Customer)'
            acl: [ oro_order_create ]
