datagrids:
    base-orders-grid:
        extended_entity_name: 'Oro\Bundle\OrderBundle\Entity\Order'
        options:
            entityHint: oro.order.entity_plural_label
            entity_pagination: true
        source:
            type:         orm
            query:
                select:
                    - DISTINCT order1.id
                    - order1.identifier
                    - order1.poNumber
                    - order1.currency
                    - order1.subtotalValue as subtotal
                    - order1.totalValue as total
                    - order1.shipUntil
                    - order1.createdAt
                    - order1.updatedAt
                    - payment_status.paymentStatus as paymentStatus
                    - order1.shippingMethod
                    - order1.shippingMethodType
                    - IDENTITY(order1.organization) as organizationId
                    - order1.totalDiscountsAmount
                from:
                    - { table: 'Oro\Bundle\OrderBundle\Entity\Order', alias: order1 }
                join:
                    left:
                        - join: 'Oro\Bundle\PaymentBundle\Entity\PaymentStatus'
                          alias: payment_status
                          conditionType: WITH
                          condition: 'payment_status.entityIdentifier = order1.id AND payment_status.entityClass = ''Oro\Bundle\OrderBundle\Entity\Order'''
        properties:
            id: ~
            view_link:
                type:  url
                params: [ id ]

        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye
                rowAction:     true

    frontend-orders-grid:
        acl_resource: oro_order_frontend_view
        extends: base-orders-grid
        update: false
        delete: false
        options:
            frontend: true
        source:
            query:
                select:
                    - partial order1.{id, shippingAddress}
                join:
                    left:
                        - { join: order1.shippingAddress, alias: shippingAddress }
        columns:
            identifier:
                label: oro.order.identifier.label
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            shippingAddress:
                label: oro.order.shipping_address.label
                type: twig
                template: '@OroOrder/Order/Datagrid/frontendShippingAddress.html.twig'
                frontend_type: html
            total:
                label: oro.order.total.label
                frontend_type: multi-currency
                type: callback
                callable: [ '@oro_currency.converter.currency_to_string', 'convert' ]
                multicurrency_config:
                    currency_field: currency
            paymentMethods:
                label: oro.order.payment_method.label
                type: twig
                template: '@OroOrder/Order/Datagrid/paymentMethod.html.twig'
                frontend_type: html
            paymentStatus:
                label: oro.order.payment_status.label
                type: twig
                frontend_type: html
                template: '@OroOrder/Order/Datagrid/frontendPaymentStatus.html.twig'
            #Hidden fields goes next
            poNumber:
                label: oro.order.po_number.label
                renderable: false
            shipUntil:
                label: oro.order.ship_until.label
                frontend_type: date
                renderable: false
            currency:
                label: oro.order.currency.label
                renderable: false
            subtotal:
                label: oro.order.subtotal.label
                frontend_type: multi-currency
                type: callback
                callable: [ '@oro_currency.converter.currency_to_string', 'convert' ]
                multicurrency_config:
                    currency_field: currency
                renderable: false
            shippingMethod:
                label: oro.order.shipping_method.label
                type: twig
                frontend_type: html
                template: '@OroOrder/Order/Datagrid/frontendShippingMethodFull.html.twig'
                renderable: false
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
                renderable: false
        sorters:
            columns:
                poNumber:
                    data_name: order1.poNumber
                shipUntil:
                    data_name: order1.shipUntil
                createdAt:
                    data_name: order1.createdAt
                updatedAt:
                    data_name: order1.updatedAt
                identifier:
                    data_name: order1.identifier
                currency:
                    data_name: order1.currency
                subtotal:
                    data_name: subtotal
                total:
                    data_name: total
            default:
                createdAt: DESC
        filters:
            columns:
                poNumber:
                    type: string
                    data_name: order1.poNumber
                shipUntil:
                    type: date
                    data_name: order1.shipUntil
                createdAt:
                    type: datetime
                    data_name: order1.createdAt
                updatedAt:
                    type: datetime
                    data_name: order1.updatedAt
                paymentStatus:
                    type: choice
                    data_name: paymentStatus
                    options:
                        field_options:
                            choices: "@oro_payment.formatter.payment_status_label->getAvailableStatuses"
                            translatable_options: false
                identifier:
                    type: string
                    data_name: order1.identifier
                currency:
                    type: choice
                    data_name: order1.currency
                    options:
                        field_options:
                            choices: "@oro_currency.config.currency->getCurrencies"
                            translatable_options: false
                subtotal:
                    type: currency
                    data_name: subtotal
                    renderable: false
                total:
                    type: currency
                    data_name: total
        properties:
            id: ~
            view_link:
                route: oro_order_frontend_view
            view_aria_label:
                type: translatable
                key: oro.frontend.order.action.view.aria_label
                params: [ identifier ]
            start_from_order_aria_label:
                type: translatable
                key: oro.frontend.order.action.start_from_order.aria_label
                params: [ identifier ]
        actions:
            view:
                ariaLabel: view_aria_label
                acl_resource: oro_order_frontend_view

    order-products-previously-purchased-grid:
        extends: frontend-product-search-grid
        acl_resource: oro_order_frontend_view
        source:
            query:
                select:
                    - datetime.ordered_at_by.CUSTOMER_USER_ID as recency
                where:
                    and:
                        - datetime.ordered_at_by.CUSTOMER_USER_ID >= @oro_order.previously_purchased.configuration->getPreviouslyPurchasedStartDateString()
        columns:
            recency:
                label: oro.order.recency.label
                frontend_type: datetime
        sorters:
            toolbar_sorting: true
            disable_default_sorting: false
            disable_not_selected_option: true
            columns:
                recency:
                    type: datetime
                    data_name: datetime.ordered_at_by.CUSTOMER_USER_ID
            default:
                recency: DESC

    base-order-line-items-grid:
        extended_entity_name: 'Oro\Bundle\OrderBundle\Entity\OrderLineItem'
        options:
            entityHint: oro.order.orderlineitem.entity_plural_label
        source:
            type: orm
            query:
                select:
                    - partial order_item.{ id, currency, value }
                    - order_item.productSku
                    - order_item.freeFormProduct
                    - order_item.quantity
                    - order_item.productUnitCode
                    - order_item.shipBy
                    - order_item.comment
                    - order_item.productName
                    - order_item.productVariantFields
                    - order_item.shippingMethod
                    - order_item.shippingMethodType
                    - order_item.shippingEstimateAmount
                from:
                    - { table: 'Oro\Bundle\OrderBundle\Entity\OrderLineItem', alias: order_item }
                join:
                    left:
                        - { join: order_item.product, alias: product }
                where:
                    and:
                        - order_item.order = :order_id
                orderBy:
                    - column: order_item.id
                      dir: ASC
            bind_parameters:
                - order_id

    order-line-items-grid:
        extends: base-order-line-items-grid
        columns:
            productSku:
                label: oro.product.sku.label
                cellClassName: 'direction-ltr'
            product:
                label:         oro.product.entity_label
                type:          twig
                frontend_type: html
                template:      '@OroOrder/Order/Datagrid/product.html.twig'
            quantity:
                label: oro.order.orderlineitem.quantity.label
                frontend_type: decimal
            productUnitCode:
                label: oro.order.orderlineitem.product_unit_code.label
            price:
                label:         oro.order.orderlineitem.price.label
                type:          twig
                frontend_type: html
                template:      '@OroOrder/Order/Datagrid/price.html.twig'
            shipBy:
                label:         oro.order.orderlineitem.ship_by.label
                frontend_type: date
            comment:
                label: oro.order.orderlineitem.comment.label
            shippingMethod:
                label:         oro.order.datagrid.orderlineitems.shipping_method.label
                type:          twig
                frontend_type: html
                template:      '@OroOrder/Order/Datagrid/shippingMethodFull.html.twig'
                renderable:    false
            shippingEstimateAmount:
                label:         oro.order.datagrid.orderlineitems.shipping_cost.label
                type:          twig
                frontend_type: html
                template:      '@OroOrder/Order/Datagrid/lineItemShippingCost.html.twig'
                renderable:    false

    order-line-items-grid-frontend:
        extends: base-order-line-items-grid
        columns:
            product:
                label:         oro.product.entity_label
                type:          twig
                frontend_type: html
                template:      '@OroOrder/Order/Datagrid/frontendProduct.html.twig'
            quantity:
                label:         oro.order.orderlineitem.quantity.label
                type:          twig
                frontend_type: html
                template:      '@OroOrder/Order/Datagrid/frontendQuantity.html.twig'
            price:
                label:         oro.order.orderlineitem.price.label
                type:          twig
                frontend_type: html
                template:      '@OroOrder/Order/Datagrid/price.html.twig'
            shipBy:
                label:         oro.order.orderlineitem.ship_by.label
                frontend_type: date
            comment:
                label:         oro.order.orderlineitem.comment.label
        options:
            toolbarOptions:
                placement:
                    bottom: true
            frontend: true
