aliases:
    oro/filter/product-price-filter$: oropricing/js/filter/product-price-filter
app-modules:
    - oropricing/js/app/modules/validator-constraints-module
dynamic-imports:
    commons:
        - oropricing/js/validator/unique-product-prices
    orodatagrid:
        - oro/filter/product-price-attribute-filter
        - oro/filter/product-price-filter
    orosale:
        - oropricing/js/app/components/price-lists-errors-handler
        - oropricing/js/app/components/product-sidebar-component
        - oropricing/js/app/components/product-unit-precision-limitations-component
        - oropricing/js/app/components/totals-component
        - oropricing/js/app/components/product-prices-update-widget-component
        - oropricing/js/app/views/expression-field-switcher
        - oropricing/js/app/views/line-item-product-prices-view
        - oropricing/js/app/views/line-item-product-prices-extended-view
        - oropricing/js/app/views/price-list-currency-limitations-view
        - oropricing/js/app/views/quantity-switcher
map:
    '*':
        oro/filter/product-price-attribute-filter: oro/filter/product-price-filter
