navigation:
    menu_config:
        items:
            pricing_price_lists_list:
                label:           'oro.pricing.pricelist.entity_plural_label'
                route:           'oro_pricing_price_list_index'
                position:        500
                extras:
                    routes:      ['/^oro_pricing_price_list/']
                    description: 'oro.pricing.menu.price_lists_list.description'

            pricing_price_attribute_price_lists_list:
                label:           'oro.pricing.priceattributepricelist.entity_plural_label'
                route:           'oro_pricing_price_attribute_price_list_index'
                position:        90
                extras:
                    routes:      ['/^oro_pricing_price_attribute_price_list/']
                    description: 'oro.pricing.menu.price_attribute_price_lists_list.description'

            pricing_product_price_debug:
                label: 'oro.pricing.productprice.debug.page_title'
                route: 'oro_pricing_price_product_debug_index'
                position: 600
                extras:
                    routes: ['/^oro_pricing_price_product_debug/']
                    description: 'oro.pricing.menu.product_price_debug.description'

            shortcut_pricing_price_attribute_price_list:
                label:           'oro.pricing.priceattributepricelist.entity_plural_label'
                route:           'oro_pricing_price_attribute_price_list_index'
                extras:
                    description: 'oro.pricing.menu.shortcut_price_lists.description'

            shortcut_pricing_price_list:
                label:           'oro.pricing.pricelist.entity_plural_label'
                route:           'oro_pricing_price_list_index'
                extras:
                    description: 'oro.pricing.menu.shortcut_price_lists.description'

            shortcut_pricing_new_price_list:
                label:           'oro.pricing.menu.shortcut_new_price_list.label'
                route:           'oro_pricing_price_list_create'
                extras:
                    description:    'oro.pricing.menu.shortcut_price_lists.description'
                    is_custom_action: true

        tree:
            application_menu:
                children:
                    sales_tab:
                        children:
                            pricing_price_lists_list: ~
                            pricing_product_price_debug: ~
                    products_tab:
                        children:
                            pricing_price_attribute_price_lists_list: ~
            shortcuts:
                children:
                    shortcut_pricing_price_list: ~
                    shortcut_pricing_price_attribute_price_list: ~
                    shortcut_pricing_new_price_list:   ~

    titles:
        oro_pricing_price_list_index:   ~
        oro_pricing_price_list_view:   '%name%'
        oro_pricing_price_list_update: '%name% - Edit'
        oro_pricing_price_list_create: oro.ui.create_entity

        oro_pricing_price_attribute_price_list_index:  ~
        oro_pricing_price_attribute_price_list_view:   '%name%'
        oro_pricing_price_attribute_price_list_update: '%name% - Edit'
        oro_pricing_price_attribute_price_list_create: oro.ui.create_entity

        pricing_product_price_debug: ~
