system_configuration:
    groups:
        pricing_general:
            title: oro.pricing.system_configuration.groups.pricing_general.title
        default_price_lists:
            title: oro.pricing.system_configuration.groups.default_price_lists.title
        price_rounding:
            title: oro.pricing.system_configuration.groups.price_rounding.title
        price_lists_update:
            title: oro.pricing.system_configuration.groups.price_lists_update.title
        pricing:
            title: oro.pricing.system_configuration.groups.pricing.title
            icon: 'fa-credit-card'
        price_strategies:
            title: oro.pricing.system_configuration.groups.price_strategies.title
        minimum_sellable_quantity:
            title: oro.pricing.system_configuration.groups.minimum_sellable_quantity.title
    fields:
        oro_pricing.default_price_list:
            data_type: integer
            type: Oro\Bundle\PricingBundle\Form\Type\PriceListSelectType
            options:
                label: oro.pricing.pricelist.entity_label
        oro_pricing.default_price_lists:
            data_type: array
            type: Oro\Bundle\PricingBundle\Form\Type\PriceListSystemConfigType
            options:
                label: oro.pricing.system_configuration.fields.price_lists.title
                resettable: false
        oro_pricing.rounding_type:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            priority: 10
            options:
                label: oro.pricing.system_configuration.fields.rounding_type.label
                tooltip: oro.pricing.system_configuration.fields.rounding_type.tooltip
                required: true
                constraints:
                    - NotBlank: ~
                choice_translation_domain: messages
                choices:
                    oro.pricing.system_configuration.fields.rounding_type.choices.ceil.label: 0
                    oro.pricing.system_configuration.fields.rounding_type.choices.floor.label: 1
                    oro.pricing.system_configuration.fields.rounding_type.choices.half_down.label: 5
                    oro.pricing.system_configuration.fields.rounding_type.choices.half_up.label: 6
                    oro.pricing.system_configuration.fields.rounding_type.choices.half_even.label: 4
        oro_pricing.precision:
            data_type: integer
            type: Symfony\Component\Form\Extension\Core\Type\IntegerType
            search_type: text
            priority: 20
            options:
                label: oro.pricing.system_configuration.fields.precision.label
                tooltip: oro.pricing.system_configuration.fields.precision.tooltip
                required: true
                constraints:
                    - NotBlank: ~
                    - Range:
                        min: 0
                    - Type:
                        type: integer
        oro_pricing.price_calculation_precision:
            data_type: integer
            type: Symfony\Component\Form\Extension\Core\Type\IntegerType
            search_type: text
            priority: 30
            options:
                label: oro.pricing.system_configuration.fields.price_calculation_precision.label
                tooltip: oro.pricing.system_configuration.fields.price_calculation_precision.tooltip
                constraints:
                    - Range:
                        min: 0
                        max: 4
                    - Type:
                        type: integer
        oro_pricing.offset_of_processing_cpl_prices:
            data_type: float
            type: Symfony\Component\Form\Extension\Core\Type\NumberType
            search_type: text
            options:
                label: oro.pricing.system_configuration.fields.offset_of_processing_cpl_prices.label
                tooltip: oro.pricing.system_configuration.fields.offset_of_processing_cpl_prices.tooltip
                required: true
                constraints:
                    - NotBlank: ~
                    - Type:
                        type: float
                    - 'Oro\Bundle\ValidationBundle\Validator\Constraints\GreaterThanZero': ~
        oro_pricing.price_strategy:
            data_type: string
            type: Oro\Bundle\PricingBundle\Form\Type\PriceListStrategySelectType
            options:
                label: oro.pricing.system_configuration.fields.pricing_strategy.label
                required: true
                multiple: false
                constraints:
                    - NotBlank: ~
        oro_pricing.fractional_quantity_less_then_unit_price_calculation:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 15
            options:
                required: false
                label: oro.pricing.system_configuration.fields.fractional_quantity_less_then_unit_price_calculation.label
                tooltip: oro.pricing.system_configuration.fields.fractional_quantity_less_then_unit_price_calculation.tooltip
        oro_pricing.fractional_quantity_less_then_minimum_priced_price_calculation:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 15
            options:
                required: false
                label: oro.pricing.system_configuration.fields.fractional_quantity_less_then_minimum_priced_price_calculation.label
                tooltip: oro.pricing.system_configuration.fields.fractional_quantity_less_then_minimum_priced_price_calculation.tooltip
        oro_pricing.quantity_less_then_minimum_priced_price_calculation:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 15
            options:
                required: false
                label: oro.pricing.system_configuration.fields.quantity_less_then_minimum_priced_price_calculation.label
                tooltip: oro.pricing.system_configuration.fields.quantity_less_then_minimum_priced_price_calculation.tooltip
        oro_pricing.feature_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 20
            page_reload: true
            options:
                required: false
                label: oro.pricing.system_configuration.fields.feature_enabled.label
                tooltip: oro.pricing.system_configuration.fields.feature_enabled.tooltip
    tree:
        system_configuration:
            commerce:
                children:
                    catalog:
                        children:
                            pricing:
                                priority: 100
                                children:
                                    pricing_general:
                                        priority: 300
                                        children:
                                            - oro_pricing.feature_enabled
                                    price_rounding:
                                        priority: 200
                                        children:
                                            - oro_pricing.rounding_type
                                            - oro_pricing.precision
                                            - oro_pricing.price_calculation_precision
                                    default_price_lists:
                                        priority: 100
                                        children:
                                            - oro_pricing.default_price_list
                                            - oro_pricing.default_price_lists
                                    price_lists_update:
                                        priority: 50
                                        children:
                                            - oro_pricing.offset_of_processing_cpl_prices
                                    price_strategies:
                                        priority: 25
                                        children:
                                            - oro_pricing.price_strategy
                                    minimum_sellable_quantity:
                                        priority: 15
                                        children:
                                            - oro_pricing.fractional_quantity_less_then_unit_price_calculation
                                            - oro_pricing.fractional_quantity_less_then_minimum_priced_price_calculation
                                            - oro_pricing.quantity_less_then_minimum_priced_price_calculation
