services:
    _defaults:
        public: true

    Oro\Bundle\OrderBundle\Controller\OrderController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\OrderBundle\Controller\AjaxOrderController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\OrderBundle\Controller\Frontend\OrderController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\OrderBundle\Controller\Frontend\ProductsController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\OrderBundle\Controller\DashboardController:
        arguments:
            - '@oro_order.provider.dashboard.sales_orders_chart_widget_provider.volume'
            - '@oro_order.provider.dashboard.sales_orders_chart_widget_provider.number'
