services:
    oro_order.form.type.order:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderType'
        arguments:
            - '@oro_order.order.provider.order_address_security'
            - '@oro_order.handler.order_currency_handler'
            - '@oro_order.form.type.event_listener.subtotals_subscriber'
        tags:
            - { name: form.type, alias: oro_order_type }

    oro_order.form.type.suborder:
        class: 'Oro\Bundle\OrderBundle\Form\Type\SubOrderType'
        arguments:
            - '@oro_order.order.provider.order_address_security'
            - '@oro_order.handler.order_currency_handler'
            - '@oro_order.form.type.event_listener.subtotals_subscriber'
        tags:
            - { name: form.type, alias: oro_suborder_type }

    oro_order.form.type.order_address_select:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderAddressSelectType'
        arguments:
            - '@oro_order.manager.order_address'
            - '@oro_locale.formatter.address'
            - '@oro_order.order.provider.order_address_security'
            - '@oro_importexport.serializer'
        tags:
            - { name: form.type, alias: order_address_select }

    oro_order.form.type.order_address:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderAddressType'
        arguments:
            - '@oro_order.manager.order_address'
            - '@oro_order.order.provider.order_address_security'
        tags:
            - { name: form.type, alias: oro_order_address_type }

    oro_order.form.section.provider:
        class: 'Oro\Bundle\OrderBundle\Form\Section\SectionProvider'
        public: false
        arguments:
             - '@form.registry'

    oro_order.form.type.order_line_item:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderLineItemType'
        arguments:
            - '@oro_product.provider.product_units_provider'
            - '@oro_order.form.type.event_listener.order_line_item_product'
            - '@oro_order.form.type.event_listener.order_line_item_checksum'
        calls:
            - [setDataClass, ['Oro\Bundle\OrderBundle\Entity\OrderLineItem']]
            - [setSectionProvider, ['@oro_order.form.section.provider']]
        tags:
            - { name: form.type }

    oro_order.form.type.event_listener.order_line_item_product:
        class: Oro\Bundle\OrderBundle\Form\Type\EventListener\OrderLineItemProductListener
        arguments:
            - '@oro_entity.tools.entity_state_checker'

    oro_order.form.type.event_listener.order_line_item_checksum:
        class: Oro\Bundle\OrderBundle\Form\Type\EventListener\OrderLineItemChecksumListener
        arguments:
            - '@oro_product.line_item_checksum_generator'

    oro_order.form.type.order_product_kit_item_line_item:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderProductKitItemLineItemType'
        arguments:
            - '@oro_order.product_kit.provider.product_kit_item_products'
            - '@oro_order.form.type.event_listener.order_product_kit_item_line_item_default_data'
            - '@oro_order.form.type.event_listener.order_product_kit_item_line_item_ghost_option'
        tags:
            - { name: form.type }

    oro_order.form.type.event_listener.order_product_kit_item_line_item_default_data:
        class: Oro\Bundle\OrderBundle\Form\Type\EventListener\OrderProductKitItemLineItemDefaultDataListener
        arguments:
            - '@oro_order.product_kit.factory.order_product_kit_item_line_item'

    oro_order.form.type.event_listener.order_product_kit_item_line_item_ghost_option:
        class: Oro\Bundle\OrderBundle\Form\Type\EventListener\OrderProductKitItemLineItemGhostOptionListener

    oro_order.form.type.order_product_kit_item_line_item_collection:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderProductKitItemLineItemCollectionType'
        tags:
            - { name: form.type }

    oro_order.form.type.order_line_item_collection:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderLineItemsCollectionType'
        tags:
            - { name: form.type }

    oro_order.form.type.extension.order_data_storage:
        class: 'Oro\Bundle\OrderBundle\Form\Extension\OrderDataStorageExtension'
        arguments:
            - '@request_stack'
            - '@oro_product.storage.product_data_storage'
            - '@form.property_accessor'
            - '@doctrine'
            - '@logger'
        tags:
            - { name: form.type_extension }

    oro_order.form.type.order_collection_table:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderCollectionTableType'
        tags:
            - { name: form.type, alias: "oro_order_collection_table" }

    oro_order.form.type.order_discount_collection_row:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderDiscountCollectionRowType'
        calls:
            - [setDataClass, ['Oro\Bundle\OrderBundle\Entity\OrderDiscount']]
        tags:
            - { name: form.type, alias: "oro_order_discount_collection_row" }

    oro_order.form.type.order_discount_collection_table:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderDiscountCollectionTableType'
        tags:
            - { name: form.type, alias: "oro_order_discount_collection_table" }

    oro_order.form.type.order_discount_item:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderDiscountItemType'
        arguments:
            - '@oro_order.order.total.total_helper'
        calls:
            - [setDataClass, ['Oro\Bundle\OrderBundle\Entity\OrderDiscount']]
        tags:
            - { name: form.type, alias: "oro_order_discount_item" }

    oro_order.form.type.event_listener.subtotals_subscriber:
        class: 'Oro\Bundle\OrderBundle\Form\Type\EventListener\SubtotalSubscriber'
        public: true
        arguments:
            - '@oro_order.order.total.total_helper'
            - '@oro_order.pricing.price_matcher'
            - !service
                class: Oro\Bundle\OrderBundle\Handler\OrderLineItemCurrencyHandler

    oro_order.form.type.order_shipping_tracking:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderShippingTrackingType'
        arguments:
            - '@oro_shipping.tracking_aware_shipping_methods_provider'
        tags:
            - { name: form.type }

    oro_order.form.type.order_shipping_tracking_collection:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderShippingTrackingCollectionType'
        tags:
            - { name: form.type }

    oro_order.form.type.select_switch_input:
        class: 'Oro\Bundle\OrderBundle\Form\Type\SelectSwitchInputType'
        tags:
            - { name: form.type }

    oro_order.form.type.order_price:
        class: 'Oro\Bundle\OrderBundle\Form\Type\OrderPriceType'
        tags:
            - { name: form.type }
