services:
    oro_order.tests.entity_name_resolver.data_loader:
        class: Oro\Bundle\OrderBundle\Tests\Functional\Environment\TestEntityNameResolverDataLoader
        decorates: oro_entity.tests.entity_name_resolver.data_loader
        arguments:
            - '@.inner'

    oro_order.tests.api.skipped_entity_provider:
        class: Oro\Bundle\ApiBundle\Tests\Functional\Environment\SkippedEntityProvider
        decorates: oro_api.tests.skipped_entity_provider
        arguments:
            - '@.inner'
        calls:
            - [addSkippedEntity, ['Oro\Bundle\OrderBundle\Api\Model\OrderSubtotal', ['get_list']]]
