operations:
    b2b_flow_checkout_new_address:
        label: oro.checkout.form.address.manual
        enabled: true
        page_reload: false
        applications: [commerce]
        acl_resource: oro_checkout_frontend_checkout
        frontend_options:
            template: '@OroCheckout/Action/address.html.twig'

    b2b_flow_checkout_new_billing_address:
        extends: b2b_flow_checkout_new_address
        attributes:
            visitor_email:
                label: oro.customer.customeruser.username.label
                type: string
            address:
                property_path: data.billingAddress
            save_address:
                label: oro.checkout.save_billing_address.label
                type: boolean
        form_options:
            attribute_fields:
                visitor_email:
                    form_type: Oro\Bundle\CustomerBundle\Form\Type\CustomerVisitorEmailAddressType
                address:
                    form_type: Oro\Bundle\CheckoutBundle\Form\Type\CheckoutAddressType
                    options:
                        object: $.data
                        addressType: 'billing'
                        required: true
                        constraints:
                            - Valid: ~
                            - NotBlank: ~
                            - Oro\Bundle\AddressBundle\Validator\Constraints\NameOrOrganization: ~
                save_address:
                    form_type: Oro\Bundle\CheckoutBundle\Form\Type\SaveAddressType
        form_init:
            - '@call_service_method':
                service: oro_workflow.manager
                method: getFirstWorkflowItemByEntity
                method_parameters: [$.data]
                attribute: $.workflowItem
            - '@assign_value': [$.visitor_email, $.workflowItem.data.email]
            - '@assign_value': [$.address, $.data.billingAddress]
            - '@tree':
                conditions:
                    '@and':
                        - '@acl_granted': 'CREATE;entity:Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress'
                        - '@acl_granted': 'CREATE;entity:Oro\Bundle\CustomerBundle\Entity\CustomerAddress'
                actions:
                    - '@assign_value': [$.save_address, $.data.saveBillingAddress]
        actions:
            - '@assign_value': [$.workflowItem.data.email, $.visitor_email]
            - '@call_method':
                object: $.workflowItem
                method: setUpdated
            - '@flush_entity': $.workflowItem
            - '@assign_value': [$.data.saveBillingAddress, $.save_address]
            - '@flush_entity': [$.address]
            - '@flush_entity': [$.data]
            - '@run_action_group':
                action_group: update_checkout_state
                parameters_mapping:
                    checkout: $.data
                    state_token: $.workflowItem.data.state_token
                    update_checkout_state: true

    b2b_flow_checkout_new_shipping_address:
        extends: b2b_flow_checkout_new_address
        attributes:
            address:
                property_path: data.shippingAddress
            save_address:
                label: oro.checkout.save_shipping_address.label
                type: boolean
        form_options:
            attribute_fields:
                address:
                    form_type: Oro\Bundle\CheckoutBundle\Form\Type\CheckoutAddressType
                    options:
                        object: $.data
                        addressType: 'shipping'
                        required: true
                        constraints:
                            - Valid: ~
                            - NotBlank: ~
                            - Oro\Bundle\AddressBundle\Validator\Constraints\NameOrOrganization: ~
                save_address:
                    form_type: Oro\Bundle\CheckoutBundle\Form\Type\SaveAddressType
        form_init:
            - '@assign_value': [$.address, $.data.shippingAddress]
            - '@tree':
                conditions:
                    '@and':
                        - '@acl_granted': 'CREATE;entity:Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress'
                        - '@acl_granted': 'CREATE;entity:Oro\Bundle\CustomerBundle\Entity\CustomerAddress'
                actions:
                    - '@assign_value': [$.save_address, $.data.saveShippingAddress]
        actions:
            - '@call_service_method':
                service: oro_workflow.manager
                method: getFirstWorkflowItemByEntity
                method_parameters: [$.data]
                attribute: $.workflowItem
            - '@call_method':
                object: $.workflowItem
                method: setUpdated
            - '@flush_entity': $.workflowItem
            - '@assign_value': [$.data.saveShippingAddress, $.save_address]
            - '@flush_entity': [$.address]
            - '@flush_entity': [$.data]
            - '@run_action_group':
                action_group: update_checkout_state
                parameters_mapping:
                    checkout: $.data
                    state_token: $.workflowItem.data.state_token
                    update_checkout_state: true

action_groups:
    b2b_flow_checkout_duplicate_address:
        service: oro_checkout.action_group.b2b_flow_checkout.address_actions
        method: duplicateOrderAddress
        return_value_name: 'newAddress'

    b2b_flow_checkout_update_billing_address:
        service: oro_checkout.action_group.b2b_flow_checkout.address_actions
        method: updateBillingAddress
        return_value_name: 'billing_address_has_shipping'

    b2b_flow_checkout_update_shipping_address:
        service: oro_checkout.action_group.b2b_flow_checkout.address_actions
        method: updateShippingAddress

    b2b_flow_checkout_update_shipping_method:
        service: oro_checkout.action_group.update_shipping_price

    b2b_flow_checkout_place_order:
        service: oro_checkout.action_group.b2b_flow_checkout.order_actions
        method: placeOrder
        return_value_name: 'order'

    b2b_flow_checkout_create_child_orders:
        service: oro_checkout.action_group.b2b_flow_checkout.split_order_actions
        method: createChildOrders

    b2b_flow_checkout_purchase:
        service: oro_checkout.action_group.b2b_flow_checkout.checkout_actions
        method: purchase

    b2b_flow_checkout_finish_checkout:
        service: oro_checkout.action_group.b2b_flow_checkout.checkout_actions
        method: finishCheckout

    b2b_flow_checkout_send_order_confirmation_email:
        service: oro_checkout.action_group.b2b_flow_checkout.order_actions
        method: sendConfirmationEmail

    b2b_flow_checkout_create_guest_customer_user:
        service: oro_checkout.action_group.b2b_flow_checkout.customer_user_actions
        method: createGuestCustomerUser

    b2b_flow_checkout_update_guest_customer_user:
        service: oro_checkout.action_group.b2b_flow_checkout.customer_user_actions
        method: updateGuestCustomerUser

    handle_late_registration:
        service: oro_checkout.action_group.b2b_flow_checkout.customer_user_actions
        method: handleLateRegistration

    b2b_flow_checkout_has_applicable_shipping_rules:
        service: oro_checkout.action_group.b2b_flow_checkout.shipping_method_actions
        method: hasApplicableShippingRules
        return_value_name: 'hasRules'

    b2b_flow_checkout_update_default_shipping_methods:
        service: oro_checkout.action_group.b2b_flow_checkout.shipping_method_actions
        method: updateDefaultShippingMethods

    b2b_flow_checkout_actualize_shipping_methods:
        service: oro_checkout.action_group.b2b_flow_checkout.shipping_method_actions
        method: actualizeShippingMethods

    b2b_flow_checkout_update_checkout_shipping_prices:
        service: oro_checkout.action_group.b2b_flow_checkout.shipping_method_actions
        method: updateCheckoutShippingPrices
