action_groups:
    b2b_flow_checkout_duplicate_address:
        service: oro_checkout.action_group.b2b_flow_checkout.address_actions
        method: duplicateOrderAddress
        return_value_name: 'newAddress'

    b2b_flow_checkout_update_billing_address:
        service: oro_checkout.action_group.b2b_flow_checkout.address_actions
        method: updateBillingAddress
        return_value_name: 'billing_address_has_shipping'

    b2b_flow_checkout_update_shipping_address:
        service: oro_checkout.action_group.b2b_flow_checkout.address_actions
        method: updateShippingAddress

    b2b_flow_checkout_update_shipping_method:
        service: oro_checkout.action_group.update_shipping_price

    b2b_flow_checkout_place_order:
        service: oro_checkout.action_group.b2b_flow_checkout.order_actions
        method: placeOrder
        return_value_name: 'order'

    b2b_flow_checkout_create_child_orders:
        service: oro_checkout.action_group.b2b_flow_checkout.split_order_actions
        method: createChildOrders

    b2b_flow_checkout_purchase:
        service: oro_checkout.action_group.b2b_flow_checkout.checkout_actions
        method: purchase

    b2b_flow_checkout_finish_checkout:
        service: oro_checkout.action_group.b2b_flow_checkout.checkout_actions
        method: finishCheckout

    b2b_flow_checkout_send_order_confirmation_email:
        service: oro_checkout.action_group.b2b_flow_checkout.order_actions
        method: sendConfirmationEmail

    b2b_flow_checkout_create_guest_customer_user:
        service: oro_checkout.action_group.b2b_flow_checkout.customer_user_actions
        method: createGuestCustomerUser

    b2b_flow_checkout_update_guest_customer_user:
        service: oro_checkout.action_group.b2b_flow_checkout.customer_user_actions
        method: updateGuestCustomerUser

    handle_late_registration:
        service: oro_checkout.action_group.b2b_flow_checkout.customer_user_actions
        method: handleLateRegistration

    b2b_flow_checkout_has_applicable_shipping_rules:
        service: oro_checkout.action_group.b2b_flow_checkout.shipping_method_actions
        method: hasApplicableShippingRules
        return_value_name: 'hasRules'

    b2b_flow_checkout_update_default_shipping_methods:
        service: oro_checkout.action_group.b2b_flow_checkout.shipping_method_actions
        method: updateDefaultShippingMethods

    b2b_flow_checkout_actualize_shipping_methods:
        service: oro_checkout.action_group.b2b_flow_checkout.shipping_method_actions
        method: actualizeShippingMethods

    b2b_flow_checkout_update_checkout_shipping_prices:
        service: oro_checkout.action_group.b2b_flow_checkout.shipping_method_actions
        method: updateCheckoutShippingPrices
