action_groups:
    # TODO: Find a way how to work with result/results of action group when dealing with a services
    # TODO: ??? Do we need context in service, or let's keep it not connected to action bundle at all to be able to reuse??
    b2b_flow_checkout_duplicate_address:
        service: oro_checkout.action_group.b2b_flow_checkout.address_actions
        method: duplicateOrderAddress

    b2b_flow_checkout_update_billing_address:
        service: oro_checkout.action_group.b2b_flow_checkout.address_actions
        method: updateBillingAddress

    b2b_flow_checkout_update_shipping_address:
        service: oro_checkout.action_group.b2b_flow_checkout.address_actions
        method: updateShippingAddress

    # TODO: May be removed as it is a proxy for proxy...
    b2b_flow_checkout_update_shipping_method:
        parameters:
            checkout:
                type: Oro\Bundle\CheckoutBundle\Entity\Checkout
        actions:
            - '@run_action_group':
                action_group: oro_update_shipping_price
                parameters_mapping:
                    checkout: $.checkout

    b2b_flow_checkout_place_order:
        service: oro_checkout.action_group.b2b_flow_checkout.order_actions
        method: placeOrder

    b2b_flow_checkout_create_child_orders:
        service: oro_checkout.action_group.b2b_flow_checkout.split_order_actions
        method: createChildOrders

    b2b_flow_checkout_purchase:
        service: oro_checkout.action_group.b2b_flow_checkout.checkout_actions
        method: purchase

    b2b_flow_checkout_finish_checkout:
        service: oro_checkout.action_group.b2b_flow_checkout.checkout_actions
        method: finishCheckout

    b2b_flow_checkout_send_order_confirmation_email:
        service: oro_checkout.action_group.b2b_flow_checkout.order_actions
        method: sendConfirmationEmail

    b2b_flow_checkout_create_guest_customer_user:
        service: oro_checkout.action_group.b2b_flow_checkout.customer_user_actions
        method: createGuestCustomerUser

    b2b_flow_checkout_update_guest_customer_user:
        service: oro_checkout.action_group.b2b_flow_checkout.customer_user_actions
        method: updateGuestCustomerUser

    handle_late_registration:
        service: oro_checkout.action_group.b2b_flow_checkout.customer_user_actions
        method: handleLateRegistration
