services:
    _defaults:
        public: true

    Oro\Bundle\FrontendLocalizationBundle\Controller\Frontend\AjaxLocalizationController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_locale.helper.localized_slug_redirect, key: Oro\Bundle\FrontendLocalizationBundle\Helper\LocalizedSlugRedirectHelper }
