styles:
    inputs:
        - 'bundles/orocheckout/default/scss/settings/global-settings.scss'
        - 'bundles/orocheckout/default/scss/variables/checkout-config.scss'
        - 'bundles/orocheckout/default/scss/variables/multistep-checkout-layout-config.scss'
        - 'bundles/orocheckout/default/scss/variables/multistep-checkout-config.scss'
        - 'bundles/orocheckout/default/scss/variables/checkout-form-config.scss'
        - 'bundles/orocheckout/default/scss/variables/checkout-order-summary-config.scss'
        - 'bundles/orocheckout/default/scss/variables/checkout-order-summary-container-config.scss'
        - 'bundles/orocheckout/default/scss/variables/customer-shopping-list-config.scss'
        - 'bundles/orocheckout/default/scss/variables/summary-collapse-config.scss'
        - 'bundles/orocheckout/default/scss/variables/summary-widget-config.scss'
        - 'bundles/orocheckout/default/scss/variables/summary-table-config.scss'
        - 'bundles/orocheckout/default/scss/variables/order-checkout-widget-config.scss'
        - 'bundles/orocheckout/default/scss/variables/checkout-navigation-config.scss'
        - 'bundles/orocheckout/default/scss/variables/single-page-checkout-view-config.scss'
        - 'bundles/orocheckout/default/scss/variables/checkout-credentials-config.scss'
        - 'bundles/orocheckout/default/scss/variables/order-loading-placeholder-config.scss'

        - 'bundles/orocheckout/default/scss/components/checkout-summary-widget.scss'
        - 'bundles/orocheckout/default/scss/components/checkout-summary-inner-layout.scss'
        - 'bundles/orocheckout/default/scss/components/customer-shopping-list.scss'
        - 'bundles/orocheckout/default/scss/components/multistep-checkout-layout.scss'
        - 'bundles/orocheckout/default/scss/components/multistep-checkout.scss'
        - 'bundles/orocheckout/default/scss/components/summary-collapse.scss'
        - 'bundles/orocheckout/default/scss/components/summary-widget.scss'
        - 'bundles/orocheckout/default/scss/components/summary-table.scss'
        - 'bundles/orocheckout/default/scss/components/order-checkout-widget.scss'
        - 'bundles/orocheckout/default/scss/components/order-loading-placeholder.scss'
        - 'bundles/orocheckout/default/scss/styles.scss'

print_styles:
    inputs:
        - 'bundles/orocheckout/default/scss/components/order-checkout-widget-print.scss'
