dynamic-imports:
    orocheckout:
        - orocheckout/js/app/components/payment-additional-data-component
        - orocheckout/js/app/components/payment-save-for-later-component
        - orocheckout/js/app/components/payment-transition-button-component
        - orocheckout/js/app/components/payment-validate-component
        - orocheckout/js/app/components/shipping-transition-button-component
        - orocheckout/js/app/components/multi-shipping-transition-button-component
        - orocheckout/js/app/components/multi-shipping-per-group-transition-button-component
        - orocheckout/js/app/components/single-page-checkout-component
        - orocheckout/js/app/components/transition-button-component
        - orocheckout/js/app/views/address-view
        - orocheckout/js/app/views/checkout-content-view
        - orocheckout/js/app/views/checkout-inner-content-view
        - orocheckout/js/app/views/late-checkout-registration-view
        - orocheckout/js/app/views/checkout-address-validation-dialog-widget
        - orocheckout/js/app/views/checkout-multi-step-address-validated-at-view
        - orocheckout/js/app/views/checkout-multi-step-address-validation-view
        - orocheckout/js/app/views/checkout-multi-step-address-validation-view
        - orocheckout/js/app/views/checkout-base-new-address-validated-at-view
        - orocheckout/js/app/views/checkout-multi-step-new-address-validated-at-view
        - orocheckout/js/app/views/checkout-single-page-address-validation-view
        - orocheckout/js/app/views/checkout-single-page-new-address-validated-at-view
        - orocheckout/js/app/views/add-address-button-view
        - orocheckout/js/app/views/checkout-overlay-popup-view
        - orocheckout/js/datagrid/builder/grouped-line-items-subtotal-builder
        - tpl-loader!orocheckout/templates/datagrid/cell/inventory_status.html
        - tpl-loader!orocheckout/templates/datagrid/cell/item-message.html
        - tpl-loader!orocheckout/templates/datagrid/cell/item.html
        - tpl-loader!orocheckout/templates/datagrid/cell/price.html
        - tpl-loader!orocheckout/templates/datagrid/cell/quantity.html
        - tpl-loader!orocheckout/templates/datagrid/cell/subtotal.html
        - tpl-loader!orocheckout/templates/datagrid/cell/sku.html
        - tpl-loader!orocheckout/templates/datagrid/cell/sku-message.html
        - tpl-loader!orocheckout/templates/datagrid/cell/unit.html
