datagrids:
    inventory-level-grid:
        acl_resource: oro_product_inventory_update
        source:
            type: orm
            query:
                select:
                    - precision.id as combinedId
                    - IDENTITY(precision.unit) as unitCode
                    - IDENTITY(precision.unit) as productUnit
                    - level.quantity as levelQuantity
                from:
                    - { table: 'Oro\Bundle\ProductBundle\Entity\ProductUnitPrecision', alias: precision }
                join:
                    left:
                        -   join: 'Oro\Bundle\InventoryBundle\Entity\InventoryLevel'
                            alias: level
                            conditionType: WITH
                            condition: "level.productUnitPrecision = precision.id"
                where:
                    and:
                        - IDENTITY(precision.product) = :productId
            bind_parameters:
                - productId
        columns:
            levelQuantity:
                label: oro.inventory.inventorylevel.quantity.label
                frontend_type: string # can't use decimal because of inappropriate formatter
                editable: true
                cellClassName: 'editing-cell'
            productUnit:
                label: oro.product.productunit.entity_label
                type: twig
                frontend_type: html
                template: '@OroProduct/ProductUnit/Datagrid/unitFullPlural.html.twig'
        sorters:
            columns:
                levelQuantity:
                    data_name: levelQuantity
                productUnit:
                    data_name: productUnit
            default:
                productUnit: ASC
        properties:
            combinedId: ~
            unitCode: ~
        options:
            mode: client
            toolbarOptions:
                hide: true
                pagination:
                    onePage: true
            cellSelection:
                dataField: combinedId
                columnName:
                    - levelQuantity
                selector: '#inventory-level-quantities'
            jsmodules:
                - oroinventory/js/datagrid/builder/level-quantity-builder

    inventory-grid:
        extended_entity_name: 'Oro\Bundle\InventoryBundle\Entity\InventoryLevel'
        acl_resource: oro_product_inventory_view
        source:
            type: orm
            query:
                select:
                    - inventory.id
                    - product.id as productId
                    - product.sku as sku
                    - product.skuUppercase as productSkuUppercase
                    - JSON_EXTRACT(product.serialized_data, 'inventory_status') as inventory_status
                    - inventory.quantity as quantity
                    - precisionUnit.code as unit
                    - productPrecision.precision as inventoryLevelPrecision
                    - IDENTITY(productPrecision.unit) as unitCode
                    - product.denormalizedDefaultName as productName
                    - product.denormalizedDefaultNameUppercase as productNameUppercase
                from:
                    - { table: 'Oro\Bundle\InventoryBundle\Entity\InventoryLevel', alias: inventory }
                join:
                    left:
                        - { join: inventory.product, alias: product }
                        - { join: inventory.productUnitPrecision, alias: productPrecision }
                        - { join: productPrecision.unit, alias: precisionUnit }
            hints:
                - HINT_TRANSLATABLE
        properties:
            id: ~
            productId: ~
            inventoryLevelPrecision: ~
        inline_editing:
            enable: true
        save_api_accessor:
            default_route_parameters:
                className: Oro_Bundle_InventoryBundle_Entity_InventoryLevel
        columns:
            sku:
                label: oro.product.sku.label
            productName:
                label: oro.product.names.label
            inventory_status:
                label: oro.product.inventory_status.label
                frontend_type: select
                choices: "@oro_entity_extend.enum_options_provider->getEnumChoicesByCode('prod_inventory_status')"
                translatable_options: false
                data_name: inventory_status
                inline_editing:
                    enable: true
                    editor:
                        view_options:
                            value_field_name: inventory_status
                    save_api_accessor:
                        route: oro_api_patch_product_inline_edit_inventory_status
                        route_parameters_rename_map:
                            productId: id
            quantity:
                label: oro.inventory.inventorylevel.quantity.label
                frontend_type: decimal
                align: right
                inline_editing:
                    enable: true
                    editor:
                        view: oroinventory/js/app/views/quantity-editor-view
                        view_options:
                            decimalsField: inventoryLevelPrecision
                    validation_rules:
                        DecimalsNumber:
                            decimalsField: inventoryLevelPrecision
                    validation_groups: [ Default ]
            unit:
                label: oro.product.productunitprecision.unit.label
                type: twig
                frontend_type: html
                template: '@OroProduct/ProductUnit/Datagrid/unitFullPlural.html.twig'
        sorters:
            columns:
                sku:
                    data_name: sku
                productName:
                    data_name: productName
                inventory_status:
                    data_name: inventory_status
                quantity:
                    data_name: quantity
                unit:
                    data_name: unit
        filters:
            columns:
                sku:
                    type: string
                    data_name: productSkuUppercase
                    case_insensitive: false
                    value_conversion: mb_strtoupper
                productName:
                    type: string
                    data_name: productNameUppercase
                    case_insensitive: false
                    value_conversion: mb_strtoupper
                inventory_status:
                    type: enum
                    data_name: inventory_status
                    enum_code: prod_inventory_status
                quantity:
                    data_name: quantity
                    type: number
                unit:
                    type: choice
                    data_name: unit
                    options:
                        field_options:
                            choices: "@oro_product.provider.product_units_provider->getAvailableProductUnits"
                            translatable_options: false
                            multiple: true
        options:
            jsmodules:
                - oroinventory/js/datagrid/builder/inventory-status-builder
