app-modules:
    - orocustomer/js/app/modules/validator-constraints-module
    - oroform/default/js/app/modules/validator-constraints-module
    - orofrontend/default/js/app/modules/input-widgets
    - orofrontend/js/app/modules/component-shortcuts-module
    - oronavigation/js/app/modules/navigation-module
    - oroui/js/app/modules/component-shortcuts-module
    - oroui/js/app/modules/focus-visible
    - oroui/js/app/modules/ignore-tabbable
    - oroui/js/app/modules/init-layout
    - oroui/js/app/modules/layout-module
    - oroui/js/app/modules/messenger-module
    - oroui/js/app/modules/swipeable-module
    - oroui/js/app/modules/viewport-module
    - orouser/js/app/modules/validator-constraints-module
    - orovalidation/default/js/app/modules/validator-constraints-module
dynamic-imports:
    commons:
        - controllers/page-controller
        - orocommercemenu/js/app/views/header-row-view
        - orofrontend/default/js/app/views/proxy-focus-view
        - orofrontend/default/js/app/views/scroll-top-view
        - orofrontend/default/js/app/views/frontend-messages-view
        - orofrontend/js/app/views/dom-relocation-view
        - oronavigation/js/app/views/navigation-menu-view
        - oroproduct/js/app/views/search-autocomplete-view
        - oroshoppinglist/js/app/components/shoppinglist-collection-component
        - oroshoppinglist/js/app/components/shoppinglist-widget-view-component
        - oroshoppinglist/js/app/views/shoppinglist-widget-view
        - orotranslation/js/translator
        - oroui/js/app/components/app-loading-bar-component
        - oroui/js/app/components/app-loading-mask-component
        - oroui/js/app/components/jquery-widget-component
        - oroui/js/app/components/view-component
        - oroui/js/app/components/viewport-component
        - oroui/js/app/components/widget-component
        - oroui/js/app/views/layout-subtree-view
        - oroui/js/app/views/page/content-view
        - oroui/js/mediator
        - orowindows/js/dialog/state/model
        - routing
    extra:
        - oro/product-shopping-lists-widget
        - oro/select2-component
        - orocommercemenu/js/app/views/menu-traveling-view
        - orocustomer/js/validator/unique-customer-user-name-and-email
        - oroform/js/app/views/form-validate-view
        - oroform/js/validator/callback
        - oroform/js/validator/count
        - oroform/js/validator/date
        - oroform/js/validator/datetime
        - oroform/js/validator/email
        - oroform/js/validator/length
        - oroform/js/validator/not-blank-group
        - oroform/js/validator/notblank
        - oroform/js/validator/notnull
        - oroform/js/validator/number
        - oroform/js/validator/numeric-range
        - oroform/js/validator/open-range
        - oroform/js/validator/range
        - oroform/js/validator/regex
        - oroform/js/validator/repeated
        - oroform/js/validator/time
        - oroform/js/validator/type
        - orofrontend/default/js/app/views/fullscreen-popup-view
        - orofrontend/js/app/components/delete-item-component
        - orofrontend/js/app/components/list-slider-component
        - orofrontend/js/app/components/popup-gallery-widget
        - oropricing/js/app/views/base-product-matrix-view
        - oropricing/js/app/views/list-item-product-prices-view
        - oropricing/js/app/views/product-total-price-view
        - oroproduct/js/app/components/product-unit-select-component
        - oroproduct/js/app/views/base-product-view
        - oroproduct/js/app/views/product-quantity-editable-view
        - oroproduct/js/content-processor/product-add-to-dropdown-button
        - oroshoppinglist/js/app/components/shopping-list-create-component
        - oroshoppinglist/js/app/components/shoppinglist-create-order-button-component
        - oroshoppinglist/js/app/views/matrix-grid-add-to-shopping-list-view
        - oroshoppinglist/js/app/views/matrix-grid-popup-button-view
        - oroshoppinglist/js/app/views/product-add-to-shopping-list-view
        - oroshoppinglist/js/app/views/product-quick-add-to-shopping-list-view
        - oroshoppinglist/js/app/views/product-shopping-lists-view
        - oroshoppinglist/js/app/views/shopping-list-quick-search
        - oroshoppinglist/js/shopping-list-item-errors-handler
        - orouser/js/validator/password-complexity
        - orovalidation/js/validator/alphanumeric
        - orovalidation/js/validator/alphanumeric-dash
        - orovalidation/js/validator/alphanumeric-dash-underscore
        - orovalidation/js/validator/decimal
        - orovalidation/js/validator/email
        - orovalidation/js/validator/greater-than-zero
        - orovalidation/js/validator/integer
        - orovalidation/js/validator/letters
        - orovalidation/js/validator/url-safe
entry:
    app:
        - oroui/js/app
        - oroui/js/app/services/app-ready-load-modules
