#Consider this workflow is reused in standart and single page checkout workflows
workflows:
    b2b_flow_checkout:
        transition_definitions:
            __start___definition: ~

            unblock_and_recalculate_definition:
                actions:
                    - '@assign_value':
                        - [$payment_method, null]
                        - [$payment_in_progress, false]

            payment_error_definition:
                actions:
                    - '@assign_value':
                          - [$payment_method, null]
                          - [$payment_in_progress, false]
                    - '@remove_entity':
                        conditions:
                            '@not_empty': $order
                        parameters: [$order]
                    - '@unset_value': [$.data.order]
