layout:
    actions:
        - '@setOption':
            id: category_title
            optionName: text
            optionValue: '=data["web_catalog_title"].getTitle(data["locale"].getLocalizedValue(data["category"].getCurrentCategory().getTitles()))'
