services:
    oro_ups.cache.address_validation:
        parent: oro.data.cache
        tags:
            - { name: 'cache.pool', namespace: 'oro_ups_address_validation' }

    oro_ups.address_validation.client.address_validation_request_factory:
        class: Oro\Bundle\UPSBundle\AddressValidation\Client\Request\Factory\UPSAddressValidationRequestFactory

    oro_ups.address_validation.client.address_validation_response_factory:
        class: Oro\Bundle\UPSBundle\AddressValidation\Client\Response\Factory\UPSAddressValidationResponseFactory

    oro_ups.address_validation.address_validation_client:
        class: Oro\Bundle\UPSBundle\AddressValidation\Client\UPSAddressValidationClient
        arguments:
            - '@oro_ups.token_provider'
            - '@oro_ups.client.factory_basic'
            - '@oro_ups.address_validation.client.address_validation_response_factory'
            - '@logger'

    oro_ups.address_validation.client.cache.ups_response:
        class: Oro\Bundle\UPSBundle\AddressValidation\Cache\UPSAddressValidationResponseCache
        arguments:
            - '@oro_ups.cache.address_validation'

    oro_ups.address_validation.address_validation_cached_client:
        class: Oro\Bundle\AddressValidationBundle\Client\AddressValidationCachedClient
        arguments:
            - '@oro_ups.address_validation.address_validation_client'
            - '@oro_ups.address_validation.client.cache.ups_response'

    oro_ups.address_validation.resolved_address_factory:
        class: Oro\Bundle\UPSBundle\AddressValidation\UPSResolvedAddressFactory
        arguments:
            - '@doctrine'

    oro_ups.address_validation.resolver.factory:
        class: Oro\Bundle\AddressValidationBundle\Resolver\Factory\AddressValidationResolverBasicFactory
        arguments:
            - '@oro_ups.address_validation.client.address_validation_request_factory'
            - '@oro_ups.address_validation.address_validation_cached_client'
            - '@oro_ups.address_validation.resolved_address_factory'
            - 'Oro\Bundle\UPSBundle\Entity\UPSTransport'
        tags:
            - { name: oro_address_validation.resolver_factory }
