Oro\Bundle\UPSBundle\Entity\UPSTransport:
    constraints:
        - Oro\Bundle\UPSBundle\Validator\Constraints\CountryShippingServicesConstraint: ~
        - Oro\Bundle\UPSBundle\Validator\Constraints\RemoveUsedShippingServiceConstraint: ~
    properties:
        upsClientId:
            - NotBlank: ~
            - Length:
                  max: 255
        upsClientSecret:
            - NotBlank: ~
        upsShippingAccountName:
            - NotBlank: ~
        upsShippingAccountNumber:
            - NotBlank: ~
        upsPickupType:
            - NotBlank: ~
        upsUnitOfWeight:
            - NotBlank: ~
        upsCountry:
            - NotBlank: ~
            - Valid: ~
        applicableShippingServices:
            - NotBlank:
                message: 'oro.ups.settings.shipping_service.blank.message'
        labels:
            - NotBlank: ~
            - Valid: ~
