services:
    oro_product.product_kit.event_listener.product_status_listener:
        class: Oro\Bundle\ProductBundle\ProductKit\EventListener\ProductStatusListener
        arguments:
            - '@doctrine'
            - '@oro_product.product_kit.resolver.product_kit_status_resolver'
            - '@oro_product.product_kit.resolver.product_kit_inventory_status_resolver'

    Oro\Bundle\ProductBundle\ProductKit\EventListener\StatusListener: '@oro_product.product_kit.event_listener.status_listener'
    oro_product.product_kit.event_listener.status_listener:
        class: Oro\Bundle\ProductBundle\ProductKit\EventListener\StatusListener
        arguments:
            - '@oro_product.product_kit.resolver.product_kit_status_resolver'
            - '@oro_product.product_kit.resolver.product_kit_inventory_status_resolver'
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: onClear }

    Oro\Bundle\ProductBundle\ProductKit\Resolver\ProductKitStatusResolver: '@oro_product.product_kit.resolver.product_kit_status_resolver'
    oro_product.product_kit.resolver.product_kit_status_resolver:
        class: Oro\Bundle\ProductBundle\ProductKit\Resolver\ProductKitStatusResolver
        arguments:
            - '@doctrine'

    Oro\Bundle\ProductBundle\ProductKit\Resolver\ProductKitInventoryStatusResolver: '@oro_product.product_kit.resolver.product_kit_inventory_status_resolver'
    oro_product.product_kit.resolver.product_kit_inventory_status_resolver:
        class: Oro\Bundle\ProductBundle\ProductKit\Resolver\ProductKitInventoryStatusResolver
        arguments:
            - '@doctrine'

    oro_product.event_listener.website_search_reindex_product_kit:
        class: Oro\Bundle\ProductBundle\ProductKit\EventListener\WebsiteSearchReindexProductKitListener
        arguments:
            - '@oro_website.indexation_entities_container'
            - '@event_dispatcher'
            - '@doctrine'
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: onClear }
            - { name: kernel.event_listener, event: oro_website_search.reindexation_request, method: onReindexationRequest }

    oro_product.event_listener.search_product_kit:
        class: Oro\Bundle\ProductBundle\ProductKit\EventListener\SearchProductKitListener
        arguments:
            - '@oro_search.mapper'
            - '@oro_search.async.indexer'
            - '@doctrine'
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: onClear }
            - { name: kernel.event_listener, event: oro_search.before_index_entities, method: beforeIndexEntities }
            - { name: kernel.event_listener, event: oro_search.prepare_entity_map, method: prepareEntityMapEvent }

    oro_product.acl.product_voter:
        class: Oro\Bundle\ProductBundle\Acl\Voter\ProductVoter
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_product.provider.product_kits_by_product'
        calls:
            - [ setClassName, [ 'Oro\Bundle\ProductBundle\Entity\Product' ] ]
        tags:
            - { name: security.voter }
