services:
    oro_product.product_kit.event_listener.product_status_listener:
        class: Oro\Bundle\ProductBundle\ProductKit\EventListener\ProductStatusListener
        arguments:
            - '@doctrine'
            - '@oro_product.product_kit.resolver.product_kit_status_resolver'
            - '@oro_product.product_kit.resolver.product_kit_inventory_status_resolver'

    Oro\Bundle\ProductBundle\ProductKit\EventListener\StatusListener: '@oro_product.product_kit.event_listener.status_listener'
    oro_product.product_kit.event_listener.status_listener:
        class: Oro\Bundle\ProductBundle\ProductKit\EventListener\StatusListener
        arguments:
            - '@oro_product.product_kit.resolver.product_kit_status_resolver'
            - '@oro_product.product_kit.resolver.product_kit_inventory_status_resolver'
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: onClear }

    Oro\Bundle\ProductBundle\ProductKit\Resolver\ProductKitStatusResolver: '@oro_product.product_kit.resolver.product_kit_status_resolver'
    oro_product.product_kit.resolver.product_kit_status_resolver:
        class: Oro\Bundle\ProductBundle\ProductKit\Resolver\ProductKitStatusResolver
        arguments:
            - '@doctrine'

    Oro\Bundle\ProductBundle\ProductKit\Resolver\ProductKitInventoryStatusResolver: '@oro_product.product_kit.resolver.product_kit_inventory_status_resolver'
    oro_product.product_kit.resolver.product_kit_inventory_status_resolver:
        class: Oro\Bundle\ProductBundle\ProductKit\Resolver\ProductKitInventoryStatusResolver
        arguments:
            - '@doctrine'
