services:
    oro_product.related_item.helper.config_helper:
        class: Oro\Bundle\ProductBundle\RelatedItem\Helper\RelatedItemConfigHelper
        calls:
            - [addConfigProvider, ['related_products', '@oro_product.related_item.related_product.config_provider']]
            - [addConfigProvider, ['upsell_products', '@oro_product.related_item.upsell_product.config_provider']]

    Oro\Bundle\ProductBundle\RelatedItem\Helper\RelatedItemConfigHelper:
        alias: oro_product.related_item.helper.config_helper

    # RELATED PRODUCTS
    oro_product.related_item.related_product.config_provider:
        class: Oro\Bundle\ProductBundle\RelatedItem\RelatedProduct\RelatedProductsConfigProvider
        arguments:
            - '@oro_config.manager'

    Oro\Bundle\ProductBundle\RelatedItem\RelatedProduct\RelatedProductsConfigProvider:
        alias: oro_product.related_item.related_product.config_provider

    oro_product.related_item.related_product.assigner_database_strategy_abstract:
      abstract: true
      public: false
      class: Oro\Bundle\ProductBundle\RelatedItem\RelatedProduct\AssignerDatabaseStrategy
      arguments: ['@oro_entity.doctrine_helper', '@oro_product.related_item.related_product.config_provider']

    oro_product.related_item.related_product.assigner_strategy:
      parent: oro_product.related_item.related_product.assigner_database_strategy_abstract

    oro_product.related_item.related_product.assigner_database_strategy:
      parent: oro_product.related_item.related_product.assigner_database_strategy_abstract

    oro_product.related_item.related_product.finder_strategy:
        class: Oro\Bundle\ProductBundle\RelatedItem\RelatedProduct\FinderDatabaseStrategy
        arguments:
            - '@doctrine'
            - '@oro_product.related_item.related_product.config_provider'

    oro_product.related_item.related_product.data_provider:
        class: Oro\Bundle\ProductBundle\Layout\DataProvider\RelatedItemDataProvider
        arguments:
            - '@oro_product.related_item.related_product.finder_strategy'
            - '@oro_product.related_item.related_product.config_provider'
            - '@oro_ui.user_agent_provider'
            - '@doctrine'
            - '@oro_product.product.manager'
            - '@oro_security.acl_helper'
            - '@oro_product.product_list_builder'
        tags:
            - { name: layout.data_provider, alias: oro_product_related_products }

    # UPSELL PRODUCTS
    oro_product.related_item.upsell_product.config_provider:
        class: Oro\Bundle\ProductBundle\RelatedItem\UpsellProduct\UpsellProductConfigProvider
        arguments:
            - '@oro_config.manager'

    Oro\Bundle\ProductBundle\RelatedItem\UpsellProduct\UpsellProductConfigProvider:
        alias: oro_product.related_item.upsell_product.config_provider

    oro_product.related_item.upsell_product.assigner_strategy:
        public: false
        class: Oro\Bundle\ProductBundle\RelatedItem\UpsellProduct\AssignerDatabaseStrategy
        arguments: ['@oro_entity.doctrine_helper', '@oro_product.related_item.upsell_product.config_provider']

    oro_product.related_item.upsell_product.finder_strategy:
        class: Oro\Bundle\ProductBundle\RelatedItem\UpsellProduct\FinderDatabaseStrategy
        arguments:
            - '@doctrine'
            - '@oro_product.related_item.upsell_product.config_provider'

    oro_product.related_item.upsell_product.data_provider:
        class: Oro\Bundle\ProductBundle\Layout\DataProvider\RelatedItemDataProvider
        arguments:
            - '@oro_product.related_item.upsell_product.finder_strategy'
            - '@oro_product.related_item.upsell_product.config_provider'
            - '@oro_ui.user_agent_provider'
            - '@doctrine'
            - '@oro_product.product.manager'
            - '@oro_security.acl_helper'
            - '@oro_product.product_list_builder'
        tags:
            - { name: layout.data_provider, alias: oro_product_upsell_products }
