system_configuration:
    groups:
        catalog_search:
            title: oro.webcatalog.system_configuration.groups.catalog_search.title
            icon: fa-search
        website_search_special_pages:
            title: oro.webcatalog.system_configuration.groups.website_search_terms.special_pages.title
            priority: -10
    fields:
        oro_web_catalog.web_catalog:
            ui_only: true
            data_type: integer
            type: Oro\Bundle\WebCatalogBundle\Form\Type\WebCatalogSelectType
            priority: 110
            options:
                label: oro.webcatalog.system_configuration.fields.web_catalog.label
                tooltip: oro.webcatalog.system_configuration.fields.web_catalog.tooltip
                required: false
                create_enabled: false
            page_reload: true
        oro_web_catalog.navigation_root:
            data_type: integer
            type: Oro\Bundle\WebCatalogBundle\Form\Type\ContentNodeSelectSystemConfigType
            priority: 100
            options:
                label: oro.webcatalog.system_configuration.fields.navigation_root.label
                tooltip: oro.webcatalog.system_configuration.fields.navigation_root.tooltip
                required: false
                data_transformer: oro_web_catalog.form.data_transformer.navigation_root_option
        oro_web_catalog.enable_web_catalog_canonical_url:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 50
            options:
                label: oro.webcatalog.system_configuration.fields.enable_web_catalog_canonical_url.label
                tooltip: oro.webcatalog.system_configuration.fields.enable_web_catalog_canonical_url.tooltip
        oro_web_catalog.empty_search_result_page:
            data_type: array
            type: Oro\Bundle\WebCatalogBundle\Form\Type\EmptySearchResultPageSelectSystemConfigType
            options:
                label: oro.webcatalog.system_configuration.fields.empty_search_result_page.label
                tooltip: oro.webcatalog.system_configuration.fields.empty_search_result_page.tooltip
                attr:
                    'data-page-component-module': 'oroui/js/app/components/view-component'
                    'data-page-component-options': '{"view": "orowebcatalog/js/app/views/content-node-from-webcatalog-view","listenedFieldName":"website_search_terms[oro_web_catalog___empty_search_result_page][value][webCatalog]","triggeredFieldName":"website_search_terms[oro_web_catalog___empty_search_result_page][value][contentNode]"}'

    tree:
        system_configuration:
            platform:
                children:
                    websites:
                        children:
                            routing:
                                children:
                                    websites_routing_general:
                                        children:
                                            - oro_web_catalog.web_catalog
                                            - oro_web_catalog.navigation_root
                                    oro_redirect_canonical_urls:
                                        children:
                                            - oro_web_catalog.enable_web_catalog_canonical_url
            commerce:
                children:
                    search:
                        children:
                            website_search_terms:
                                children:
                                    website_search_special_pages:
                                        children:
                                            - oro_web_catalog.empty_search_result_page
