Oro\Bundle\ProductBundle\Entity\Product:
    properties:
        type:
            -   EqualTo:
                    value: kit
                    message: 'oro.shoppinglist.product_kit_is_available_for_purchase.product.type.kit.message'
                    groups:
                        # Used by oro_shopping_list.product_kit.checker.product_kit_availability_checker
                        - product_kit_is_available_for_purchase
        status:
            -   EqualTo:
                    value: enabled
                    message: 'oro.shoppinglist.product_kit_is_available_for_purchase.product.status.enabled.message'
                    groups:
                        # Used by oro_shopping_list.product_kit.checker.product_kit_availability_checker
                        - product_kit_is_available_for_purchase
        kitItems:
            -   Oro\Bundle\ShoppingListBundle\Validator\Constraints\ProductKitItemCollectionIsAvailableForPurchase:
                    groups:
                        # Used by oro_shopping_list.product_kit.checker.product_kit_availability_checker
                        - product_kit_is_available_for_purchase

Oro\Bundle\ProductBundle\Entity\ProductKitItem:
    properties:
        kitItemProducts:
            -   Oro\Bundle\ShoppingListBundle\Validator\Constraints\ProductKitItemProductCollectionIsAvailableForPurchase:
                    groups:
                        # Used by oro_shopping_list.product_kit.checker.product_kit_item_availability_checker
                        - product_kit_item_is_available_for_purchase

Oro\Bundle\ProductBundle\Entity\ProductKitItemProduct:
    constraints:
        -   Oro\Bundle\ShoppingListBundle\Validator\Constraints\ProductKitItemProductHasPrice:
                groups:
                    # Used by oro_shopping_list.product_kit.checker.product_kit_item_product_availability_checker
                    - product_kit_item_product_is_available_for_purchase
    properties:
        product:
            -   Expression:
                    expression: 'value && value.isEnabled()'
                    groups:
                        # Used by oro_shopping_list.product_kit.checker.product_kit_item_product_availability_checker
                        - product_kit_item_product_is_available_for_purchase
            -   Expression:
                    expression: 'value && value.isSimple()'
                    groups:
                        # Used by oro_shopping_list.product_kit.checker.product_kit_item_product_availability_checker
                        - product_kit_item_product_is_available_for_purchase

Oro\Bundle\ShoppingListBundle\Model\MatrixCollectionColumn:
    constraints:
        -   Oro\Bundle\ShoppingListBundle\Validator\Constraints\MatrixCollectionColumn: ~
    properties:
        quantity:
            -   Oro\Bundle\ValidationBundle\Validator\Constraints\Decimal: ~
            -   Oro\Bundle\ValidationBundle\Validator\Constraints\GreaterThanZero: ~

Oro\Bundle\ShoppingListBundle\Entity\ShoppingList:
    properties:
        label:
            -   NotBlank: ~
            -   Length:
                    max: 255
        totals:
            -   Valid: ~
        notes:
            -   Length:
                    max: 2048
        lineItems:
            -   Valid: ~

Oro\Bundle\ShoppingListBundle\Entity\ShoppingListTotal:
    properties:
        subtotalValue:
            -   Type:
                    type: numeric
                    groups:
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - create
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - update
                        # Used by \Oro\Bundle\ProductBundle\Form\Type\FrontendLineItemType
                        - add_product
                        # Used by \Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController
                        - add_product_kit_line_item
            -   Oro\Bundle\ValidationBundle\Validator\Constraints\NumericRange:
                    notInRangeMessage: 'oro.shoppinglist.subtotal.range.not_in_range_message'
                    groups:
                        - Default
                        # Used by \Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController
                        - add_product_kit_line_item

Oro\Bundle\ShoppingListBundle\Entity\LineItem:
    constraints:
        -   Oro\Bundle\ShoppingListBundle\Validator\Constraints\LineItem:
                groups:
                    # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                    - update
        -   Oro\Bundle\ProductBundle\Validator\Constraints\QuantityUnitPrecision:
                path: quantity
                groups:
                    # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                    - create
                    # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                    - update
                    # Used by \Oro\Bundle\ProductBundle\Form\Type\FrontendLineItemType
                    - add_product
                    # Used by \Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController
                    - add_product_kit_line_item
        -   Oro\Bundle\InventoryBundle\Validator\Constraints\QuantityToOrder:
                groups:
                    # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                    - create
                    # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                    - update
                    # Used by \Oro\Bundle\ShoppingListBundle\EventListener\DatagridLineItemsDataValidationListener
                    - datagrid_line_items_data
        -   Oro\Bundle\ProductBundle\Validator\Constraints\ProductKitLineItemContainsRequiredKitItems:
                groups:
                    # Used by \Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController
                    - add_product_kit_line_item
                    # Used by \Oro\Bundle\ShoppingListBundle\EventListener\DatagridLineItemsDataValidationListener
                    - datagrid_line_items_data
    properties:
        product:
            -   NotBlank:
                    groups:
                        - Default
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - create
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - update
                        # Used by \Oro\Bundle\ProductBundle\Form\Type\FrontendLineItemType
                        - add_product
            -   Expression:
                    expression: 'value && value.isEnabled()'
                    groups:
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - create
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - update
                        # Used by \Oro\Bundle\ProductBundle\Form\Type\FrontendLineItemType
                        - add_product
                        # Used by \Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController
                        - add_product_kit_line_item
                        # Used by \Oro\Bundle\ShoppingListBundle\EventListener\DatagridLineItemsDataValidationListener
                        - datagrid_line_items_data
        quantity:
            -   NotBlank:
                    groups:
                        - Default
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - create
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - update
                        # Used by \Oro\Bundle\ProductBundle\Form\Type\FrontendLineItemType
                        - add_product
            -   Oro\Bundle\ValidationBundle\Validator\Constraints\Decimal:
                    groups:
                        - Default
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - create
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - update
                        # Used by \Oro\Bundle\ProductBundle\Form\Type\FrontendLineItemType
                        - add_product
            -   Expression:
                    expression: "this.getProduct() && (this.getProduct().isConfigurable() || value > 0)"
                    message: 'oro.shoppinglist.lineitem.quantity.greater_than_zero'
                    groups:
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - create
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - update
                        # Used by \Oro\Bundle\ProductBundle\Form\Type\FrontendLineItemType
                        - add_product
                        # Used by \Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController
                        - add_product_kit_line_item
                        # Used by \Oro\Bundle\ShoppingListBundle\EventListener\DatagridLineItemsDataValidationListener
                        - datagrid_line_items_data
                    payload:
                        jsValidation:
                            type: Range
                            options:
                                min: 0
                                max: 100000000
        unit:
            -   NotBlank:
                    groups:
                        - Default
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - create
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - update
                        # Used by \Oro\Bundle\ProductBundle\Form\Type\FrontendLineItemType
                        - add_product
        shoppingList:
            -   NotBlank:
                    groups:
                        - Default
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - create
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - update
        notes:
            -   Length:
                    max: 2048
                    groups:
                        - Default
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - create
                        # Used by \Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType
                        - update
                        # Used by \Oro\Bundle\ProductBundle\Form\Type\FrontendLineItemType
                        - add_product
        kitItemLineItems:
            -   Valid:
                    groups:
                        - Default
                        # Used by \Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController
                        - add_product_kit_line_item
        checksum:
            -   NotNull: ~
            -   Length:
                    max: 40

Oro\Bundle\ShoppingListBundle\Entity\ProductKitItemLineItem:
    properties:
        lineItem:
            -   NotNull: ~
        kitItem:
            -   NotNull: ~
        product:
            -   NotNull: ~
            -   AtLeastOneOf:
                    constraints:
                        -   Oro\Bundle\ProductBundle\Validator\Constraints\ProductKitItemLineItemProductAvailable:
                                availabilityValidationGroups: [ product_kit_item_product_is_available_for_purchase ]
                        -   Expression:
                                expression: 'this.getKitItem() && this.getKitItem().isOptional()'
                    message: 'oro.shoppinglist.product_kit_item_line_item.product.status_required.message'
                    includeInternalMessages: false
                    groups:
                        # Used by \Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController
                        - add_product_kit_line_item
                        # Used by \Oro\Bundle\ShoppingListBundle\EventListener\DatagridLineItemsDataValidationListener
                        - datagrid_line_items_data
            -   AtLeastOneOf:
                    constraints:
                        -   Oro\Bundle\ProductBundle\Validator\Constraints\ProductKitItemLineItemProductAvailable:
                                availabilityValidationGroups: [ product_kit_item_product_is_available_for_purchase ]
                        -   Expression:
                                expression: 'this.getKitItem() && !this.getKitItem().isOptional()'
                    message: 'oro.shoppinglist.product_kit_item_line_item.product.status_optional.message'
                    includeInternalMessages: false
                    groups:
                        # Used by \Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController
                        - add_product_kit_line_item
                        # Used by \Oro\Bundle\ShoppingListBundle\EventListener\DatagridLineItemsDataValidationListener
                        - datagrid_line_items_data
        quantity:
            -   NotBlank:
                    message: 'oro.shoppinglist.product_kit_item_line_item.quantity.not_blank.message'
                    payload:
                        jsValidation:
                            type: NotBlank
                            options:
                                allowNull: true
            -   Type:
                    type: float
            -   Oro\Bundle\ValidationBundle\Validator\Constraints\GreaterThanZero:
                    message: 'oro.shoppinglist.product_kit_item_line_item.quantity.greater_than_zero.message'
                    groups:
                        # Used by \Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController
                        - add_product_kit_line_item
                        # Used by \Oro\Bundle\ShoppingListBundle\EventListener\DatagridLineItemsDataValidationListener
                        - datagrid_line_items_data
            -   Range:
                    minPropertyPath: 'kitItem.minimumQuantity'
                    maxPropertyPath: 'kitItem.maximumQuantity'
                    notInRangeMessage: 'oro.shoppinglist.product_kit_item_line_item.quantity.range.not_in_range_message'
                    groups:
                        # Used by \Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController
                        - add_product_kit_line_item
                        # Used by \Oro\Bundle\ShoppingListBundle\EventListener\DatagridLineItemsDataValidationListener
                        - datagrid_line_items_data
            -   Oro\Bundle\ProductBundle\Validator\Constraints\ProductKitItemLineItemQuantityUnitPrecision:
                    groups:
                        # Used by \Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController
                        - add_product_kit_line_item
                        # Used by \Oro\Bundle\ShoppingListBundle\EventListener\DatagridLineItemsDataValidationListener
                        - datagrid_line_items_data
        unit:
            -   NotNull: ~
            -   Oro\Bundle\ProductBundle\Validator\Constraints\ProductKitItemLineItemProductUnitAvailable:
                    groups:
                        # Used by \Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController
                        - add_product_kit_line_item
                        # Used by \Oro\Bundle\ShoppingListBundle\EventListener\DatagridLineItemsDataValidationListener
                        - datagrid_line_items_data
        sortOrder:
            -   NotNull: ~
            -   Type:
                    type: integer
            -   Range:
                    # Minimum of 4-byte integer value.
                    min: -2147483648
                    # Maximum of 4-byte integer value.
                    max: 2147483647
