system_configuration:
    groups:
        website_search_suggestion:
            title: oro.websitesearchsuggestion.system_configuration.groups.website_search_suggestion.title
            description: oro.websitesearchsuggestion.system_configuration.groups.website_search_suggestion.description
            description_style: warning
    fields:
        oro_website_search_suggestion.website_search_suggestion_feature_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 100
            page_reload: true
            options:
                label: oro.websitesearchsuggestion.feature.website_search_suggestion.label

        oro_website_search_suggestion.search_autocomplete_max_suggests:
            data_type: integer
            type: Symfony\Component\Form\Extension\Core\Type\IntegerType
            search_type: text
            priority: 15
            options:
                label: oro.websitesearchsuggestion.system_configuration.fields.search_autocomplete_max_suggests.label
                tooltip: oro.websitesearchsuggestion.system_configuration.fields.search_autocomplete_max_suggests.tooltip
                required: true
                constraints:
                    -   NotBlank: ~
                    -   Oro\Bundle\ValidationBundle\Validator\Constraints\NumericRange:
                            min: 0
                            max: 100

    tree:
        system_configuration:
            commerce:
                children:
                    product:
                        children:
                            product_search:
                                children:
                                    website_search_suggestion:
                                        children:
                                            - oro_website_search_suggestion.website_search_suggestion_feature_enabled
                                            - oro_website_search_suggestion.search_autocomplete_max_suggests

