Oro\Bundle\WebsiteSearchSuggestionBundle\Entity\Suggestion:
    alias: oro_website_search_suggestion_WEBSITE_ID
    fields:
        -
            name: localization_id
            type: integer
        -
            name: words_count
            type: integer
        -
            name: phrase
            type: text
