api:
    entity_aliases:
        Oro\Bundle\CatalogBundle\Api\Model\CategoryNode:
            alias:        mastercatalogtree
            plural_alias: mastercatalogtree
        Oro\Bundle\CatalogBundle\Entity\Category:
            alias:        mastercatalogcategory
            plural_alias: mastercatalogcategories

    entities:
        Oro\Bundle\CatalogBundle\Api\Model\CategoryNode:
            documentation_resource: '@OroCatalogBundle/Resources/doc/api_frontend/category_node.md'
            disable_meta_properties: true
            identifier_field_names: [id]
            fields:
                id:
                    data_type: integer
                order:
                    data_type: integer
                    property_path: category.left
                parent:
                    target_class: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode
                    target_type: to-one
                    property_path: _
                    depends_on: [ category.materializedPath ]
                path:
                    target_class: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode
                    target_type: to-many
                    property_path: _
                    depends_on: [ category.materializedPath ]
                # declare excluded "materializedPath" field as it is required to compute the value of
                # "parent" and "path" fields
                materializedPath:
                    data_type: string
                    property_path: category.materializedPath
                    exclude: true
                category:
                    target_class: Oro\Bundle\CatalogBundle\Entity\Category
                    target_type: to-one
                    property_path: _
            filters:
                fields:
                    id:
                        data_type: integer
                        allow_array: true
                    parent:
                        data_type: integer
                        allow_array: true
                        operators: [ '=', '!=', '*', '!*' ]
                        property_path: parentCategory
                    root:
                        data_type: integer
                        type: nestedTree
                    category:
                        data_type: integer
                        operators: [ '=', '!=' ]
                        property_path: id
            actions:
                get:
                    description: Get Master Catalog Tree Node
                get_list:
                    description: Get Master Catalog Tree Nodes
                    disable_paging: true
                    disable_sorting: true
                create: false
                update: false
                delete: false
                delete_list: false
            subresources:
                path:
                    filters:
                        # disable all filters
                        exclusion_policy: all
                    actions:
                        get_relationship:
                            disable_paging: true
                            disable_sorting: true
                        get_subresource:
                            disable_paging: true
                            disable_sorting: true

        Oro\Bundle\CatalogBundle\Entity\Category:
            documentation_resource: '@OroCatalogBundle/Resources/doc/api_frontend/category.md'
            fields:
                denormalizedDefaultTitle:
                    exclude: true
                materializedPath:
                    exclude: true
                root:
                    exclude: true
                level:
                    exclude: true
                left:
                    exclude: true
                right:
                    exclude: true
                products:
                    exclude: true
                parentCategory:
                    exclude: true
                childCategories:
                    exclude: true
                title:
                    data_type: localizedFallbackValue:titles
                shortDescription:
                    data_type: localizedFallbackValue:shortDescriptions
                description:
                    data_type: localizedFallbackValue:longDescriptions
                url:
                    data_type: string
                    property_path: _
                urls:
                    data_type: objects
                    property_path: _
                images:
                    data_type: objects
                    property_path: _
                    depends_on:
                        - smallImage.id
                        - smallImage.mimeType
                        - smallImage.filename
                        - largeImage.id
                        - largeImage.mimeType
                        - largeImage.filename
                # declare excluded field for "smallImage" entity property
                # to be able to use "smallImage" property in "depends_on" option
                _smallImage:
                    property_path: smallImage
                    exclude: true
                # declare excluded field for "largeImage" entity property
                # to be able to use "largeImage" property in "depends_on" option
                _largeImage:
                    property_path: largeImage
                    exclude: true
                categoryPath:
                    target_class: Oro\Bundle\CatalogBundle\Entity\Category
                    target_type: to-many
                    property_path: _
                    depends_on: [ materializedPath ]
                # declare excluded field for "materializedPath" entity property
                # to be able to use "materializedPath" property in "depends_on" option
                _materializedPath:
                    property_path: materializedPath
                    exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
            subresources:
                categoryPath:
                    filters:
                        # disable all filters
                        exclusion_policy: all
                    actions:
                        get_relationship:
                            disable_paging: true
                            disable_sorting: true
                        get_subresource:
                            disable_paging: true
                            disable_sorting: true

        Oro\Bundle\ProductBundle\Entity\Product:
            documentation_resource: '@OroCatalogBundle/Resources/doc/api_frontend/product.md'
            fields:
                category: ~
                category_sort_order: ~
            filters:
                fields:
                    rootCategory:
                        data_type: integer
                        type: nestedTree
                        options:
                            field: category

        Oro\Bundle\ProductBundle\Api\Model\ProductSearch:
            documentation_resource: '@OroCatalogBundle/Resources/doc/api_frontend/product_search.md'
            fields:
                category:
                    data_type: integer
                    property_path: integer.category_id
                    target_class: Oro\Bundle\CatalogBundle\Entity\Category
                    target_type: to-one
                category_sort_order:
                    data_type: float
                    property_path: float.category_sort_order
