api:
    entity_aliases:
        Oro\Bundle\ProductBundle\Api\Model\ProductLatestPurchase:
            alias: latestpurchase
            plural_alias: latestpurchases

    entities:
        Oro\Bundle\ProductBundle\Entity\ProductUnitPrecision:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_unit_precision.md'
            disable_meta_properties: [ title ]

        Oro\Bundle\ProductBundle\Entity\ProductUnit:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_unit.md'
            fields:
                label:
                    data_type: string
                    property_path: _
                shortLabel:
                    data_type: string
                    property_path: _
                pluralLabel:
                    data_type: string
                    property_path: _
                shortPluralLabel:
                    data_type: string
                    property_path: _

        Oro\Bundle\ProductBundle\Entity\ProductImage:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_image.md'
            disable_meta_properties: [ title ]

        Oro\Bundle\ProductBundle\Entity\ProductImageType:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_image_type.md'
            disable_meta_properties: [ title ]

        Oro\Bundle\ProductBundle\Entity\ProductName:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_name.md'
            actions:
                delete_list: false
                delete: false

        Oro\Bundle\ProductBundle\Entity\ProductShortDescription:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_short_description.md'
            actions:
                delete_list: false
                delete: false

        Oro\Bundle\ProductBundle\Entity\ProductDescription:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_description.md'
            actions:
                delete_list: false
                delete: false

        Oro\Bundle\ProductBundle\Entity\Product:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product.md'
            form_options:
                constraints:
                    - Oro\Bundle\ProductBundle\Validator\Constraints\NotEmptyConfigurableAttributes: ~
                    - Oro\Bundle\ProductBundle\Validator\Constraints\ProductVariantField: ~
                    - Oro\Bundle\ProductBundle\Validator\Constraints\ProductVariantLinks: ~
                    - Oro\Bundle\ProductBundle\Validator\Constraints\UniqueProductVariantLinks: ~
                    - Oro\Bundle\ProductBundle\Validator\Constraints\UniqueVariantLinksSimpleProduct: ~
                    - Oro\Bundle\ProductBundle\Validator\Constraints\EmptyVariantFieldInSimpleProductForVariantLinks: ~
                    - Oro\Bundle\ProductBundle\Validator\Constraints\ProductKitShippingCalculationMethod:
                          allowedShippingCalculationMethods: [ kit_shipping_all, kit_shipping_product, kit_shipping_items ]
            fields:
                skuUppercase:
                    exclude: true
                parentVariantLinks:
                    exclude: true
                denormalizedDefaultName:
                    exclude: true
                denormalizedDefaultNameUppercase:
                    exclude: true
            filters:
                fields:
                    sku:
                        allow_array: true
            actions:
                create:
                    fields:
                        names:
                            form_options:
                                constraints:
                                    - Count:
                                        min: 1
                update_list: true

        Extend\Entity\EV_Prod_Inventory_Status:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product.md'

        Oro\Bundle\ProductBundle\Entity\RelatedItem\RelatedProduct:
            documentation_resource: '@OroProductBundle/Resources/doc/api/related_product.md'
            disable_meta_properties: [ title ]
            actions:
                get:
                    description: Get Related Product Relationship
                delete:
                    description: Delete Related Product Relationship
                get_list:
                    description: Get Related Product Relationships
                delete_list:
                    description: Delete Related Product Relationships
                create:
                    description: Create Related Product Relationships
                    fields:
                        product:
                            form_options:
                                constraints:
                                    - NotBlank: ~
                        relatedItem:
                            form_options:
                                constraints:
                                    - NotBlank: ~
                update: false

        Oro\Bundle\ProductBundle\Entity\Brand:
            documentation_resource: '@OroProductBundle/Resources/doc/api/brand.md'
            fields:
                defaultTitle:
                    exclude: true

        Oro\Bundle\ProductBundle\Entity\ProductVariantLink:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_variant_links.md'
            disable_meta_properties: [ title ]

        Oro\Bundle\AttachmentBundle\Entity\File:
            documentation_resource: '@OroProductBundle/Resources/doc/api/file.md'
            fields:
                filePath:
                    data_type: object
                    depends_on: [filename,mimeType,originalFilename,extension,parentEntityClass]
                    form_options:
                        mapped: false

        Oro\Bundle\ProductBundle\Entity\ProductKitItem:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_kit_item.md'
            subresources:
                labels:
                    actions:
                        add_relationship: false
                        update_relationship: false
                        delete_relationship: false
                productKit:
                    actions:
                        update_relationship: false
                        delete_relationship: false

        Oro\Bundle\ProductBundle\Entity\ProductKitItemProduct:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_kit_item_product.md'
            disable_meta_properties: [ title ]
            actions:
                create:
                    status_codes:
                        200: false
                        201: false
                        400: false
                        403: Returned always
                        409: false
                        500: false
                update:
                    fields:
                        kitItem:
                            form_options:
                                mapped: false
                delete_list: false
                delete: false
            fields:
                productUnitPrecision:
                    form_options:
                        mapped: false
            subresources:
                kitItem:
                    actions:
                        update_relationship: false
                        delete_relationship: false
                productUnitPrecision:
                    actions:
                        update_relationship: false
                        delete_relationship: false

        Oro\Bundle\ProductBundle\Entity\ProductKitItemLabel:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_kit_item_label.md'
            actions:
                create:
                    status_codes:
                        200: false
                        201: false
                        400: false
                        403: Returned always
                        409: false
                        500: false
                delete_list: false
                delete: false
            subresources:
                kitItem:
                    actions:
                        update_relationship: false
                        delete_relationship: false
                localization:
                    actions:
                        update_relationship: false
                        delete_relationship: false

        Oro\Bundle\ProductBundle\Api\Model\ProductLatestPurchase:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_latest_purchase.md'
            disable_meta_properties: true
            identifier_field_names: [id]
            fields:
                id:
                    data_type: string
                price:
                    data_type: money
                currency:
                    data_type: string
                purchasedAt:
                    data_type: datetime
                product:
                    property_path: productId
                    target_class: Oro\Bundle\ProductBundle\Entity\Product
                    target_type: to-one
                unit:
                    target_class: Oro\Bundle\ProductBundle\Entity\ProductUnit
                    target_type: to-one
                customerUser:
                    property_path: customerUserId
                    target_class: Oro\Bundle\CustomerBundle\Entity\CustomerUser
                    target_type: to-one
                customer:
                    property_path: customerId
                    target_class: Oro\Bundle\CustomerBundle\Entity\Customer
                    target_type: to-one
                website:
                    property_path: websiteId
                    target_class: Oro\Bundle\WebsiteBundle\Entity\Website
                    target_type: to-one
            filters:
                fields:
                    unit:
                        data_type: string
                        operators: ['=']
                        allow_array: true
                    currency:
                        data_type: string
                        operators: ['=']
                        allow_array: true
                    product:
                        data_type: integer
                        operators: ['=']
                        allow_array: true
                    customer:
                        data_type: integer
                        operators: ['=']
                        allow_array: true
                    hierarchicalCustomer:
                        data_type: integer
                        operators: ['=']
                        allow_array: true
                        description: Filter records by 'customer' relationship (customer hierarchy aware).
                        type: customerHierarchyAware
                    customerUser:
                        data_type: integer
                        operators: ['=']
                        allow_array: true
                    website:
                        data_type: integer
                        operators: ['=']
                        allow_array: true
            actions:
                get_list:
                    disable_paging: true
                    disable_sorting: true
                get: false
                create: false
                update: false
                delete: false
                delete_list: false
                get_subresource: false
