oro_api:
    config_files:
        frontend_sku:
            file_name: [api_frontend_sku.yml, api_frontend.yml]
            request_type: ['frontend_sku', 'frontend']
    api_doc_views:
        frontend_sku_rest_json_api:
            label: 'JSON:API (SKU)'
            underlying_view: frontend_rest_json_api
            headers:
                X-Product-ID: sku
            request_type: ['rest', 'json_api', 'frontend_sku', 'frontend']
    error_title_overrides:
        'product kit item line item quantity range constraint': 'range constraint'

oro_frontend:
    frontend_api:
        api_doc_views: [frontend_sku_rest_json_api]

knp_gaufrette:
    filesystems:
        import_product_images:
            adapter: import_files
            alias: import_product_images_filesystem

oro_entity:
    entity_name_representation:
        Oro\Bundle\ProductBundle\Entity\Product:
            short: [ sku ]

oro_customer:
    frontend_api:
        non_authenticated_visitors_api_resources:
            - Oro\Bundle\ProductBundle\Api\Model\ProductCollection
            - Oro\Bundle\ProductBundle\Api\Model\ProductSearch
            - Oro\Bundle\ProductBundle\Entity\Product
            - Oro\Bundle\ProductBundle\Entity\ProductImage
            - Oro\Bundle\ProductBundle\Entity\ProductKitItem
            - Oro\Bundle\ProductBundle\Entity\ProductKitItemProduct
            - Oro\Bundle\ProductBundle\Entity\ProductUnit
            - Extend\Entity\EV_Prod_Inventory_Status
            - Oro\Bundle\EntityConfigBundle\Attribute\Entity\AttributeFamily
