aliases:
    oro/datagrid/action/sort-products-action$: oroproduct/js/datagrid/action/sort-products-action
    oro/datagrid/action/trigger-event-for-selected-product-ids-mass-action$: oroproduct/js/datagrid/action/trigger-event-for-selected-product-ids-mass-action
    oro/product-collection-popup-add-products-widget$: oroproduct/js/app/widget/product-collection-popup-add-products-widget
    oro/related-items-widget$: oroproduct/js/app/widget/related-items-widget
    oroproduct/js/app/datagrid/listener/related-product-listener$: oroproduct/js/app/datagrid/listener/related-items-listener
    oroproduct/datagrid/builder/product-kit-items-builder$: oroproduct/js/datagrid/builder/product-kit-items-builder
app-modules:
    - oroproduct/js/app/modules/validator-constraints-module
configs:
    oroproduct/js/validator/sku-regex: {}
dynamic-imports:
    commons:
        - oroproduct/js/validator/sku-regex
    orodatagrid:
        - oro/datagrid/action/sort-products-action
        - oro/datagrid/action/trigger-event-for-selected-product-ids-mass-action
        - oroproduct/js/datagrid/builder/sort-order-builder
        - oroproduct/js/datagrid/builder/sort-products-action-builder
        - oroproduct/js/datagrid/builder/sort-products-collection-action-builder
        - oroproduct/js/app/components/product-name-popup-editor-component
        - oroproduct/js/app/datagrid/listener/related-product-listener
        - oroproduct/js/sort-rows-drag-n-drop/exclude-from-collection
    orosale:
        - oro/product-collection-popup-add-products-widget
        - oro/related-items-widget
        - oroproduct/js/app/components/config-single-unit-component
        - oroproduct/js/app/components/product-collection-apply-query-component
        - oroproduct/js/app/components/product-image-type-radio-control-component
        - oroproduct/js/app/components/product-primary-unit-limitations-component
        - oroproduct/js/app/components/product-unit-component
        - oroproduct/js/app/components/product-unit-selection-limitations-component
        - oroproduct/js/app/components/product-variant-component
        - oroproduct/js/app/components/product-variant-field-component
        - oroproduct/js/app/components/related-items-tabs-component
        - oroproduct/js/app/views/variant-fields-view
    productskit:
        - oroproduct/js/app/components/product-kit-items-component
        - oroproduct/js/app/views/product-kit/product-kit-view
        - oroproduct/js/app/views/product-kit/product-kit-widget-view
        - oroproduct/js/app/views/product-kit/product-kit-sorting-view
        - oroproduct/datagrid/builder/product-kit-items-builder
    orowebsitesearch:
        - oroproduct/js/app/views/search-term-run-original-search-form-view
        - oroproduct/js/app/views/search-term-run-original-search-view
