search:
    Oro\Bundle\ProductBundle\Entity\Product:
        alias:                          oro_product
        route:
            name:                       oro_product_view
            parameters:
                id:                     id
        search_template:                '@OroProduct/Product/searchResult.html.twig'
        fields:
            -
                name:                   sku
                target_type:            text
                target_fields:          [sku]
            -
                name:                   defaultName
                target_type:            text
                target_fields:          [defaultName]
            -
                name: names
                relation_type: many-to-many
                relation_fields:
                    -
                        name: string
                        target_type: text
                        target_fields: [names]
            -
                name:                   defaultDescription
                target_type:            text
                target_fields:          [defaultDescription]
            -
                name:                   defaultShortDescription
                target_type:            text
                target_fields:          [defaultShortDescription]
            -
                name: descriptions
                relation_type: many-to-many
                relation_fields:
                    -
                        name: text
                        target_type: text
                        target_fields: [descriptions]
            -
                name: shortDescriptions
                relation_type: many-to-many
                relation_fields:
                    -
                        name: text
                        target_type: text
                        target_fields: [shortDescriptions]

    Oro\Bundle\ProductBundle\Entity\Brand:
        alias:                          oro_brand
        route:
            name:                       oro_product_brand_index
        search_template:                '@OroProduct/Brand/searchResult.html.twig'
        acl_permission:                 'VIEW'
        fields:
            -
                name: names
                relation_type: many-to-many
                relation_fields:
                    -
                        name: string
                        target_type: text
                        target_fields: [names]
            -
                name:                   defaultDescription
                target_type:            text
                target_fields:          [defaultDescription]
            -
                name:                   defaultShortDescription
                target_type:            text
                target_fields:          [defaultShortDescription]
            -
                name: descriptions
                relation_type: many-to-many
                relation_fields:
                    -
                        name: text
                        target_type: text
                        target_fields: [descriptions]
            -
                name: shortDescriptions
                relation_type: many-to-many
                relation_fields:
                    -
                        name: text
                        target_type: text
                        target_fields: [shortDescriptions]
