imports:
    - { resource: 'b2b_flow_checkout_with_services/attributes.yml' }
    - { resource: 'b2b_flow_checkout_with_services/steps.yml' }
    - { resource: 'b2b_flow_checkout_with_services/transitions.yml' }

workflows:
    b2b_flow_checkout:
        entity: Oro\Bundle\CheckoutBundle\Entity\Checkout
        entity_attribute: checkout
        steps_display_ordered: true

        defaults:
            active: true

        metadata:
            is_checkout_workflow: true
            is_single_page_checkout: false
            guest_checkout:
                return_to_login_transition: 'back_to_enter_credentials'
            checkout_state_config:
                enable_state_protection: true
                additionally_update_state_after: ['paid_partially']

        applications: ['commerce']

        exclusive_active_groups:
            - b2b_checkout_flow
        exclusive_record_groups:
            - b2b_checkout_flow

        priority: 200
