services:
    oro_checkout.address_validation.checkout_handler.billing_address:
        class: Oro\Bundle\CheckoutBundle\AddressValidation\CheckoutHandler\BillingAddressValidationCheckoutHandler
        arguments:
            - '@doctrine'
            - '@oro_checkout.helper.checkout_workflow_helper'
            - '@oro_checkout.action_group.update_checkout_state'

    oro_checkout.address_validation.checkout_handler.shipping_address:
        class: Oro\Bundle\CheckoutBundle\AddressValidation\CheckoutHandler\ShippingAddressValidationCheckoutHandler
        arguments:
            - '@doctrine'
            - '@oro_checkout.helper.checkout_workflow_helper'
            - '@oro_checkout.action_group.update_checkout_state'

    oro_checkout.address_validation.result_handler:
        class: Oro\Bundle\CheckoutBundle\AddressValidation\ResultHandler\CheckoutAddressValidationResultHandler
        arguments:
            - '@doctrine'
            - '@security.authorization_checker'
            - '@oro_customer.utils.address_copier'

    oro_checkout.form.factory.address_validation.address_form.billing_address:
        class: Oro\Bundle\CheckoutBundle\Form\Factory\AddressValidation\CheckoutAddressFormFactory
        arguments:
            - '@oro_checkout.helper.checkout_workflow_helper'
            - '@oro_checkout.layout.data_provider.transition'
            - '@form.factory'
            - 'billing_address'

    oro_checkout.form.factory.address_validation.address_form.shipping_address:
        class: Oro\Bundle\CheckoutBundle\Form\Factory\AddressValidation\CheckoutAddressFormFactory
        arguments:
            - '@oro_checkout.helper.checkout_workflow_helper'
            - '@oro_checkout.layout.data_provider.transition'
            - '@form.factory'
            - 'shipping_address'

    oro_checkout.provider.address_validation.multi_step_address_form_billing_address:
        class: Oro\Bundle\CheckoutBundle\Provider\AddressValidation\CheckoutAddressFormAddressProvider

    oro_checkout.provider.address_validation.multi_step_address_form_shipping_address:
        class: Oro\Bundle\CheckoutBundle\Provider\AddressValidation\CheckoutAddressFormShippingAddressProvider

    oro_checkout.provider.address_validation.single_page_address_form_billing_address:
        class: Oro\Bundle\CheckoutBundle\Provider\AddressValidation\CheckoutAddressFormAddressProvider

    oro_checkout.provider.address_validation.single_page_address_form_shipping_address:
        class: Oro\Bundle\CheckoutBundle\Provider\AddressValidation\CheckoutAddressFormShippingAddressProvider

    oro_checkout.form.factory.address_validation.single_page_address_form.new_billing_address:
        class: Oro\Bundle\CheckoutBundle\Form\Factory\AddressValidation\CheckoutNewAddressFormFactory
        arguments:
            - '@form.factory'
            - '@oro_action.operation_registry'
            - '@oro_action.helper.context'
            - 'b2b_flow_checkout_single_page_new_billing_address'

    oro_checkout.form.factory.address_validation.single_page_address_form.new_shipping_address:
        class: Oro\Bundle\CheckoutBundle\Form\Factory\AddressValidation\CheckoutNewAddressFormFactory
        arguments:
            - '@form.factory'
            - '@oro_action.operation_registry'
            - '@oro_action.helper.context'
            - 'b2b_flow_checkout_single_page_new_shipping_address'

    oro_checkout.form.factory.address_validation.multi_step_address_form.new_billing_address:
        class: Oro\Bundle\CheckoutBundle\Form\Factory\AddressValidation\CheckoutNewAddressFormFactory
        arguments:
            - '@form.factory'
            - '@oro_action.operation_registry'
            - '@oro_action.helper.context'
            - 'b2b_flow_checkout_single_page_new_billing_address'

    oro_checkout.form.factory.address_validation.multi_step_address_form.new_shipping_address:
        class: Oro\Bundle\CheckoutBundle\Form\Factory\AddressValidation\CheckoutNewAddressFormFactory
        arguments:
            - '@form.factory'
            - '@oro_action.operation_registry'
            - '@oro_action.helper.context'
            - 'b2b_flow_checkout_single_page_new_shipping_address'
