services:
    _defaults:
        public: true

    Oro\Bundle\CheckoutBundle\Controller\Frontend\CheckoutController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\CheckoutBundle\Controller\Frontend\AjaxCheckoutController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_checkout.manager.multi_shipping.checkout_line_items_shipping, key: Oro\Bundle\CheckoutBundle\Manager\MultiShipping\CheckoutLineItemsShippingManager }
            - { name: container.service_subscriber, id: oro_checkout.manager.multi_shipping.checkout_line_item_groups_shipping, key: Oro\Bundle\CheckoutBundle\Manager\MultiShipping\CheckoutLineItemGroupsShippingManager }

    Oro\Bundle\CheckoutBundle\Controller\Frontend\OpenOrdersController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
