services:
    oro_checkout.action_group.b2b_flow_checkout.address_actions:
        class: Oro\Bundle\CheckoutBundle\Action\B2bFlowCheckout\ActionGroup\AddressActions
        public: true
        arguments:
            - '@doctrine'
            - '@oro_action.factory.duplicator_factory'
        tags:
            - { name: 'oro_action_group_service' }

    oro_checkout.action_group.b2b_flow_checkout.order_actions:
        class: Oro\Bundle\CheckoutBundle\Action\B2bFlowCheckout\ActionGroup\OrderActions
        public: true
        arguments:
            - '@doctrine'
            - '@oro_checkout.action_group.b2b_flow_checkout.address_actions'
            - '@oro_payment_term.provider.payment_term'
            - '@oro_checkout.data_provider.manager.checkout_line_items'
            - '@oro_checkout.mapper.order_mapper'
            - '@oro_checkout.payment_methods_provider'
            - '@oro_order.order.total.total_helper'
            - '@oro_action.action_executor'
        tags:
            - { name: 'oro_action_group_service' }

    oro_checkout.action_group.b2b_flow_checkout.split_order_actions:
        class: Oro\Bundle\CheckoutBundle\Action\B2bFlowCheckout\ActionGroup\SplitOrderActions
        public: true
        arguments:
            - '@oro_checkout.action_group.b2b_flow_checkout.order_actions'
            - '@oro_order.order.total.total_helper'
            - '@oro_checkout.splitter.checkout_splitter'
            - '@oro_checkout.provider.grouped_line_items'
            - '@oro_checkout.provider.multi_shipping.sub_order_owner'
            - '@oro_checkout.provider.multi_shipping.sub_order_organization'
            - '@oro_checkout.shipping_method.provider_main'
            - '@oro_promotion.applied_promotion_manager'
        tags:
            - { name: 'oro_action_group_service' }

    oro_checkout.action_group.b2b_flow_checkout.checkout_actions:
        class: Oro\Bundle\CheckoutBundle\Action\B2bFlowCheckout\ActionGroup\CheckoutActions
        public: true
        arguments:
            - '@oro_security.token_accessor'
            - '@security.authorization_checker'
            - '@doctrine'
            - '@oro_entity.entity_alias_resolver'
            - '@oro_entity.entity_name_resolver'
            - '@router'
            - '@oro_action.action_executor'
        tags:
            - { name: 'oro_action_group_service' }

    oro_checkout.action_group.b2b_flow_checkout.customer_user_actions:
        class: Oro\Bundle\CheckoutBundle\Action\B2bFlowCheckout\ActionGroup\CustomerUserActions
        public: true
        arguments:
            - '@doctrine'
            - '@security.token_storage'
            - '@oro_customer.manager.guest_customer_user'
            - '@oro_customer_user.manager'
            - '@oro_shopping_list.manager.guest_shopping_list_migration'
            - '@oro_customer.security.login_manager'
            - '@oro_action.action_executor'
        tags:
            - { name: 'oro_action_group_service' }
