services:
    oro_checkout.event_listener.workflow.checkout_state_listener:
        class: Oro\Bundle\CheckoutBundle\WorkflowState\EventListener\Workflow\CheckoutStateListener
        arguments:
            - '@oro_action.action_executor'
            - '@oro_checkout.workflow_state.manager.checkout_state_diff'
            - '@oro_checkout.action_group.update_checkout_state'
            - '@oro_checkout.workflow_state.storage.checkout_state_diff_storage'
        tags:
            # Update Checkout state
            - { name: kernel.event_listener, event: oro_workflow.completed, method: updateCheckoutState, priority: 50 }
            - { name: kernel.event_listener, event: oro_workflow.transition_form_init, method: onFormInit }
            # Transition Pre-guard events
            - { name: kernel.event_listener, event: oro_workflow.pre_guard, method: onPreGuard }
            # Process updateStateToken
            - { name: kernel.event_listener, event: oro_workflow.start, method: updateStateTokenSinglePageCheckout }
            - { name: kernel.event_listener, event: oro_workflow.completed, method: updateStateTokenMultiPageCheckout, priority: -100 }
            # Checkout Workflow Start transitions
            - { name: kernel.event_listener, event: oro_workflow.completed, method: deleteCheckoutStateOnStart }
            # Checkout Workflow Finish events
            - { name: kernel.event_listener, event: oro_workflow.finish, method: deleteCheckoutState }
            # Works with current checkout state
            - { name: kernel.event_listener, event: oro_checkout.transition_request.before, method: initializeCurrentCheckoutState }
            - { name: kernel.event_listener, event: oro_checkout.transition_request.after, method: clearCurrentCheckoutState }

    oro_checkout.event_listener.workflow.checkout_state.checkout_config_builder_extension:
        class: Oro\Bundle\CheckoutBundle\WorkflowState\EventListener\Workflow\CheckoutConfigBuilderExtension
        tags:
            - {name: oro.workflow.definition_builder.extension }
