services:
    oro_checkout.action_group.b2b_flow_checkout.address_actions:
        class: Oro\Bundle\CheckoutBundle\Workflow\B2bFlowCheckout\ActionGroup\AddressActions
        public: true
        arguments:
            - '@doctrine'
            - '@oro_action.factory.duplicator_factory'
        tags:
            - { name: 'oro_action_group_service' }

    oro_checkout.action_group.b2b_flow_checkout.order_actions:
        class: Oro\Bundle\CheckoutBundle\Workflow\B2bFlowCheckout\ActionGroup\OrderActions
        public: true
        arguments:
            - '@oro_checkout.action_group.b2b_flow_checkout.address_actions'
            - '@oro_payment_term.provider.payment_term'
            - '@oro_checkout.data_provider.manager.checkout_line_items'
            - '@oro_checkout.mapper.order_mapper'
            - '@oro_checkout.payment_methods_provider'
            - '@oro_order.order.total.total_helper'
            - '@oro_action.action_executor'
        tags:
            - { name: 'oro_action_group_service' }

    oro_checkout.action_group.b2b_flow_checkout.split_order_actions:
        class: Oro\Bundle\CheckoutBundle\Workflow\B2bFlowCheckout\ActionGroup\SplitOrderActions
        public: true
        arguments:
            - '@oro_checkout.action_group.b2b_flow_checkout.order_actions'
            - '@oro_order.order.total.total_helper'
            - '@oro_checkout.splitter.checkout_splitter'
            - '@oro_checkout.provider.grouped_line_items'
            - '@oro_checkout.provider.multi_shipping.sub_order_owner'
            - '@oro_checkout.provider.multi_shipping.sub_order_organization'
            - '@oro_checkout.provider.multi_shipping.sub_order_shipping_method_setter'
            - '@oro_checkout.checkout_sub_order_shipping_price_provider'
            - '@oro_promotion.applied_promotion_manager'
        tags:
            - { name: 'oro_action_group_service' }

    oro_checkout.action_group.b2b_flow_checkout.checkout_actions:
        class: Oro\Bundle\CheckoutBundle\Workflow\B2bFlowCheckout\ActionGroup\CheckoutActions
        public: true
        arguments:
            - '@doctrine'
            - '@oro_entity.entity_alias_resolver'
            - '@oro_entity.entity_name_resolver'
            - '@router'
            - '@oro_action.action_executor'
        tags:
            - { name: 'oro_action_group_service' }

    oro_checkout.action_group.b2b_flow_checkout.customer_user_actions:
        class: Oro\Bundle\CheckoutBundle\Workflow\B2bFlowCheckout\ActionGroup\CustomerUserActions
        public: true
        arguments:
            - '@doctrine'
            - '@security.token_storage'
            - '@oro_customer.manager.guest_customer_user'
            - '@oro_customer_user.manager'
            - '@oro_shopping_list.manager.guest_shopping_list_migration'
            - '@oro_customer.security.login_manager'
            - '@oro_action.action_executor'
        tags:
            - { name: 'oro_action_group_service' }

    oro_checkout.workflow.b2b_flow_checkout.transition.continue_to_shipping_address:
        class: Oro\Bundle\CheckoutBundle\Workflow\B2bFlowCheckout\Transition\ContinueToShippingAddress
        public: true
        arguments:
            - '@oro_action.action_executor'
            - '@oro_checkout.provider.multi_shipping_config'
            - '@oro_checkout.provider.grouped_line_items'
            - '@oro_checkout.action_group.b2b_flow_checkout.customer_user_actions'
            - '@oro_checkout.action_group.b2b_flow_checkout.address_actions'
        tags:
            - { name: 'oro_workflow.transition_service' }

    oro_checkout.action_group.actualize_currency:
        class: Oro\Bundle\CheckoutBundle\Workflow\ActionGroup\ActualizeCurrency
        arguments:
            - '@oro_action.action_executor'
            - '@oro_pricing.user_currency_manager'
            - '@oro_currency.helper.currency_name'
        tags:
            - { name: 'oro_action_group_service' }

    oro_checkout.event_listener.process_workflow_request:
        class: Oro\Bundle\CheckoutBundle\Workflow\EventListener\ProcessWorkflowRequestEventListener
        arguments:
            - '@oro_checkout.helper.checkout_workflow_helper'
        tags:
            - { name: kernel.event_listener, event: oro_checkout.request, method: onCheckoutRequest, priority: -255 }

    oro_checkout.event_listener.verify_customer_consents:
        class: Oro\Bundle\CheckoutBundle\Workflow\EventListener\VerifyCustomerConsentsListener
        arguments:
            - '@oro_action.action_executor'
            - '@oro_checkout.helper.checkout_workflow_helper'
            - '@oro_workflow.manager'
            - '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: oro_checkout.request, method: checkConsents }
            - { name: kernel.event_listener, event: oro_workflow.entered, method: onStepEntered }
            - { name: oro_featuretogle.feature, feature: consents }

    oro_checkout.event_listener.checkout_request_actualize_currency:
        class: Oro\Bundle\CheckoutBundle\Workflow\EventListener\CheckoutRequestActualizeCurrencyListener
        arguments:
            - '@oro_checkout.action_group.actualize_currency'
        tags:
            - { name: kernel.event_listener, event: oro_checkout.request, method: onCheckoutRequest }

    oro_checkout.event_listener.checkout_request_preload_entities:
        class: Oro\Bundle\CheckoutBundle\EventListener\CheckoutRequestPreloadEntitiesListener
        arguments:
            - '@Oro\Bundle\EntityBundle\Manager\PreloadingManager'
        calls:
            -
                - 'setPreloadConfig'
                -
                    -
                        product:
                            backOrder: []
                            category:
                                backOrder: []
                                decrementQuantity: []
                                highlightLowInventory: []
                                inventoryThreshold: []
                                isUpcoming: []
                                lowInventoryThreshold: []
                                manageInventory: []
                                maximumQuantityToOrder: []
                                minimumQuantityToOrder: []
                            decrementQuantity: []
                            highlightLowInventory: []
                            inventoryThreshold: []
                            isUpcoming: []
                            lowInventoryThreshold: []
                            manageInventory: []
                            maximumQuantityToOrder: []
                            minimumQuantityToOrder: []
                            unitPrecisions: []
                        kitItemLineItems:
                            kitItem:
                                labels: []
                                productUnit: []
                            product:
                                names: []
                                unitPrecisions: []
                                images:
                                    types: []
                                    image:
                                        digitalAsset:
                                            titles: []
                                            sourceFile:
                                                digitalAsset: []
                            productUnit: []

        tags:
            - { name: kernel.event_listener, event: oro_checkout.request, method: onCheckoutRequest }
