workflows:
    order_processing_flow:
        steps:
            new:
                order: 10
                allowed_transitions:
                    - decline
                    - confirm
            confirmed:
                order: 20
                allowed_transitions:
                    - process
                    - mark_as_shipped
            processing:
                order: 30
                allowed_transitions:
                    - complete
                    - mark_as_shipped
            completed:
                order: 40
                is_final: true
            declined:
                order: 20
                is_final: true
