services:
    oro_shipping.form.type.shipping_origin:
        class: Oro\Bundle\ShippingBundle\Form\Type\ShippingOriginType
        arguments:
            - '@oro_address.form.listener.address'
        calls:
            - [setDataClass, ['Oro\Bundle\ShippingBundle\Model\ShippingOrigin']]
        tags:
            - { name: form.type }

    oro_shipping.form.type.shipping_origin_config:
        class: Oro\Bundle\ShippingBundle\Form\Type\ShippingOriginConfigType
        tags:
            - { name: form.type }

    oro_shipping.form.type.length_unit_select:
        class: Oro\Bundle\ShippingBundle\Form\Type\LengthUnitSelectType
        arguments:
            - '@oro_shipping.provider.measure_units.length'
            - '@oro_shipping.formatter.length_unit_label'
        calls:
            - [setEntityClass, ['Oro\Bundle\ShippingBundle\Entity\LengthUnit']]
        tags:
            - { name: form.type, alias: oro_shipping_length_unit_select }

    oro_shipping.form.type.weight_unit_select:
        class: Oro\Bundle\ShippingBundle\Form\Type\WeightUnitSelectType
        arguments:
            - '@oro_shipping.provider.measure_units.weight'
            - '@oro_shipping.formatter.weight_unit_label'
        calls:
            - [setEntityClass, ['Oro\Bundle\ShippingBundle\Entity\WeightUnit']]
        tags:
            - { name: form.type, alias: oro_shipping_weight_unit_select }

    oro_shipping.form.type.freight_class_select:
        class: Oro\Bundle\ShippingBundle\Form\Type\FreightClassSelectType
        arguments:
            - '@oro_shipping.provider.measure_units.freight'
            - '@oro_shipping.formatter.freight_class_label'
        calls:
            - [setEntityClass, ['Oro\Bundle\ShippingBundle\Entity\FreightClass']]
        tags:
            - { name: form.type, alias: oro_shipping_freight_class_select }

    oro_shipping.form.type.weight:
        class: Oro\Bundle\ShippingBundle\Form\Type\WeightType
        calls:
            - [setDataClass, ['Oro\Bundle\ShippingBundle\Model\Weight']]
        tags:
            - { name: form.type, alias: oro_shipping_weight }

    oro_shipping.form.type.shipping_methods_configs_rule:
        class: Oro\Bundle\ShippingBundle\Form\Type\ShippingMethodsConfigsRuleType
        tags:
            - { name: form.type }

    oro_shipping.form.type.shipping_method_type_config_collection:
        class: Oro\Bundle\ShippingBundle\Form\Type\ShippingMethodTypeConfigCollectionType
        arguments:
            - '@oro_shipping.form_event_subscriber.method_type_config_collection_subscriber'
        tags:
            - { name: form.type }

    oro_shipping.form.type.shipping_methods_configs_rule_destination:
        class: Oro\Bundle\ShippingBundle\Form\Type\ShippingMethodsConfigsRuleDestinationType
        arguments:
            - '@oro_shipping.form.listener.rule_destination'
        tags:
            - { name: form.type}

    oro_shipping.form.type.shipping_method_config:
        class: Oro\Bundle\ShippingBundle\Form\Type\ShippingMethodConfigType
        arguments:
            - '@oro_shipping.form_event_subscriber.method_config_subscriber'
            - '@oro_shipping.shipping_method_provider'
        tags:
            - { name: form.type }

    oro_shipping.form.listener.rule_destination:
        class: Oro\Bundle\AddressBundle\Form\EventListener\AddressCountryAndRegionSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@form.factory'

    oro_shipping.form_event_subscriber.method_type_config_collection_subscriber:
        class: Oro\Bundle\ShippingBundle\Form\EventSubscriber\MethodTypeConfigCollectionSubscriber
        arguments:
            - '@oro_shipping.shipping_method_provider'

    oro_shipping.form_event_subscriber.method_config_collection_subscriber:
        class: Oro\Bundle\ShippingBundle\Form\EventSubscriber\MethodConfigCollectionSubscriber
        arguments:
            - '@oro_shipping.shipping_method_provider'

    oro_shipping.form_event_subscriber.method_config_subscriber:
        class: Oro\Bundle\ShippingBundle\Form\EventSubscriber\MethodConfigSubscriber
        arguments:
            - '@form.factory'
            - '@oro_shipping.shipping_method_provider'

    oro_shipping.form.type.dimensions:
        class: Oro\Bundle\ShippingBundle\Form\Type\DimensionsType
        calls:
            - [setDataClass, ['Oro\Bundle\ShippingBundle\Model\Dimensions']]
        tags:
            - { name: form.type, alias: oro_shipping_dimensions }

    oro_shipping.form.type.dimensions_value:
        class: Oro\Bundle\ShippingBundle\Form\Type\DimensionsValueType
        calls:
            - [setDataClass, ['Oro\Bundle\ShippingBundle\Model\DimensionsValue']]
        tags:
            - { name: form.type, alias: oro_shipping_dimensions_value }

    oro_shipping.form.product_shipping_option:
        class: Oro\Bundle\ShippingBundle\Form\Type\ProductShippingOptionsType
        calls:
            - [setDataClass, ['Oro\Bundle\ShippingBundle\Entity\ProductShippingOptions']]
        tags:
            - { name: form.type, alias: oro_shipping_product_shipping_options }

    oro_shipping.form.product_shipping_option_collection:
        class: Oro\Bundle\ShippingBundle\Form\Type\ProductShippingOptionsCollectionType
        calls:
            - [setDataClass, ['Oro\Bundle\ShippingBundle\Entity\ProductShippingOptions']]
        tags:
            - { name: form.type, alias: oro_shipping_product_shipping_options_collection }

    oro_shipping.form.extension.product_type:
        class: Oro\Bundle\ShippingBundle\Form\Extension\ProductFormExtension
        arguments:
            - '@doctrine'
        calls:
            - [setFieldAclHelper, ['@oro_security.form.field_acl_helper']]
        tags:
            - { name: form.type_extension, alias: oro_product, extended_type: Oro\Bundle\ProductBundle\Form\Type\ProductType }

    oro_shipping.form.type.shipping_method_config_collection:
        class: Oro\Bundle\ShippingBundle\Form\Type\ShippingMethodConfigCollectionType
        arguments:
            - '@oro_shipping.form_event_subscriber.method_config_collection_subscriber'
        tags:
            - { name: form.type }

    oro_shipping.form.type.shipping_method_select:
        class: Oro\Bundle\ShippingBundle\Form\Type\ShippingMethodSelectType
        arguments:
            - '@oro_shipping.provider.shipping_methods_choices'
            - '@oro_shipping.provider.shipping_method_icon'
            - '@assets.packages'
        tags:
            - { name: form.type }

    oro_shipping.form.type.product_kit_shipping_calculation_method:
        class: Oro\Bundle\ShippingBundle\Form\Type\ProductKitShippingCalculationMethodType
        tags:
            - { name: form.type }
