services:
    oro_payment_term.form.type.payment_term:
        class: 'Oro\Bundle\PaymentTermBundle\Form\Type\PaymentTermType'
        arguments:
            - 'Oro\Bundle\PaymentTermBundle\Entity\PaymentTerm'
            - '@oro_ui.html_tag_helper'
        tags:
            - { name: form.type, alias: oro_payment_term }

    oro_payment_term.form.type.payment_term_select:
        class: 'Oro\Bundle\PaymentTermBundle\Form\Type\PaymentTermSelectType'
        tags:
            - { name: form.type, alias: oro_payment_term_select }

    oro_payment_term.form.extension.customer_type:
        class: 'Oro\Bundle\PaymentTermBundle\Form\Extension\CustomerFormExtension'
        arguments:
            - '@oro_payment_term.provider.payment_term'
            - '@oro_payment_term.provider.payment_term_association'
            - '@translator'
        tags:
            - { name: form.type_extension, alias: oro_customer_type, extended_type: Oro\Bundle\CustomerBundle\Form\Type\CustomerType }

    oro_payment_term.form.extension.order_type:
        class: 'Oro\Bundle\PaymentTermBundle\Form\Extension\OrderPaymentTermAclExtension'
        arguments:
            - '@oro_payment_term.provider.payment_term_association'
            - '@security.authorization_checker'
        calls:
            - [setAclResource, ['oro_order_payment_term_customer_can_override']]
        tags:
            - { name: form.type_extension, alias: oro_order_type, extended_type: Oro\Bundle\OrderBundle\Form\Type\OrderType }

    oro_payment_term.form.extension.suborder_type:
        class: Oro\Bundle\PaymentTermBundle\Form\Extension\SubOrderPaymentTermAclExtension
        arguments:
            - '@oro_payment_term.provider.payment_term_association'
            - '@security.authorization_checker'
        calls:
            - [setAclResource, ['oro_order_payment_term_customer_can_override']]
        tags:
            - { name: form.type_extension, alias: oro_suborder_type, extended_type: Oro\Bundle\OrderBundle\Form\Type\SubOrderType }

    oro_payment_term.form.extension.quote_type:
        class: 'Oro\Bundle\PaymentTermBundle\Form\Extension\QuotePaymentTermAclExtension'
        arguments:
            - '@oro_payment_term.provider.payment_term_association'
            - '@security.authorization_checker'
        calls:
            - [setAclResource, ['oro_quote_payment_term_customer_can_override']]
        tags:
            - { name: form.type_extension, alias: oro_sale_quote, extended_type: Oro\Bundle\SaleBundle\Form\Type\QuoteType }

    oro_payment_term.form.extension.payment_term_select:
        class: 'Oro\Bundle\PaymentTermBundle\Form\Extension\PaymentTermExtension'
        arguments:
            - '@oro_payment_term.provider.payment_term'
        tags:
            - { name: form.type_extension, alias: oro_payment_term_select, extended_type: Oro\Bundle\PaymentTermBundle\Form\Type\PaymentTermSelectType }
