imports:
    - { resource: 'actions/b2b_flow_checkout.yml' }
    - { resource: 'actions/b2b_flow_checkout_single_page.yml' }

operations:
    UPDATE:
        exclude_datagrids:
            - frontend-checkouts-grid
            - frontend-checkout-line-items-grid
            - frontend-single-page-checkout-line-items-grid

    DELETE:
        exclude_datagrids:
            - frontend-checkout-line-items-grid
            - frontend-single-page-checkout-line-items-grid

    oro_checkout_delete_order:
        extends: DELETE
        applications: [commerce]
        for_all_datagrids: false
        for_all_entities: false
        label: oro.checkout.grid.delete.label
        preconditions:
            '@and':
                - '@not_blank': $.data
                - '@equal': [$.data.completed, false]
        datagrids:
            - frontend-checkouts-grid
        datagrid_options:
            aria_label: delete_aria_label
        replace:
            - applications
            - preconditions
            - datagrids
        preactions:
            - '@trans':
                id: oro.checkout.open_order.label
                attribute: $.entityLabel

    oro_checkout_frontend_view_order:
        label: oro.checkout.frontend.order.view.label
        applications: [commerce]
        datagrids:
            - frontend-checkouts-grid
        datagrid_options:
            aria_label: view_aria_label
        order: 20
        button_options:
            icon: fa-eye
        preactions:
            - '@tree':
                conditions:
                    '@equal': [$.data.completed, true]
                actions:
                    - '@call_method':
                        object: $.data.completedData
                        method: getOrderData
                        attribute: $.orderData
                    - '@tree':
                        conditions:
                            '@not_empty': $.orderData
                        actions:
                            - '@call_service_method':
                                service: oro_entity.entity_alias_resolver
                                method: getClassByAlias
                                method_parameters: [$.orderData.entityAlias]
                                attribute: $.entityClass
                            - '@find_entity':
                                class: $.entityClass
                                where: $.orderData.entityId
                                attribute: $.order
        preconditions:
            '@and':
                - '@equal': [$.data.completed, true]
                - '@not_empty': $.order
                - '@acl_granted': [VIEW, $.order]
        actions:
            - '@redirect':
                 route: 'oro_order_frontend_view'
                 route_parameters: {id: $.order.id}

    oro_checkout_frontend_start_from_order:
        label: oro.checkout.frontend.start_from_order
        applications: [commerce]
        routes:
            - oro_order_frontend_view
        datagrids:
            - frontend-orders-grid
        datagrid_options:
            aria_label: start_from_order_aria_label
        acl_resource: [CHECKOUT_CREATE, $.data]
        button_options:
            class: text-nowrap
            icon: 'shopping-cart'
            data:
                responsive-styler: ''
                input-widget-options:
                    responsive:
                        mobile-landscape:
                            constraint: 'inDropdown'
                            classes: 'dropdown-item'
        frontend_options:
            options:
                icon: 'shopping-cart'

        preconditions:
            '@and':
                - '@workflow_available_by_record_group':
                    group_name: b2b_checkout_flow
                    entity_class: Oro\Bundle\CheckoutBundle\Entity\Checkout
        actions:
            - '@call_service_method':
                attribute: $.checkoutLineItems
                service: oro_checkout.line_items.factory
                method: create
                method_parameters: [$.data]

            - '@flash_message':
                conditions:
                    '@not':
                        - '@has_elements': $.checkoutLineItems
                message: oro.checkout.frontend.checkout.cannot_create_reorder_no_line_items
                type: 'warning'

            - '@tree':
                conditions:
                    '@has_elements': $.checkoutLineItems
                actions:
                    - '@run_action_group':
                        action_group: start_checkout
                        parameters_mapping:
                            force: true
                            forceStartCheckout: true
                            sourceCriteria:
                                order: $.data
                            settings:
                                allow_manual_source_remove: false
                                remove_source: false
                            showErrors: true
                            validateOnStartCheckout: true
                        results:
                            redirectUrl: $.redirectUrl
                            checkout: $.checkout
                            errors: $.errors
                    - '@call_service_method':
                        attribute: $.changedSkus
                        service: oro_checkout.provider.checkout_line_items
                        method: getProductSkusWithDifferences
                        method_parameters: [$.checkout.lineItems, $.data.lineItems]
                    - '@tree':
                        conditions:
                            '@has_elements': $.changedSkus
                        actions:
                            - '@call_method':
                                attribute: $.changedSkus
                                method: implode
                                method_parameters: [', ', $.changedSkus]
                            - '@flash_message':
                                message: oro.checkout.frontend.checkout.some_changes_in_line_items
                                message_parameters:
                                    skus: $.changedSkus
                                type: 'warning'

action_groups:
    oro_update_shipping_price:
        service: oro_checkout.action_group.update_shipping_price

    start_quickorder_checkout:
        service: oro_checkout.action_group.start_quick_order_checkout

    start_shoppinglist_checkout:
        service: oro_checkout.action_group.start_from_shopping_list

    prepare_checkout_settings:
        service: oro_checkout.action_group.prepare_checkout_settings
        return_value_name: 'settings'

    start_checkout:
        service: oro_checkout.action_group.start_checkout

    find_checkout:
        service: oro_checkout.action_group.find_or_create_checkout

    actualize_checkout:
        service: oro_checkout.action_group.actualize_checkout
        return_value_name: 'checkout'

    update_workflow_item:
        service: oro_checkout.action_group.update_workflow_item

    actualize_currency:
        service: oro_checkout.action_group.actualize_currency

    update_checkout_state:
        service: oro_checkout.action_group.update_checkout_state
        return_value_name: 'update_checkout_state'

    order_line_items_not_empty:
        service: oro_checkout.action_group.order_line_items_not_empty
