features:
    checkout_customer_users_registration:
        label: oro.checkout.feature.checkout_customer_users_registration.label
        description: oro.checkout.feature.checkout_customer_users_registration.description
        toggle: oro_checkout.registration_allowed
        dependencies:
            - oro_customer_registration_allowed

    oro_customer_registration_allowed:
        configuration:
            - oro_checkout.registration_allowed
            - checkout_customer_users_registration

    allow_checkout_without_email_confirmation_feature:
        label: oro.checkout.feature.allow_checkout_without_email_confirmation.label
        description: oro.checkout.feature.allow_checkout_without_email_confirmation.description
        toggle: oro_checkout.allow_checkout_without_email_confirmation
        dependencies:
            - oro_customer_confirmation_required

    oro_customer_confirmation_required:
        configuration:
            - oro_checkout.allow_checkout_without_email_confirmation

    guest_checkout:
        label: oro.checkout.feature.guest_checkout.label
        description: oro.checkout.feature.guest_checkout.description
        toggle: oro_checkout.guest_checkout
        routes:
            - 'oro_checkout_frontend_checkout'
        configuration:
            - guest_checkout_owner_section
        strategy: affirmative

    oro_address_validation:
        routes:
            - oro_checkout_address_validation_multi_step_billing_address
            - oro_checkout_address_validation_multi_step_shipping_address
            - oro_checkout_address_validation_multi_step_new_billing_address
            - oro_checkout_address_validation_multi_step_new_shipping_address
            - oro_checkout_address_validation_single_page_billing_address
            - oro_checkout_address_validation_single_page_shipping_address
            - oro_checkout_address_validation_single_page_new_billing_address
            - oro_checkout_address_validation_single_page_new_shipping_address
        configuration:
            - oro_checkout.validate_shipping_addresses__checkout
            - oro_checkout.validate_billing_addresses__checkout
