system_configuration:
    fields:
        oro_cms.landing_page_direct_url_prefix:
            data_type: string
            type: Oro\Bundle\RedirectBundle\Form\Type\SluggableEntityPrefixType
            search_type: text
            options:
                label: oro.cms.system_configuration.fields.landing_page_direct_url_prefix.label
                data_transformer: oro_redirect.form.transformer.prefix_with_redirect_to_string
                required: false
                constraints:
                    - Oro\Bundle\ValidationBundle\Validator\Constraints\UrlSafe: ~

        oro_cms.home_page:
            data_type: integer
            type: Oro\Bundle\CMSBundle\Form\Type\PageSelectType
            options:
                label: oro.cms.system_configuration.fields.home_page.label
                tooltip: oro.cms.system_configuration.fields.home_page.tooltip
                required: true
                create_enabled: false
                constraints:
                    - NotBlank: ~
                configs:
                    allowClear: false
                attr:
                    class: control-subgroup

    tree:
        system_configuration:
            platform:
                children:
                    websites:
                        children:
                            routing:
                                children:
                                    oro_redirect_direct_urls:
                                        children:
                                            - oro_cms.landing_page_direct_url_prefix
                                    websites_routing_general:
                                        children:
                                            - oro_cms.home_page
