oro_sanitize:
    entity:
        oro_integration_transport:
            fields:
                fedex_client_id: md5
                fedex_client_secret: md5
                fedex_account_number: md5
                fedex_access_token: md5
