services:
    _defaults:
        public: true

    Oro\Bundle\PromotionBundle\Controller\AjaxPromotionController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\PromotionBundle\Controller\PromotionController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_product.service.product_collection_definition_converter, key: Oro\Bundle\ProductBundle\Service\ProductCollectionDefinitionConverter }

    Oro\Bundle\PromotionBundle\Controller\AjaxCouponController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_promotion.handler.coupon_validation_handler, key: Oro\Bundle\PromotionBundle\Handler\CouponValidationHandler }

    Oro\Bundle\PromotionBundle\Controller\CouponController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\PromotionBundle\Controller\Frontend\AjaxCouponController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_promotion.entity_promotion_aware_helper, key: Oro\Bundle\PromotionBundle\Model\PromotionAwareEntityHelper }
            - { name: container.service_subscriber, id: oro_promotion.handler.frontend_coupon_handler, key: Oro\Bundle\PromotionBundle\Handler\FrontendCouponHandler }
            - { name: container.service_subscriber, id: oro_promotion.handler.frontend_coupon_remove_handler, key: Oro\Bundle\PromotionBundle\Handler\FrontendCouponRemoveHandler }
