imports:
    - { resource: '../includes/attributes.yml' }
    - { resource: '../b2b_flow_checkout/attributes.yml' }

workflows:
    b2b_flow_checkout:
        attributes:
            shipping_data_ready:
                type: boolean
