services:
    # Quote form types
    oro_sale.form.type.quote:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteType'
        arguments:
            - "@oro_sale.provider.quote_address_security"
            - '@oro_config.global'
            - '@oro_sale.form.event_listener.quote_update'
            - '@security.authorization_checker'
        calls:
            - [setDataClass, ['Oro\Bundle\SaleBundle\Entity\Quote']]
        tags:
            - { name: form.type, alias: oro_sale_quote }

    oro_sale.form.type.quote_product:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductType'
        arguments:
            - "@translator"
            - "@oro_product.formatter.product_unit_label"
            - "@oro_sale.formatter.quote_product"
            - "@doctrine"
        calls:
            - [setDataClass, ['Oro\Bundle\SaleBundle\Entity\QuoteProduct']]
            - [setProductUnitClass, ['Oro\Bundle\ProductBundle\Entity\ProductUnit']]
        tags:
            - { name: form.type, alias: oro_sale_quote_product }

    oro_sale.form.type.quote_product_offer:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductOfferType'
        arguments:
            - "@oro_sale.formatter.quote_product_offer"
        calls:
            - [setDataClass, ['Oro\Bundle\SaleBundle\Entity\QuoteProductOffer']]
        tags:
            - { name: form.type, alias: oro_sale_quote_product_offer }

    oro_sale.form.type.quote_product_request:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductRequestType'
        calls:
            - [setDataClass, ['Oro\Bundle\SaleBundle\Entity\QuoteProductRequest']]
        tags:
            - { name: form.type, alias: oro_sale_quote_product_request }

    oro_sale.form.type.quote_product_collection:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductCollectionType'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_collection }

    oro_sale.form.type.quote_product_offer_collection:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductOfferCollectionType'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_offer_collection }

    oro_sale.form.type.quote_product_request_collection:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductRequestCollectionType'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_request_collection }

    oro_sale.form.type.extension.quote_data_storage:
        class: 'Oro\Bundle\SaleBundle\Form\Extension\QuoteDataStorageExtension'
        parent: oro_product.form.type.extension.product_data_storage.abstract
        calls:
            - [setDataClass, ['Oro\Bundle\SaleBundle\Entity\Quote']]
        tags:
            - { name: form.type_extension, alias: oro_sale_quote, extended_type: Oro\Bundle\SaleBundle\Form\Type\QuoteType }

    oro_sale.form.type.extension.quote_email_template:
        class: 'Oro\Bundle\SaleBundle\Form\Extension\QuoteEmailTemplateExtension'
        arguments:
            - '@oro_security.token_accessor'
            - '@oro_featuretoggle.checker.feature_checker'
        calls:
            - [ setOrganizationProvider, [ '@oro_email.email_template_organization_provider' ] ]
        tags:
            - { name: form.type_extension, alias: oro_email_email, extended_type: Oro\Bundle\EmailBundle\Form\Type\EmailType }

    oro_sale.form.type.quote_address:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteAddressType'
        arguments:
            - "@oro_locale.formatter.address"
            - "@oro_sale.manager.quote_address"
            - "@oro_sale.provider.quote_address_security"
            - "@oro_importexport.serializer"
        tags:
            - { name: form.type, alias: oro_quote_address_type }
        calls:
            - [setDataClass, ['Oro\Bundle\SaleBundle\Entity\QuoteAddress']]

    oro_sale.form.type.quote_demand:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteDemandType'
        arguments:
            - "@oro_sale.manager.quote_demand_manager"
        tags:
            - { name: form.type, alias: oro_sale_quote_demand }

    oro_sale.form.type.quote_product_demand:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductDemandType'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_demand }

    oro_sale.form.type.quote_product_demand_collection:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductDemandCollectionType'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_demand_collection }

    oro_sale.form.type.quote_product_demand_offer_choice:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductDemandOfferChoiceType'
        arguments:
            - '@oro_product.formatter.product_unit_value'
            - '@translator'
            - '@oro_product.visibility.unit'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_demand_offer_choice }

    oro_sale.form.event_listener.quote_update:
        class: 'Oro\Bundle\SaleBundle\Form\EventListener\QuoteFormSubscriber'
        arguments:
            - '@oro_sale.provider.quote_product_price'
            - '@translator'
            - '@oro_entity.doctrine_helper'

    oro_sale.form_type.contact_info_customer_options_type:
        class: Oro\Bundle\SaleBundle\Form\Type\ContactInfoSourceOptionsType
        arguments:
            - '@oro_sale.provider.contact_info_source_options_provider'
        tags:
            - { name: form.type, alias: oro_sale_contact_info_customer_option }

    oro_sale.form.type.contact_info_user_available_type:
        class: Oro\Bundle\SaleBundle\Form\Type\ContactInfoUserAvailableOptionsType
        arguments:
            - '@oro_sale.provider.contact_info_available_user_options_provider'
        tags:
            - { name: form.type, alias: oro_sale_contact_info_user_available_option }

    oro_sale.form.type.contact_info_user_type:
        class: Oro\Bundle\SaleBundle\Form\Type\ContactInfoUserOptionsType
        arguments:
            - '@oro_sale.provider.contact_info_user_options_provider'
            - '@oro_config.manager'
        tags:
            - { name: form.type, alias: oro_sale_contact_info_user_option }

    oro_sale.form.type.contact_manual_text_type:
        class: Oro\Bundle\SaleBundle\Form\Type\ContactInfoManualTextType
        arguments:
            - '@oro_config.manager'
        tags:
            - { name: form.type, alias: oro_sale_contact_info_manual_text }
