services:
    oro_sale.form.type.quote:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteType'
        arguments:
            - '@oro_sale.provider.quote_address_security'
            - '@oro_config.global'
            - '@oro_sale.form.event_listener.quote_update'
            - '@security.authorization_checker'
        tags:
            - { name: form.type, alias: oro_sale_quote }

    oro_sale.form.type.quote_product:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductType'
        arguments:
            - '@oro_product.formatter.product_unit_label'
            - '@doctrine'
            - '@oro_sale.form.event_listener.quote_product_product'
            - '@oro_sale.form.event_listener.quote_product_offer_checksum'
        tags:
            - { name: form.type }

    oro_sale.form.event_listener.quote_product_offer_checksum:
        class: Oro\Bundle\SaleBundle\Form\EventListener\QuoteProductOfferChecksumListener
        arguments:
            - '@oro_product.line_item_checksum_generator'

    oro_sale.form.type.quote_product_offer:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductOfferType'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_offer }

    oro_sale.form.type.quote_product_request:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductRequestType'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_request }

    oro_sale.form.type.quote_product_collection:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductCollectionType'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_collection }

    oro_sale.form.type.quote_product_offer_collection:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductOfferCollectionType'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_offer_collection }

    oro_sale.form.type.quote_product_request_collection:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductRequestCollectionType'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_request_collection }

    oro_sale.form.type.extension.quote_data_storage:
        class: 'Oro\Bundle\SaleBundle\Form\Extension\QuoteDataStorageExtension'
        arguments:
            - '@request_stack'
            - '@oro_product.storage.product_data_storage'
            - '@form.property_accessor'
            - '@doctrine'
            - '@oro_product.line_item_checksum_generator'
            - '@logger'
            - '@oro_sale.provider.quote_product_prices'
        tags:
            - { name: form.type_extension }

    oro_sale.form.type.extension.quote_email_template:
        class: 'Oro\Bundle\SaleBundle\Form\Extension\QuoteEmailTemplateExtension'
        arguments:
            - '@oro_security.token_accessor'
            - '@oro_featuretoggle.checker.feature_checker'
        tags:
            - { name: form.type_extension, alias: oro_email_email, extended_type: Oro\Bundle\EmailBundle\Form\Type\EmailType }

    oro_sale.form.type.quote_address:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteAddressType'
        arguments:
            - '@oro_locale.formatter.address'
            - '@oro_sale.manager.quote_address'
            - '@oro_sale.provider.quote_address_security'
            - '@oro_importexport.serializer'
        tags:
            - { name: form.type, alias: oro_quote_address_type }

    oro_sale.form.type.quote_demand:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteDemandType'
        arguments:
            - '@oro_sale.manager.quote_demand_manager'
        tags:
            - { name: form.type, alias: oro_sale_quote_demand }

    oro_sale.form.type.quote_product_demand:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductDemandType'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_demand }

    oro_sale.form.type.quote_product_demand_collection:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductDemandCollectionType'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_demand_collection }

    oro_sale.form.type.quote_product_demand_offer_choice:
        class: 'Oro\Bundle\SaleBundle\Form\Type\QuoteProductDemandOfferChoiceType'
        arguments:
            - '@oro_product.formatter.product_unit_value'
            - '@translator'
            - '@oro_product.visibility.unit'
        tags:
            - { name: form.type, alias: oro_sale_quote_product_demand_offer_choice }

    oro_sale.form.event_listener.quote_update:
        class: 'Oro\Bundle\SaleBundle\Form\EventListener\QuoteFormSubscriber'
        arguments:
            - '@doctrine'
            - '@oro_sale.provider.quote_product_prices'
            - '@oro_sale.quote.pricing.comparator'
            - '@translator'

    oro_sale.form_type.contact_info_customer_options_type:
        class: Oro\Bundle\SaleBundle\Form\Type\ContactInfoSourceOptionsType
        arguments:
            - '@oro_sale.provider.contact_info_source_options_provider'
        tags:
            - { name: form.type, alias: oro_sale_contact_info_customer_option }

    oro_sale.form.type.contact_info_user_available_type:
        class: Oro\Bundle\SaleBundle\Form\Type\ContactInfoUserAvailableOptionsType
        arguments:
            - '@oro_sale.provider.contact_info_available_user_options_provider'
        tags:
            - { name: form.type, alias: oro_sale_contact_info_user_available_option }

    oro_sale.form.type.contact_info_user_type:
        class: Oro\Bundle\SaleBundle\Form\Type\ContactInfoUserOptionsType
        arguments:
            - '@oro_sale.provider.contact_info_user_options_provider'
            - '@oro_config.manager'
        tags:
            - { name: form.type, alias: oro_sale_contact_info_user_option }

    oro_sale.form.type.contact_manual_text_type:
        class: Oro\Bundle\SaleBundle\Form\Type\ContactInfoManualTextType
        arguments:
            - '@oro_config.manager'
        tags:
            - { name: form.type, alias: oro_sale_contact_info_manual_text }

    oro_sale.form.event_listener.quote_product_product:
        class: Oro\Bundle\SaleBundle\Form\EventListener\QuoteProductProductListener
        arguments:
            - '@oro_entity.tools.entity_state_checker'

    oro_sale.form.event_listener.quote_product_kit_item_line_item_default_data:
        class: Oro\Bundle\SaleBundle\Form\EventListener\QuoteProductKitItemLineItemDefaultDataListener
        arguments:
            - '@oro_sale.product_kit.factory.quote_product_kit_item_line_item'

    oro_sale.form.type.quote_product_kit_item_line_item_collection:
        class: Oro\Bundle\SaleBundle\Form\Type\QuoteProductKitItemLineItemCollectionType
        tags:
            - { name: form.type }

    oro_sale.form.type.quote_product_kit_item_line_item:
        class: Oro\Bundle\SaleBundle\Form\Type\QuoteProductKitItemLineItemType
        arguments:
            - '@oro_sale.product_kit.provider.product_kit_item_products'
            - '@oro_sale.form.event_listener.quote_product_kit_item_line_item_default_data'
            - '@oro_sale.form.event_listener.quote_product_kit_item_line_item_ghost_option'
        tags:
            - { name: form.type }

    oro_sale.form.event_listener.quote_product_kit_item_line_item_ghost_option:
        class: Oro\Bundle\SaleBundle\Form\EventListener\QuoteProductKitItemLineItemGhostOptionListener
