styles:
    inputs:
        - 'bundles/orocatalog/default/scss/variables/category-title-config.scss'
        - 'bundles/orocatalog/default/scss/variables/category-picture-config.scss'
        - 'bundles/orocatalog/default/scss/variables/category-long-description-config.scss'
        - 'bundles/orocatalog/default/scss/variables/categories-config.scss'

        - 'bundles/orocatalog/default/scss/components/category-picture.scss'
        - 'bundles/orocatalog/default/scss/components/category-title.scss'
        - 'bundles/orocatalog/default/scss/components/category-long-description.scss'
        - 'bundles/orocatalog/default/scss/components/categories.scss'
