Oro\Bundle\WebCatalogBundle\Entity\WebCatalog:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 255

Oro\Bundle\WebCatalogBundle\Entity\ContentNode:
    constraints:
        - Oro\Bundle\WebCatalogBundle\Validator\Constraint\NodeNotEmptyScopes: ~
        - Oro\Bundle\WebCatalogBundle\Validator\Constraint\UniqueSlugPrototype: ~
    properties:
        contentVariants:
            - Count:
                min: 1
                minMessage: 'oro.webcatalog.contentnode.content_variants.blank'
            - Oro\Bundle\WebCatalogBundle\Validator\Constraint\UniqueScope: ~
            - Oro\Bundle\WebCatalogBundle\Validator\Constraint\NotEmptyScopes: ~
            - Valid: ~
        titles:
            - Valid: ~
        slugPrototypes:
            - Valid: ~

Oro\Bundle\WebCatalogBundle\Entity\ContentVariant:
    constraints:
        - Oro\Bundle\WebCatalogBundle\Validator\Constraint\SameOrganization: ~

Oro\Bundle\WebsiteSearchTermBundle\Entity\SearchTerm:
    properties:
        redirectContentNode:
            -   When:
                    expression: 'this.getRedirectActionType() == "content_node"'
                    constraints:
                        -   NotBlank: ~
                    groups:
                        # Used in \Oro\Bundle\WebsiteSearchTermBundle\Controller\SearchTermController
                        - website_search_term_create
                        # Used in \Oro\Bundle\WebsiteSearchTermBundle\Controller\SearchTermController
                        - website_search_term_update
