operations:
    oro_sale_expire_quote:
        label: oro.sale.quote.actions.quote_expire
        enabled: true
        acl_resource: oro_sale_quote_update
        applications: [default]
        routes:
            - oro_sale_quote_view
        datagrids:
            - quotes-grid
        order: 40
        button_options:
            icon: fa-clock-o
        frontend_options:
            confirmation:
                message: oro.sale.quote.actions.quote_expire_confirm
                okText: oro.sale.quote.actions.mark_as_expired
                component: oroui/js/delete-confirmation
        preconditions:
            '@equal': [$expired, false]
        actions:
            - '@run_action_group':
                action_group: oro_sale_expire_quote
                parameters_mapping:
                    data: $.data
            - '@flash_message':
                message: oro.sale.quote.message.quote.expire.success
                type: 'info'
                message_parameters:
                    id: $id
            - '@redirect':
                conditions:
                    '@and':
                        - '@empty': $.gridName
                        - '@not_empty': $.routes[name]
                parameters:
                    route: $.routes[name]

    oro_sale_notify_customer_by_email:
        label: oro.sale.quote.notify_customer.by_email.link.text
        applications: [default]
        routes:
            - oro_sale_quote_view
        order: 20
        acl_resource: oro_email_email_create

        button_options:
            icon: fa-envelope
            group: oro.sale.quote.notify_customer.label

        frontend_options:
            template: '@OroSale/Action/emailNotification.html.twig'
            title: oro.sale.quote.notify_customer.by_email.link.text
            options:
                allowMaximize: true
                allowMinimize: true
                dblclick: maximize
                maximizedHeightDecreaseBy: minimize-bar
                width: 1000

        attributes:
            email:
                label: ' '
                type: object
                options:
                    class: Oro\Bundle\EmailBundle\Form\Model\Email

        form_options:
            attribute_fields:
                email:
                    form_type: Oro\Bundle\EmailBundle\Form\Type\EmailType

        form_init:
            - '@call_service_method':
                attribute: $.email
                service: oro_sale.helper.notification
                method: getEmailModel
                method_parameters: [$.data]
            - '@call_service_method':
                attribute: $.appendSignature
                service: oro_config.manager
                method: get
                method_parameters: ['oro_email.append_signature']

        preactions:
            - '@assign_constant_value':
                attribute: $.sentToCustomerInternalStatus
                value: Oro\Bundle\SaleBundle\Entity\Quote::INTERNAL_STATUS_SENT_TO_CUSTOMER

        preconditions:
            '@not_equal': [$.sentToCustomerInternalStatus, $internalStatus.id]

        actions:
            - '@run_action_group':
                action_group: oro_sale_notify_customer_by_email
                parameters_mapping:
                    email: $.email
            - '@request_enum_entity':
                enum_code: 'quote_internal_status'
                attribute: $internalStatus
                identifier: 'sent_to_customer'
            - '@flush_entity': $.data
            - '@flash_message':
                message: oro.sale.quote.message.quote.sent.success
                type: 'info'
                message_parameters:
                    id: $qid

    oro_sale_frontend_quote_submit_to_order:
        label: oro.sale.quote.actions.submit_to_order
        groups:
            - oro_sale_frontend_quote_submit_to_order
        applications: [commerce]
        routes:
            - oro_sale_quote_frontend_view
        order: 20
        acl_resource: [CHECKOUT_CREATE, 'entity:Oro\Bundle\SaleBundle\Entity\QuoteDemand']
        button_options:
            icon: fa-pencil-square-o
            class:  quota-accept-btn
        service: oro_sale.operation.frontend_quote_submit_to_order

    oro_sale_frontend_guest_quote_submit_to_order:
        label: oro.sale.quote.actions.submit_to_order
        applications: [commerce]
        routes:
            - oro_sale_quote_frontend_view_guest
        order: 20
        acl_resource: [CREATE, entity:commerce@Oro\Bundle\CheckoutBundle\Entity\Checkout]
        button_options:
            icon: fa-pencil-square-o
            class: quota-accept-btn
        service: oro_sale.operation.frontend_guest_quote_submit_to_order

action_groups:
    oro_sale_quote_duplicate:
        parameters:
            quote:
                type: 'Oro\Bundle\SaleBundle\Entity\Quote'
            copy_notes:
                type: bool
                default: true
            flush:
                type: bool
                default: true
        actions:
            - '@create_datetime':
                attribute: $.currentDatetime
            - '@run_action_group':
                action_group: oro_sale_quote_duplicate_fields
                results:
                    quoteCopy: $.quoteCopy
                parameters_mapping:
                    quote: $.quote
            - '@assign_value': [$.quoteCopy.createdAt, $.currentDatetime]
            - '@assign_value': [$.quoteCopy.updatedAt, $.currentDatetime]

            - '@foreach':
                conditions:
                    '@equal': [false, $.copy_notes]
                parameters:
                    array: $.quoteCopy.quoteProducts
                    value: $.quoteProduct
                    actions:
                        - '@assign_value': [$.quoteProduct.comment, '']
                        - '@assign_value': [$.quoteProduct.commentCustomer, '']

            - '@flush_entity':
                conditions:
                    '@equal': [true, $.flush]
                parameters:
                    entity: $.quoteCopy

    oro_sale_quote_duplicate_fields:
        parameters:
            quote:
                type: 'Oro\Bundle\SaleBundle\Entity\Quote'
        actions:
            - '@duplicate':
                target: $.quote
                attribute: $.quoteCopy
                settings:
                    - [[setNull], [propertyName, [id]]]
                    - [[setNull], [propertyName, [qid]]]
                    - [[setNull], [propertyName, [demands]]]
                    - [[setNull], [propertyName, [internal_status]]]
                    - [[setNull], [propertyName, [customer_status]]]
                    - [[replaceValue, false], [property, ['Oro\Bundle\SaleBundle\Entity\Quote', expired]]]
                    - [[replaceValue, false], [property, ['Oro\Bundle\SaleBundle\Entity\Quote', pricesChanged]]]
                    - [[keep], [propertyName, [customerUser]]]
                    - [[keep], [propertyName, [customer]]]
                    - [[keep], [propertyName, [organization]]]
                    - [[keep], [propertyName, [owner]]]
                    - [[keep], [propertyName, [website]]]
                    - [[keep], [propertyName, [request]]]
                    - [[keep], [propertyName, [assignedUsers]]]
                    - [[keep], [propertyName, [assignedCustomerUsers]]]
                    - [[keep], [property, ['Oro\Bundle\SaleBundle\Entity\QuoteAddress', country]]]
                    - [[keep], [property, ['Oro\Bundle\SaleBundle\Entity\QuoteAddress', region]]]
                    - [[keep], [property, ['Oro\Bundle\SaleBundle\Entity\QuoteAddress', customerAddress]]]
                    - [[keep], [property, ['Oro\Bundle\SaleBundle\Entity\QuoteAddress', customerUserAddress]]]
                    - [[keep], [propertyType, ['Oro\Bundle\ProductBundle\Entity\Product']]]
                    - [[keep], [propertyType, ['Oro\Bundle\ProductBundle\Entity\ProductUnit']]]
                    - [[keep], [propertyType, ['Oro\Bundle\PaymentTermBundle\Entity\PaymentTerm']]]
                    - [[keep], [propertyType, ['Oro\Bundle\RFPBundle\Entity\RequestProductItem']]]
                    - [[collection], [propertyType, ['Doctrine\Common\Collections\Collection']]]
                    - [[keep], [propertyType, ['Oro\Bundle\ProductBundle\Entity\ProductKitItem']]]

    oro_sale_expire_quote:
        parameters:
            data:
                type: Oro\Bundle\SaleBundle\Entity\Quote
        conditions:
            '@equal': [$.data.expired, false]
        actions:
            - '@assign_value': [$.data.expired, true]
            - '@flush_entity': $.data

    oro_sale_notify_customer_by_email:
        parameters:
            email:
                type: Oro\Bundle\EmailBundle\Form\Model\Email
        acl_resource: oro_email_email_create
        actions:
            - '@call_service_method':
                service: oro_sale.helper.notification
                method: send
                method_parameters: [$.email]

    oro_sale_send_no_quote_alert:
        parameters:
            data:
                type: Oro\Bundle\RFPBundle\Entity\Request
        actions:
            - '@foreach':
                array: $.data.customerUser.salesRepresentatives
                value: $.saleRep
                actions:
                    - '@send_email_template':
                        conditions:
                            '@not_empty': $.data.customerUser.owner
                        parameters:
                            from: $.data.customerUser.owner.email
                            recipients: [$.saleRep]
                            template: 'request_no_quote_alert'
                            entity: $.data
            - '@call_method':
                object: $.data.customerUser.salesRepresentatives
                method: toArray
                attribute: $.customerUserSalesReps
            - '@foreach':
                array: $.data.customer.salesRepresentatives
                value: $.saleRep
                actions:
                    - '@send_email_template':
                        conditions:
                            '@and':
                                - '@not_empty': $.data.customerUser.owner
                                - '@not_in': [$.saleRep, $.customerUserSalesReps]
                        parameters:
                            from: $.data.customerUser.owner.email
                            recipients: [$.saleRep]
                            template: 'request_no_quote_alert'
                            entity: $.data

    oro_sale_frontend_quote_accept_and_submit_to_order:
        service: oro_sale.workflow.action_group.accept_quote_and_submit_order
