styles:
    inputs:
        - 'bundles/oroproduct/default/scss/variables/sku-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-view-layout-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-view-desc-title-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-view-quantity-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-view-line-form-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-view-brand-config.scss'
        - 'bundles/oroproduct/default/scss/variables/embedded-products-config.scss'
        - 'bundles/oroproduct/default/scss/variables/quick-order-config.scss'
        - 'bundles/oroproduct/default/scss/variables/quick-order-add-config.scss'
        - 'bundles/oroproduct/default/scss/variables/quick-order-copy-paste-config.scss'
        - 'bundles/oroproduct/default/scss/variables/quick-order-import-config.scss'
        - 'bundles/oroproduct/default/scss/variables/page-templates/wide-theme-config.scss'
        - 'bundles/oroproduct/default/scss/variables/page-templates/tabs-theme-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-view-attributes-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-view-attribute-box-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-view-desc-list-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-view-benefits-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-view-media/container-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-view-media/gallery-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-item-config.scss'
        - 'bundles/oroproduct/default/scss/variables/view-product-gallery-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-list-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-popup-header-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-action-aria-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-filters-root-config.scss'
        - 'bundles/oroproduct/default/scss/variables/price-hint-content-config.scss'
        - 'bundles/oroproduct/default/scss/variables/search-autocomplete-config.scss'
        - 'bundles/oroproduct/default/scss/variables/elevatezoom-config.scss'
        - 'bundles/oroproduct/default/scss/variables/filter-controls-config.scss'
        - 'bundles/oroproduct/default/scss/variables/product-sticker-config.scss'
        - 'bundles/oroproduct/default/scss/variables/visible-items-counter-config.scss'

        # Product Kit Variables
        - 'bundles/oroproduct/default/scss/variables/product-kit/product-kit-line-items-config.scss'

        - 'bundles/oroproduct/default/scss/components/filter-controls.scss'
        - 'bundles/oroproduct/default/scss/components/quick-order-add/quick-order-add.scss'
        - 'bundles/oroproduct/default/scss/components/product.scss'
        - 'bundles/oroproduct/default/scss/components/product-item.scss'
        - 'bundles/oroproduct/default/scss/components/product-item-list-view.scss'
        - 'bundles/oroproduct/default/scss/components/product-list.scss'
        - 'bundles/oroproduct/default/scss/components/product-filters-root.scss'
        - 'bundles/oroproduct/default/scss/components/elevatezoom.scss'
        - 'bundles/oroproduct/default/scss/components/product-view-media/container.scss'
        - 'bundles/oroproduct/default/scss/components/product-view-media/gallery.scss'
        - 'bundles/oroproduct/default/scss/components/product-view-attributes.scss'
        - 'bundles/oroproduct/default/scss/components/product-view-attributes-container.scss'
        - 'bundles/oroproduct/default/scss/components/product-view-attribute-box.scss'
        - 'bundles/oroproduct/default/scss/components/product-view-attributes-tabs.scss'
        - 'bundles/oroproduct/default/scss/components/product-view-desc-title.scss'
        - 'bundles/oroproduct/default/scss/components/product-view-desc-list.scss'
        - 'bundles/oroproduct/default/scss/components/product-view-benefits.scss'
        - 'bundles/oroproduct/default/scss/components/sku.scss'
        - 'bundles/oroproduct/default/scss/components/product-action-aria.scss'
        - 'bundles/oroproduct/default/scss/components/add-product-from-view-component.scss'
        - 'bundles/oroproduct/default/scss/components/view-product-gallery.scss'
        - 'bundles/oroproduct/default/scss/components/product-popup-header.scss'
        - 'bundles/oroproduct/default/scss/components/search-autocomplete.scss'
        - 'bundles/oroproduct/default/scss/components/visible-items-counter.scss'

        # Product kit styles
        - 'bundles/oroproduct/default/scss/components/product-kit/product-kit-view.scss'
        - 'bundles/oroproduct/default/scss/components/product-kit/product-kit-line-items.scss'

        - 'bundles/oroproduct/default/scss/styles.scss'
