types:
    main:
        label: oro.product.productimage.type.main.label
        dimensions:
            - product_original
            - product_gallery_popup
            - product_gallery_main
            - product_large
            - product_medium
            - product_small
        max_number: 1
    listing:
        label: oro.product.productimage.type.listing.label
        dimensions:
            - product_small
            - product_large
        max_number: 1
    additional:
        label: oro.product.productimage.type.additional.label
        dimensions:
            - product_original
            - product_small
        max_number: ~
dimensions:
    product_original:
        width: ~
        height: ~
        options:
            applyProductImageWatermark: true
    product_gallery_popup:
        width: 836
        height: 620
        options:
            applyProductImageWatermark: true
    product_gallery_main:
        width: 700
        height: 520
        options:
            applyProductImageWatermark: true
            background:
                transparency: 0
    product_large:
        width: 480
        height: 356
        options:
            applyProductImageWatermark: true
            background:
                transparency: 0
    product_medium:
        width: 350
        height: 260
        options:
            applyProductImageWatermark: true
            background:
                transparency: 0
    product_small:
        width: auto
        height: 80
        options:
            applyProductImageWatermark: true
    product_extra_small:
        width: auto
        height: 42
        options:
            applyProductImageWatermark: true
    category_medium:
        width: 315
        height: 260
