services:
    oro_inventory.event_listener.product_manage_inventory_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\ProductManageInventoryFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-view, method: onProductView }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-edit, method: onProductEdit }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-create-step-two, method: onProductEdit }

    oro_inventory.event_listener.product_highlight_low_inventory_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\ProductHighlightLowInventoryFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-view, method: onProductView }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-edit, method: onProductEdit }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-create-step-two, method: onProductEdit }

    oro_inventory.event_listener.category_manage_inventory_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\CategoryManageInventoryFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.category-edit, method: onCategoryEdit }

    oro_inventory.event_listener.category_highlight_low_inventory_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\CategoryHighlightLowInventoryFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.category-edit, method: onCategoryEdit }

    oro_inventory.event_listener.product_inventory_threshold_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\ProductInventoryThresholdFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-view, method: onProductView }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-edit, method: onProductEdit }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-create-step-two, method: onProductEdit }

    oro_inventory.event_listener.product_low_inventory_threshold_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\ProductLowInventoryThresholdFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-view, method: onProductView }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-edit, method: onProductEdit }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-create-step-two, method: onProductEdit }

    oro_inventory.event_listener.category_inventory_threshold_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\CategoryInventoryThresholdFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.category-edit, method: onCategoryEdit }

    oro_inventory.event_listener.category_low_inventory_threshold_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\CategoryLowInventoryThresholdFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.category-edit, method: onCategoryEdit }

    oro_inventory.event_listener.product_back_order_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\ProductBackOrderFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-view, method: onProductView }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-edit, method: onProductEdit }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-create-step-two, method: onProductEdit }

    oro_inventory.event_listener.product_decrement_quantity_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\ProductDecrementQuantityFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-view, method: onProductView }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-edit, method: onProductEdit }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-create-step-two, method: onProductEdit }

    oro_inventory.event_listener.category_inventory_decrement_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\CategoryInventoryDecrementFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.category-edit, method: onCategoryEdit }

    oro_inventory.event_listener.category_inventory_backorder_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\CategoryInventoryBackorderFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.category-edit, method: onCategoryEdit }

    oro_inventory.event_listener.category_quantity_to_order_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\CategoryQuantityToOrderFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.category-edit, method: onCategoryEdit }

    oro_inventory.event_listener.product_upcoming_form_event_listener:
        class: Oro\Bundle\InventoryBundle\EventListener\ProductUpcomingFormViewListener
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-view, method: onProductView }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-edit, method: onProductEdit }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-create-step-two, method: onProductEdit }

    oro_inventory.event_listener.category_upcoming_form_event_listener:
        class: Oro\Bundle\InventoryBundle\EventListener\CategoryUpcomingFormViewListener
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.category-edit, method: onCategoryEdit }

    oro_inventory.event_listener.product_quantity_to_order_form_view_listener:
        class: 'Oro\Bundle\InventoryBundle\EventListener\ProductQuantityToOrderFormViewListener'
        parent: oro_inventory.service.fallback_fields_form_view
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-view, method: onProductView }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-edit, method: onProductEdit }
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.product-create-step-two, method: onProductEdit }

    oro_inventory.event_listener.datagrid_line_items_data.inventory:
        class: Oro\Bundle\InventoryBundle\EventListener\DatagridLineItemsDataInventoryListener
        arguments:
            - '@oro_inventory.provider.upcoming_product_provider'
            - '@oro_inventory.inventory.low_inventory_provider'
            - '@oro_locale.formatter.date_time'
            - '@oro_locale.settings'
        tags:
            - { name: kernel.event_listener, event: oro_product.datagrid_line_items_data.frontend-customer-user-shopping-list-grid, method: onLineItemData }
            - { name: kernel.event_listener, event: oro_product.datagrid_line_items_data.frontend-customer-user-shopping-list-edit-grid, method: onLineItemData }
            - { name: kernel.event_listener, event: oro_product.datagrid_line_items_data.frontend-checkout-line-items-grid, method: onLineItemData }
            - { name: kernel.event_listener, event: oro_product.datagrid_line_items_data.frontend-single-page-checkout-line-items-grid, method: onLineItemData }

    oro_inventory.event_listener.create_order_listener:
        class: Oro\Bundle\InventoryBundle\EventListener\CreateOrderEventListener
        arguments:
            - '@oro_inventory.manager.inventory_quantity_manager'
            - '@oro_inventory.handler.inventory_decrement_status_handler'
            - '@doctrine'
            - '@oro_checkout.data_provider.manager.checkout_line_items'
        tags:
            - { name: kernel.event_listener, event: extendable_action.checkout_complete, method: onCreateOrder, priority: 10 }

    oro_inventory.event_listener.unit_visibility.datagrid:
        parent: oro_product.event_listener.unit_visibility.datagrid_basic
        arguments:
            index_0: 'unit'
            index_2: '@@OroProduct/ProductUnit/Datagrid/decimalQuantity.html.twig'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.inventory-grid, method: onBuildBefore }

    oro_inventory.event_listener.product_flush:
        class: Oro\Bundle\InventoryBundle\EventListener\ProductFlushEventListener
        arguments:
            - "@oro_inventory.manager.inventory_manager"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    oro_inventory.event_listener.product_product_inventory_fields_changed:
        class: Oro\Bundle\InventoryBundle\EventListener\Search\ProductInventoryFieldsChangedListener
        arguments:
            - '@oro_website.indexation_entities_container'
            - '@oro_product.search.product_reindex_manager'
        tags:
            - { name: doctrine.orm.entity_listener, entity: Oro\Bundle\EntityBundle\Entity\EntityFieldFallbackValue, event: postUpdate}
            - { name: kernel.event_listener, event: oro_config.update_after, method: onConfigUpdate }
