services:
    _defaults:
        public: true

    Oro\Bundle\CatalogBundle\Controller\Frontend\ProductController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_theme.provider.theme_configuration, key: Oro\Bundle\ThemeBundle\Provider\ThemeConfigurationProvider }

    Oro\Bundle\CatalogBundle\Controller\CategoryController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\CatalogBundle\Controller\ProductController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\CatalogBundle\Controller\AjaxCatalogController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\CatalogBundle\Controller\CategoryProductsController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
