services:
    oro_catalog.api.category_node_repository:
        class: Oro\Bundle\CatalogBundle\Api\Repository\CategoryNodeRepository
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_api.object_normalizer'
            - '@oro_api.criteria_connector'
            - '@oro_api.query_acl_helper'

    oro_catalog.api.resource_type_resolver.category_product_collection:
        class: Oro\Bundle\FrontendBundle\Api\ResourceTypeResolver
        arguments:
            - 'master_catalog_category_product_collection'
            - ['categoryId']
        tags:
            - { name: oro_frontend.api.resource_type_resolver, routeName: oro_product_frontend_product_index }

    oro_catalog.api.resource_api_url_resolver.category_products_collection:
        class: Oro\Bundle\CatalogBundle\Api\CategoryProductsRestJsonApiResourceApiUrlResolver
        arguments:
            - '@router'
            - '@oro_api.rest.routes_registry'
            - '@oro_api.value_normalizer'
        tags:
            - { name: oro_frontend.api.resource_api_url_resolver, routeName: oro_product_frontend_product_index, requestType: rest&json_api }

    oro_catalog.api.remove_not_available_category_node_from_parent_filter:
        class: Oro\Bundle\CatalogBundle\Api\Processor\RemoveNotAvailableCategoryNodeFromFilter
        arguments:
            - 'parent'
            - '@oro_catalog.api.category_node_repository'
        tags:
            - { name: oro.api.processor, action: get_list, group: build_query, requestType: frontend, class: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode, priority: 55 }

    oro_catalog.api.remove_not_available_category_node_from_root_filter:
        class: Oro\Bundle\CatalogBundle\Api\Processor\RemoveNotAvailableCategoryNodeFromFilter
        arguments:
            - 'root'
            - '@oro_catalog.api.category_node_repository'
        tags:
            - { name: oro.api.processor, action: get_list, group: build_query, requestType: frontend, class: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode, priority: 55 }

    oro_catalog.api.load_category_node:
        class: Oro\Bundle\CatalogBundle\Api\Processor\LoadCategoryNode
        arguments:
            - '@oro_catalog.api.category_node_repository'
        tags:
            - { name: oro.api.processor, action: get, group: load_data, requestType: frontend, class: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode }

    oro_catalog.api.load_category_nodes:
        class: Oro\Bundle\CatalogBundle\Api\Processor\LoadCategoryNodes
        arguments:
            - '@oro_catalog.api.category_node_repository'
        tags:
            - { name: oro.api.processor, action: get_list, group: load_data, requestType: frontend, class: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode }

    oro_catalog.api.compute_category_node_category:
        class: Oro\Bundle\CatalogBundle\Api\Processor\ComputeCategoryNodeCategory
        arguments:
            - '@oro_api.entity_serializer'
            - '@oro_api.doctrine_helper'
            - '@oro_api.entity_accessor'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, collection: true, class: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode, priority: 250 }

    oro_catalog.api.compute_category_node_parent_and_path:
        class: Oro\Bundle\CatalogBundle\Api\Processor\ComputeCategoryNodeParentAndPath
        arguments:
            - '@oro_api.entity_serializer'
            - '@oro_api.doctrine_helper'
        calls:
            - [setSourceEntityClass, ['Oro\Bundle\CatalogBundle\Entity\Category']]
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, collection: true, class: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode }

    oro_catalog.api.subresource.build_query:
        class: Oro\Bundle\CatalogBundle\Api\Processor\BuildCategoryNodeSubresourceQuery
        arguments:
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: get_subresource, group: build_query, requestType: frontend, parentClass: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode, priority: -90 }
            - { name: oro.api.processor, action: get_relationship, group: build_query, requestType: frontend, parentClass: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode, priority: -90 }

    oro_catalog.api.subresource.add_parent_category_node_id_to_path_query:
        class: Oro\Bundle\ApiBundle\Processor\Subresource\Shared\AddParentEntityIdToTreeNodePathQuery
        arguments:
            - '@stof_doctrine_extensions.listener.tree'
            - '@oro_api.doctrine_helper'
        calls:
            - [setSourceEntityClass, ['Oro\Bundle\CatalogBundle\Entity\Category']]
        tags:
            - { name: oro.api.processor, action: get_subresource, group: build_query, requestType: frontend, association: path, parentClass: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode, priority: -140 }
            - { name: oro.api.processor, action: get_relationship, group: build_query, requestType: frontend, association: path, parentClass: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode, priority: -140 }

    oro_catalog.api.subresource.add_parent_category_node_id_to_parent_query:
        class: Oro\Bundle\CatalogBundle\Api\Processor\AddParentEntityIdToCategoryNodeSubresourceQuery
        arguments:
            - '@oro_api.entity_id_helper'
            - 'parentCategory'
        tags:
            - { name: oro.api.processor, action: get_subresource, group: build_query, requestType: frontend, association: parent, parentClass: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode, priority: -140 }
            - { name: oro.api.processor, action: get_relationship, group: build_query, requestType: frontend, association: parent, parentClass: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode, priority: -140 }

    oro_catalog.api.subresource.add_parent_category_node_id_to_category_query:
        class: Oro\Bundle\CatalogBundle\Api\Processor\AddParentEntityIdToCategoryNodeCategorySubresourceQuery
        arguments:
            - '@oro_api.entity_id_helper'
        tags:
            - { name: oro.api.processor, action: get_subresource, group: build_query, requestType: frontend, association: category, parentClass: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode, priority: -140 }
            - { name: oro.api.processor, action: get_relationship, group: build_query, requestType: frontend, association: category, parentClass: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode, priority: -140 }

    oro_catalog.api.subresource.validate_parent_category_node_access:
        class: Oro\Bundle\CatalogBundle\Api\Processor\ValidateParentCategoryNodeAccess
        arguments:
            - '@oro_catalog.api.category_node_repository'
        tags:
            - { name: oro.api.processor, action: get_subresource, group: load_data, requestType: frontend, parentClass: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode, priority: 105 }
            - { name: oro.api.processor, action: get_relationship, group: load_data, requestType: frontend, parentClass: Oro\Bundle\CatalogBundle\Api\Model\CategoryNode, priority: 105 }

    oro_catalog.api.compute_category_urls:
        class: Oro\Bundle\RedirectBundle\Api\Processor\ComputeUrlFields
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_locale.helper.localization'
            - '@oro_config.manager'
            - '@router'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, collection: true, class: Oro\Bundle\CatalogBundle\Entity\Category }

    oro_catalog.api.compute_category_images:
        class: Oro\Bundle\CatalogBundle\Api\Processor\ComputeCategoryImages
        arguments:
            - '@oro_attachment.manager'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, collection: true, class: Oro\Bundle\CatalogBundle\Entity\Category }

    oro_catalog.api.compute_category_path:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeLoadedData\ComputeTreeNodePathField
        arguments:
            - '@oro_api.entity_serializer'
            - '@oro_api.doctrine_helper'
            - 'categoryPath'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, collection: true, class: Oro\Bundle\CatalogBundle\Entity\Category }

    oro_catalog.api.subresource.add_parent_category_id_to_path_query:
        class: Oro\Bundle\ApiBundle\Processor\Subresource\Shared\AddParentEntityIdToTreeNodePathQuery
        arguments:
            - '@stof_doctrine_extensions.listener.tree'
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: get_subresource, group: build_query, requestType: frontend, association: categoryPath, parentClass: Oro\Bundle\CatalogBundle\Entity\Category, priority: -140 }
            - { name: oro.api.processor, action: get_relationship, group: build_query, requestType: frontend, association: categoryPath, parentClass: Oro\Bundle\CatalogBundle\Entity\Category, priority: -140 }

    oro_catalog.api.hide_invisible_product_category:
        class: Oro\Bundle\CatalogBundle\Api\Processor\HideInvisibleProductCategories
        arguments:
            - '@oro_api.query_acl_helper'
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, collection: true, class: Oro\Bundle\ProductBundle\Entity\Product }
