system_configuration:
    groups:
        sitemap:
            title: oro.seo.system_configuration.groups.sitemap.title
            icon: 'fa-map'
        sitemap_default:
            title: oro.seo.system_configuration.groups.sitemap_default.title
        sitemap_product:
            title: oro.seo.system_configuration.groups.sitemap_product.title
        sitemap_category:
            title: oro.seo.system_configuration.groups.sitemap_category.title
        sitemap_page:
            title: oro.seo.system_configuration.groups.sitemap_page.title
        sitemap_robots_txt:
            title: oro.seo.system_configuration.groups.sitemap_robots_txt.title
    fields:
        oro_seo.sitemap_changefreq_product:
            data_type: string
            type: Oro\Bundle\SEOBundle\Form\Type\SitemapChangefreqType
            priority: 100
            options:
                label: oro.seo.system_configuration.fields.changefreq_product.label
                required: true
                constraints:
                    - NotBlank: ~
        oro_seo.sitemap_priority_product:
            data_type: float
            type: Oro\Bundle\SEOBundle\Form\Type\SitemapPriorityType
            search_type: text
            priority: 200
            options:
                label: oro.seo.system_configuration.fields.priority_product.label
                required: true
                constraints:
                    - NotBlank: ~
        oro_seo.sitemap_changefreq_category:
            data_type: string
            type: Oro\Bundle\SEOBundle\Form\Type\SitemapChangefreqType
            priority: 100
            options:
                label: oro.seo.system_configuration.fields.changefreq_category.label
                required: true
                constraints:
                    - NotBlank: ~
        oro_seo.sitemap_priority_category:
            data_type: float
            type: Oro\Bundle\SEOBundle\Form\Type\SitemapPriorityType
            search_type: text
            priority: 200
            options:
                label: oro.seo.system_configuration.fields.priority_category.label
                required: true
                constraints:
                    - NotBlank: ~
        oro_seo.sitemap_changefreq_cms_page:
            data_type: string
            type: Oro\Bundle\SEOBundle\Form\Type\SitemapChangefreqType
            priority: 100
            options:
                label: oro.seo.system_configuration.fields.changefreq_page.label
                required: true
                constraints:
                    - NotBlank: ~
        oro_seo.sitemap_priority_cms_page:
            data_type: float
            type: Oro\Bundle\SEOBundle\Form\Type\SitemapPriorityType
            search_type: text
            priority: 200
            options:
                label: oro.seo.system_configuration.fields.priority_page.label
                required: true
                constraints:
                    - NotBlank: ~
        oro_seo.sitemap_cron_definition:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            priority: 500
            options:
                label: oro.seo.system_configuration.fields.sitemap_cron_definition.label
                required: true
                constraints:
                    - NotBlank: ~
                choices:
                    oro.seo.system_configuration.fields.sitemap_cron_definition.choice.weekly.label: '0 0 * * 0'
                    oro.seo.system_configuration.fields.sitemap_cron_definition.choice.daily.label: '0 0 * * *'
                    oro.seo.system_configuration.fields.sitemap_cron_definition.choice.hourly.label: '0 * * * *'
        oro_seo.sitemap_exclude_landing_pages:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                required: false
                tooltip: oro.seo.system_configuration.fields.sitemap_exclude_landing_pages.tooltip
                label:   oro.seo.system_configuration.fields.sitemap_exclude_landing_pages.label
        oro_seo.sitemap_include_landing_pages_not_in_web_catalog:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                required: false
                tooltip: oro.seo.system_configuration.fields.sitemap_include_landing_pages_not_in_web_catalog.tooltip
                label:   oro.seo.system_configuration.fields.sitemap_include_landing_pages_not_in_web_catalog.label
        oro_seo.sitemap_robots_txt_template:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextareaType
            options:
                required: false
                tooltip: oro.seo.system_configuration.fields.sitemap_robots_txt_template.tooltip
                label: oro.seo.system_configuration.fields.sitemap_robots_txt_template.label

    tree:
        system_configuration:
            platform:
                children:
                    websites:
                        children:
                            sitemap:
                                children:
                                    sitemap_default:
                                        children:
                                            - oro_seo.sitemap_cron_definition
                                    sitemap_product:
                                        children:
                                            - oro_seo.sitemap_changefreq_product
                                            - oro_seo.sitemap_priority_product
                                    sitemap_category:
                                        children:
                                            - oro_seo.sitemap_changefreq_category
                                            - oro_seo.sitemap_priority_category
                                    sitemap_page:
                                        children:
                                            - oro_seo.sitemap_changefreq_cms_page
                                            - oro_seo.sitemap_priority_cms_page
                                            - oro_seo.sitemap_exclude_landing_pages
                                            - oro_seo.sitemap_include_landing_pages_not_in_web_catalog
                                    sitemap_robots_txt:
                                        children:
                                            - oro_seo.sitemap_robots_txt_template
