services:
    _defaults:
        public: true

    Oro\Bundle\CMSBundle\Controller\Frontend\PageController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\CMSBundle\Controller\PageController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\CMSBundle\Controller\ContentWidgetController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_cms.content_widget.type_registry, key: Oro\Bundle\CMSBundle\ContentWidget\ContentWidgetTypeRegistry }
            - { name: container.service_subscriber, id: oro_cms.content_widget.frontend_emulator, key: Oro\Bundle\CMSBundle\ContentWidget\FrontendEmulator }

    Oro\Bundle\CMSBundle\Controller\WysiwygContentController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_cms.tools.wysiwyg_content_checker, key: Oro\Bundle\CMSBundle\Tools\WYSIWYGContentChecker }
            - { name: container.service_subscriber, id: oro_cms.tools.digital_asset_twig_tags_converter, key: Oro\Bundle\CMSBundle\Tools\DigitalAssetTwigTagsConverter }

    Oro\Bundle\CMSBundle\Controller\LoginPageController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\CMSBundle\Controller\ContentBlockController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\CMSBundle\Controller\ContentTemplateController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_cms.provider.content_template_content_provider, key: Oro\Bundle\CMSBundle\Provider\ContentTemplateContentProvider }
