services:
    _defaults:
        public: true

    Oro\Bundle\WebsiteSearchTermBundle\Controller\SearchTermController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: container.service_subscriber }
