services:
    oro_pricing.form.options_configurator.price_rule_editor_options_configurator:
        class: Oro\Bundle\PricingBundle\Form\OptionsConfigurator\PriceRuleEditorOptionsConfigurator
        public: false
        arguments:
            - '@oro_product.autocomplete_fields_provider'
            - '@form.factory'
            - '@twig'
            - '@oro_entity.entity_alias_resolver'

    oro_pricing.form.options_configurator.price_rule_editor_options_configurator.currency:
        class: Oro\Bundle\PricingBundle\Form\OptionsConfigurator\PriceRuleEditorOptionsConfigurator
        public: false
        arguments:
            - '@oro_product.autocomplete_fields_provider.currency'
            - '@form.factory'
            - '@twig'
            - '@oro_entity.entity_alias_resolver'

    oro_pricing.form.options_configurator.price_rule_editor_options_configurator.unit:
        class: Oro\Bundle\PricingBundle\Form\OptionsConfigurator\PriceRuleEditorOptionsConfigurator
        public: false
        arguments:
            - '@oro_product.autocomplete_fields_provider.unit'
            - '@form.factory'
            - '@twig'
            - '@oro_entity.entity_alias_resolver'

    oro_pricing.form.type.price_rule_editor:
        class: Oro\Bundle\PricingBundle\Form\Type\PriceRuleEditorType
        arguments:
            - '@oro_pricing.form.options_configurator.price_rule_editor_options_configurator'
        tags:
            - { name: form.type, alias: oro_pricing_price_rule_editor }

    oro_pricing.form.type.price_rule_editor_text:
        class: Oro\Bundle\PricingBundle\Form\Type\PriceRuleEditorTextType
        arguments:
            - '@oro_pricing.form.options_configurator.price_rule_editor_options_configurator'
        tags:
            - { name: form.type, alias: oro_pricing_price_rule_editor_text }

    oro_pricing.form.type.rule_editor_currency_expression:
        class: Oro\Bundle\PricingBundle\Form\Type\RuleEditorCurrencyExpressionType
        arguments:
            - '@oro_pricing.form.options_configurator.price_rule_editor_options_configurator.currency'
        tags:
            - { name: form.type, alias: oro_pricing_price_rule_editor_currency }

    oro_pricing.form.type.rule_editor_unit_expression:
        class: Oro\Bundle\PricingBundle\Form\Type\RuleEditorUnitExpressionType
        arguments:
            - '@oro_pricing.form.options_configurator.price_rule_editor_options_configurator.unit'
        tags:
            - { name: form.type, alias: oro_pricing_price_rule_editor_unit }

    oro_pricing.form.type.price_list:
        class: 'Oro\Bundle\PricingBundle\Form\Type\PriceListType'
        tags:
            - { name: form.type, alias: oro_pricing_price_list }

    oro_pricing.form.type.price_attribute_price_list:
        class: 'Oro\Bundle\PricingBundle\Form\Type\PriceAttributePriceListType'
        calls:
            - [setDataClass, ['Oro\Bundle\PricingBundle\Entity\PriceAttributePriceList']]
        tags:
            - { name: form.type, alias: oro_pricing_price_attribute_price_list }

    oro_pricing.form.type.price_list_select:
        class: 'Oro\Bundle\PricingBundle\Form\Type\PriceListSelectType'
        tags:
            - { name: form.type, alias: oro_pricing_price_list_select }

    oro_pricing.form.type.product_price_collection:
        class: 'Oro\Bundle\PricingBundle\Form\Type\ProductPriceCollectionType'
        arguments:
            - "@doctrine"
        calls:
            - [setDataClass, ['Oro\Bundle\PricingBundle\Entity\ProductPrice']]
            - [setPriceListClass, ['Oro\Bundle\PricingBundle\Entity\PriceList']]
        tags:
            - { name: form.type, alias: oro_pricing_product_price_collection }

    oro_pricing.form.type.product_price:
        class: 'Oro\Bundle\PricingBundle\Form\Type\ProductPriceType'
        tags:
            - { name: form.type, alias: oro_pricing_product_price }
        calls:
            - [setDataClass, ['Oro\Bundle\PricingBundle\Entity\ProductPrice']]

    oro_pricing.form.type.price_type_selector:
        class: 'Oro\Bundle\PricingBundle\Form\Type\PriceTypeSelectorType'
        tags:
            - { name: form.type, alias: "oro_pricing_price_type" }

    oro_pricing.form.type.price_list_product_price:
        class: 'Oro\Bundle\PricingBundle\Form\Type\PriceListProductPriceType'
        tags:
            - { name: form.type, alias: oro_pricing_price_list_product_price }
        calls:
            - [setDataClass, ['Oro\Bundle\PricingBundle\Entity\ProductPrice']]

    oro_pricing.form.price_list_relation:
        class: 'Oro\Bundle\PricingBundle\Form\Type\PriceListRelationType'
        tags:
            - { name: form.type }

    oro_pricing.form.price_list_collection:
        class: 'Oro\Bundle\PricingBundle\Form\Type\PriceListCollectionType'
        tags:
            - { name: form.type, alias: oro_pricing_price_list_collection }

    oro_pricing.form.price_lists_settings:
        class: 'Oro\Bundle\PricingBundle\Form\Type\PriceListsSettingsType'
        arguments:
            - "@doctrine"
            - "@property_accessor"
        tags:
            - { name: form.type, alias: oro_pricing_price_lists_settings }

    oro_pricing.form.type.product_price_filter:
        class: 'Oro\Bundle\PricingBundle\Form\Type\Filter\ProductPriceFilterType'
        arguments:
            - "@translator"
            - "@doctrine"
            - "@oro_product.formatter.product_unit_label"
        tags:
            - { name: form.type, alias: oro_pricing_product_price_filter }

    oro_pricing.form.extension.customer_type:
        class: 'Oro\Bundle\PricingBundle\Form\Extension\CustomerFormExtension'
        arguments:
            - "@oro_pricing.entity_listener.customer"
        tags:
            - { name: form.type_extension, alias: oro_customer_type, extended_type: Oro\Bundle\CustomerBundle\Form\Type\CustomerType }
            - { name: oro_featuretogle.feature, feature: oro_price_lists_combined }

    oro_pricing.form.extension.customer_type.flat_pricing:
        class: 'Oro\Bundle\PricingBundle\Form\Extension\CustomerFormFlatPricingExtension'
        arguments:
            - "@oro_pricing.entity_listener.customer.flat_pricing"
        tags:
            - { name: form.type_extension, alias: oro_customer_type, extended_type: Oro\Bundle\CustomerBundle\Form\Type\CustomerType }
            - { name: oro_featuretogle.feature, feature: oro_price_lists_flat }

    oro_pricing.form.extension.customer_group_type.flat_pricing:
        class: 'Oro\Bundle\PricingBundle\Form\Extension\CustomerGroupFormFlatPricingExtension'
        arguments:
            - "@oro_pricing.entity_listener.customer_group.flat_pricing"
        tags:
            - { name: form.type_extension, alias: oro_customer_group_type, extended_type: Oro\Bundle\CustomerBundle\Form\Type\CustomerGroupType }
            - { name: oro_featuretogle.feature, feature: oro_price_lists_flat }

    oro_pricing.form.extension.customer_group_type:
        class: 'Oro\Bundle\PricingBundle\Form\Extension\CustomerGroupFormExtension'
        arguments:
            - "@oro_pricing.entity_listener.customer_group"
        tags:
            - { name: form.type_extension, alias: oro_customer_group_type, extended_type: Oro\Bundle\CustomerBundle\Form\Type\CustomerGroupType }
            - { name: oro_featuretogle.feature, feature: oro_price_lists_combined }

    oro_pricing.form.extension.product_type:
        class: 'Oro\Bundle\PricingBundle\Form\Extension\ProductFormExtension'
        arguments:
            - "@doctrine"
            - '@oro_pricing.shard_manager'
            - '@oro_pricing.manager.price_manager'
            - '@security.authorization_checker'
            - '@oro_security.form.field_acl_helper'
        tags:
            - { name: form.type_extension, alias: oro_product, extended_type: Oro\Bundle\ProductBundle\Form\Type\ProductType }
            - { name: oro_featuretogle.feature, feature: oro_price_lists }

    oro_pricing.form.extension.product_type.price_attributes:
        class: Oro\Bundle\PricingBundle\Form\Extension\PriceAttributesProductFormExtension
        arguments:
            - '@doctrine'
            - '@oro_security.acl_helper'
            - '@request_stack'
        tags:
            - { name: form.type_extension, alias: oro_product, extended_type: Oro\Bundle\ProductBundle\Form\Type\ProductType }

    oro_pricing.form.type.price_list_select_with_priority:
        class: 'Oro\Bundle\PricingBundle\Form\Type\PriceListSelectWithPriorityType'
        tags:
            - { name: form.type, alias: oro_pricing_price_list_select_with_priority }

    oro_pricing.form.type.price_list_system_config:
        class: 'Oro\Bundle\PricingBundle\Form\Type\PriceListSystemConfigType'
        arguments:
            - 'Oro\Bundle\PricingBundle\SystemConfig\PriceListConfig'
        tags:
            - { name: form.type, alias: oro_pricing_price_list_system_config }

    oro_pricing.form.type.product_price_unit_selector:
        parent: oro_product.form.type.product_unit_selection
        class: 'Oro\Bundle\PricingBundle\Form\Type\ProductPriceUnitSelectorType'
        tags:
            - { name: form.type, alias: oro_pricing_product_price_unit_selector }

    oro_pricing.form.type.product_attribute_price_collection:
       class: Oro\Bundle\PricingBundle\Form\Type\ProductAttributePriceCollectionType
       arguments:
           - '@translator'
       tags:
           - { name: form.type, alias: oro_pricing_product_attribute_price_collection }

    oro_pricing.form.type.product_attribute_price:
       class: Oro\Bundle\PricingBundle\Form\Type\ProductAttributePriceType
       tags:
           - { name: form.type, alias: oro_pricing_product_attribute_price }

    oro_pricing.form.type.oro_pricing_price_rule:
        class: Oro\Bundle\PricingBundle\Form\Type\PriceRuleType
        tags:
            - { name: form.type, alias: oro_pricing_price_rule }

    oro_pricing.form.type.price_list_filter:
        class: Oro\Bundle\PricingBundle\Form\Type\Filter\PriceListFilterType
        arguments:
            - '@oro_pricing.shard_manager'
        tags:
            - { name: form.type, alias: oro_type_price_list_filter }

    oro_pricing.form.type.strategy_price_list:
        class: Oro\Bundle\PricingBundle\Form\Type\PriceListStrategySelectType
        arguments:
            - '@oro_pricing.pricing_strategy.strategy_register'
            - '@translator'
        tags:
            - { name: form.type, alias: oro_pricing_list_strategy_selection }

    oro_pricing.form.extension.price_list_select_with_priority_type:
        class: 'Oro\Bundle\PricingBundle\Form\Extension\PriceListFormExtension'
        arguments:
            - '@oro_config.manager'
        tags:
            - { name: form.type_extension, alias: oro_pricing_price_list_select_with_priority, extended_type: Oro\Bundle\PricingBundle\Form\Type\PriceListSelectWithPriorityType }

    oro_pricing.form.extension.price_type.frontend:
        class: 'Oro\Bundle\PricingBundle\Form\Extension\FrontendPriceFormExtension'
        arguments:
            - '@oro_frontend.request.frontend_helper'
            - '@oro_pricing.user_currency_manager'
        tags:
            - { name: form.type_extension, extended_type: 'Oro\Bundle\CurrencyBundle\Form\Type\PriceType' }
