services:
    oro_pricing.tests.combined_price_list_schedule_command:
        alias: Oro\Bundle\PricingBundle\Command\CombinedPriceListScheduleCommand
        public: true

    oro_pricing.tests.debug.minimal_prices_selected_price_provider:
        alias: Oro\Bundle\PricingBundle\Debug\Provider\MinimalPricesSelectedPriceProvider
        public: true

    oro_pricing.tests.api.skipped_entity_provider:
        class: Oro\Bundle\ApiBundle\Tests\Functional\Environment\SkippedEntityProvider
        decorates: oro_api.tests.skipped_entity_provider
        arguments:
            - '@.inner'
        calls:
            - [addSkippedEntity, ['Oro\Bundle\PricingBundle\Entity\ProductPrice']]
            - [addSkippedEntity, ['Oro\Bundle\PricingBundle\Entity\PriceListSchedule', ['create']]]

    oro_pricing.tests.entity_name_resolver.data_loader:
        class: Oro\Bundle\PricingBundle\Tests\Functional\Environment\TestEntityNameResolverDataLoader
        decorates: oro_entity.tests.entity_name_resolver.data_loader
        arguments:
            - '@.inner'
