datagrids:
    frontend-requests-grid:
        acl_resource: oro_rfp_frontend_request_view
        extended_entity_name: 'Oro\Bundle\RFPBundle\Entity\Request'
        options:
            frontend: true
            entityHint: oro.rfp.request.entity_plural_label
            entity_pagination: true
            jsmodules:
                - orodatagrid/js/datagrid/builder/html-templates-preloader
        source:
            type: orm
            query:
                select:
                    - request.id
                    - request.createdAt
                    - request.poNumber
                    - request.shipUntil
                    - CONCAT(requestCustomerUser.firstName, ' ', requestCustomerUser.lastName) as customerUserName
                    - JSON_EXTRACT(request.serialized_data, 'internal_status') as internal_status
                    - JSON_EXTRACT(request.serialized_data, 'customer_status') as customer_status
                from:
                    - { table: 'Oro\Bundle\RFPBundle\Entity\Request', alias: request }
                join:
                    left:
                        - { join: request.customerUser, alias: requestCustomerUser }
                where:
                    and:
                        - JSON_EXTRACT(request.serialized_data, 'internal_status') IS NULL OR JSON_EXTRACT(request.serialized_data, 'internal_status') <> :internalStatus
            bind_parameters:
                -   name: internalStatus
                    default: rfp_internal_status.deleted
            hints:
                - HINT_TRANSLATABLE

        columns:
            id:
                label: oro.frontend.rfp.request.id.label
            customer_status:
                label: oro.frontend.rfp.request.customer_status.label
                frontend_template: tpl-loader!orofrontend/templates/datagrid/quote-status.html
                frontend_type: html-template
                customer_statuses: "@oro_entity_extend.enum_options_provider->getEnumChoicesWithIdKey('rfp_customer_status')"
                translatable_options: false
            poNumber:
                label: oro.frontend.rfp.request.po_number.label
            shipUntil:
                label: oro.frontend.rfp.request.ship_until.label
                frontend_type: date
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            customerUserName:
                label: oro.frontend.rfp.request.customer_user.label
        properties:
            id: ~
            view_link:
                type: url
                route: oro_rfp_frontend_request_view
                params: [ id ]
            update_link:
                type: url
                route: oro_rfp_frontend_request_update
                params: [ id ]
            view_aria_label:
                type: translatable
                key: oro.rfp.action.request.view.aria_label
                params: [ id ]
            update_aria_label:
                type: translatable
                key: oro.rfp.action.request.edit.aria_label
                params: [ id ]
            customer_status:
                label: customer_status
        sorters:
            columns:
                customer_status:
                    data_name: customer_status
                customerUserName:
                    data_name: customerUserName
                poNumber:
                    data_name: request.poNumber
                shipUntil:
                    data_name: request.shipUntil
                createdAt:
                    data_name: request.createdAt
            disable_default_sorting: true
        filters:
            columns:
                customer_status:
                    type: enum
                    data_name: customer_status
                    enum_code: rfp_customer_status
                customerUserName:
                    type: string
                    data_name: customerUserName
                poNumber:
                    type: string
                    data_name: request.poNumber
                shipUntil:
                    type: date
                    data_name: request.shipUntil
                createdAt:
                    type: datetime
                    data_name: request.createdAt
        actions:
            view:
                type: navigate
                label: oro.grid.action.view
                ariaLabel: view_aria_label
                link: view_link
                icon: eye
                rowAction: true
                acl_resource: oro_rfp_frontend_request_view
            update:
                type: navigate
                label: oro.grid.action.update
                ariaLabel: update_aria_label
                link: update_link
                icon: pencil-square-o
                rowAction: true
                acl_resource: oro_rfp_frontend_request_update

    frontend-request-line-items-grid:
        acl_resource: oro_rfp_frontend_request_view
        options:
            entityHint: oro.rfp.requestproduct.entity_plural_label
            frontend: true
            toolbarOptions:
                placement:
                    bottom: true
        source:
            type: orm
            query:
                select:
                    - partial request_product.{ id }
                    - request_product.id
                    - request_product.comment
                    - COALESCE(product.sku, request_product.productSku) as productSku
                    - product.id as productId
                from:
                    - { table: 'Oro\Bundle\RFPBundle\Entity\RequestProduct', alias: request_product }
                join:
                    left:
                        - { join: request_product.product, alias: product }
                where:
                    and:
                        - request_product.request = :request_id
            bind_parameters:
                - request_id
        columns:
            product:
                label:         oro.frontend.rfp.request.sections.request_products.columns.item.label
                type:          twig
                frontend_type: html
                template:      '@OroRFP/layouts/default/twig/Datagrid/frontendProduct.html.twig'
            qty:
                label: oro.frontend.rfp.request.sections.request_products.columns.quantity.label
                type: twig
                frontend_type: html
                template: '@OroRFP/layouts/default/twig/Datagrid/frontendProductQty.html.twig'
            price:
                label: oro.frontend.rfp.request.sections.request_products.columns.price.label
                type: twig
                frontend_type: html
                template: '@OroRFP/layouts/default/twig/Datagrid/frontendProductPrice.html.twig'
            notes:
                label: oro.frontend.rfp.request.sections.request_products.columns.notes.label
                type: twig
                frontend_type: html
                template: '@OroRFP/layouts/default/twig/Datagrid/frontendProductNotes.html.twig'
        filters:
            columns:
                productSku:
                    type:      string
                    data_name: product.skuUppercase
                    case_insensitive: false
                    value_conversion: mb_strtoupper
                    label: oro.frontend.rfp.requestproduct.sku.label
