features:
    rfp:
        label: oro.rfp.feature.label
        description: oro.rfp.feature.description
        toggle: oro_rfp.feature_enabled
        routes:
            - 'oro_rfp_request_view'
            - 'oro_rfp_request_info'
            - 'oro_rfp_request_index'
            - 'oro_rfp_request_update'
            - 'oro_rfp_request_product_kit_item_line_item_entry_point'
        operations:
            - 'oro_rfp_create_quote'
        entities:
            - 'Oro\Bundle\RFPBundle\Entity\Request'
            - 'Oro\Bundle\RFPBundle\Entity\RequestProduct'
            - 'Oro\Bundle\RFPBundle\Entity\RequestProductItem'
            - 'Oro\Bundle\RFPBundle\Entity\RequestAdditionalNote'
            - 'Extend\Entity\EV_Rfp_Customer_Status'
            - 'Extend\Entity\EV_Rfp_Internal_Status'
        api_resources:
            - 'Oro\Bundle\RFPBundle\Entity\Request'
            - 'Oro\Bundle\RFPBundle\Entity\RequestProduct'
            - 'Oro\Bundle\RFPBundle\Entity\RequestProductItem'
            - 'Oro\Bundle\RFPBundle\Entity\RequestAdditionalNote'
            - 'Extend\Entity\EV_Rfp_Customer_Status'
            - 'Extend\Entity\EV_Rfp_Internal_Status'
        navigation_items:
            - 'application_menu.sales_tab.request_list'
        configuration:
            - 'rfp_notifications'
            - 'oro_rfp.frontend_product_visibility'
            - 'oro_rfp.backend_product_visibility'

    rfp_frontend:
        label: oro.rfp.feature.frontend_rfp.label
        description: oro.rfp.feature.frontend_rfp.description
        toggle: oro_rfp.frontend_feature_enabled
        dependencies:
            - 'rfp'
            - 'guest_rfp'
        operations:
            - 'oro_rfp_frontend_request_a_quote'
            - 'oro_rfp_frontend_request_create'
            - 'oro_rfp_frontend_request_edit'
        routes:
            - 'oro_rfp_frontend_request_view'
            - 'oro_rfp_frontend_request_index'
            - 'oro_rfp_frontend_request_create'
            - 'oro_rfp_frontend_request_update'
            - 'oro_rfp_frontend_request_product_kit_configuration'
            - 'oro_rfp_frontend_request_tier_prices'

    guest_rfp:
        label: oro.rfp.feature.guest_rfp.label
        description: oro.rfp.feature.guest_rfp.description
        toggle: oro_rfp.guest_rfp
        strategy: affirmative
        configuration:
            - 'guest_rfp_owner_section'
