system_configuration:
    groups:
        guest_shopping_list:
            title: oro.shoppinglist.system_configuration.groups.guest_shopping_list.label
            icon: 'fa-users'
        guest_shopping_list_user_section:
            title: oro.shoppinglist.system_configuration.groups.guest_shopping_list_owner.title
        guest_shopping_list.enable:
            title: oro.shoppinglist.system_configuration.groups.guest_shopping_list.label
        shopping_list:
            title: oro.shoppinglist.system_configuration.groups.shopping_list.title
            icon: 'fa-cogs'
        shopping_list_limit_section:
            title: oro.shoppinglist.system_configuration.groups.shopping_list_limit.title
        shopping_list_options:
            title: oro.shoppinglist.system_configuration.groups.shopping_list_options.title
    fields:
        oro_shopping_list.backend_product_visibility:
            data_type: array
            type: Oro\Bundle\ProductBundle\Form\Type\ProductInventoryStatusSelectType
            options:
                label: oro.shoppinglist.system_configuration.fields.backend_product_visibility.title
        oro_shopping_list.availability_for_guests:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: oro.shoppinglist.system_configuration.fields.availability_for_guests.label
                tooltip: oro.shoppinglist.system_configuration.fields.availability_for_guests.tooltip
        oro_shopping_list.shopping_list_limit:
            data_type: integer
            type: Symfony\Component\Form\Extension\Core\Type\IntegerType
            search_type: text
            options:
                label: oro.shoppinglist.system_configuration.groups.shopping_list_limit.title
                tooltip: oro.shoppinglist.system_configuration.fields.shopping_list_limit.tooltip
                required: true
                constraints:
                    - NotBlank: ~
                    - Range:
                        min: 0
                    - Type:
                        type: integer

        oro_shopping_list.default_guest_shopping_list_owner:
            ui_only: true
            data_type: string
            type: Oro\Bundle\UserBundle\Form\Type\UserSelectType
            priority: 110
            options:
                label: oro.shoppinglist.system_configuration.fields.default_guest_shopping_list_owner.title
                tooltip: oro.shoppinglist.system_configuration.fields.default_guest_shopping_list_owner.tooltip
                required: true
                configs:
                    allowClear: false
                    placeholder: 'oro.user.form.choose_user'
                    result_template_twig: '@OroUser/User/Autocomplete/result.html.twig'
                    selection_template_twig: '@OroUser/User/Autocomplete/selection.html.twig'
                constraints:
                    - NotBlank: ~

        oro_shopping_list.mass_adding_on_product_listing_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: oro.shoppinglist.system_configuration.fields.mass_adding_on_product_listing_enabled.label
                tooltip: oro.shoppinglist.system_configuration.fields.mass_adding_on_product_listing_enabled.tooltip
                required: false
        oro_shopping_list.show_all_in_shopping_list_widget:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: oro.shoppinglist.system_configuration.fields.show_all_in_shopping_list_widget.label
                tooltip: oro.shoppinglist.system_configuration.fields.show_all_in_shopping_list_widget.tooltip
        oro_shopping_list.shopping_lists_max_line_items_per_page:
            data_type: integer
            type: Symfony\Component\Form\Extension\Core\Type\IntegerType
            search_type: text
            options:
                label: oro.shoppinglist.system_configuration.fields.shopping_lists_max_line_items_per_page.label
                tooltip: oro.shoppinglist.system_configuration.fields.shopping_lists_max_line_items_per_page.tooltip
                required: true
                constraints:
                    - NotBlank: ~
                    - Range:
                          min: 200
                          max: 1000

    tree:
        system_configuration:
            commerce:
                children:
                    product_inventory:
                        children:
                            allowed_statuses:
                                children:
                                    backend_inventory_statuses_visibility:
                                        children:
                                            - oro_shopping_list.backend_product_visibility
                    sales:
                        children:
                            shopping_list:
                                children:
                                    shopping_list_limit_section:
                                        children:
                                            - oro_shopping_list.shopping_list_limit
                                    guest_shopping_list.enable:
                                        children:
                                            - oro_shopping_list.availability_for_guests
                                    guest_shopping_list_user_section:
                                        children:
                                            - oro_shopping_list.default_guest_shopping_list_owner
                                    shopping_list_options:
                                        children:
                                            - oro_shopping_list.mass_adding_on_product_listing_enabled
                                            - oro_shopping_list.shopping_lists_max_line_items_per_page
                                            - oro_shopping_list.show_all_in_shopping_list_widget
