navigation:
    menu_config:
        items:
            oro_website_search_search_term:
                label: 'oro.websitesearchterm.navigation.search_terms.label'
                route: 'oro_website_search_term_index'
                route_parameters:
                    gridName: 'website-search-terms'
                extras:
                    routes: [ 'oro_website_search_term_index', 'oro_website_search_term_create', 'oro_website_search_term_view', 'oro_website_search_term_update' ]

        tree:
            application_menu:
                children:
                    marketing_tab:
                        children:
                            oro_website_search_tab:
                                children:
                                    oro_website_search_search_term: ~

    titles:
        oro_website_search_term_index: ~
        oro_website_search_term_create: 'oro.ui.create_entity'
        oro_website_search_term_view: '%title% - oro.ui.view_entity'
        oro_website_search_term_update: '%title% - oro.ui.update_entity'
